(define (problem p4x4ab)
  (:domain mgo)
  (:objects v0 v1 v2 v3 - value )
  (:init  (xpos v0) (ypos v0) (xgoal v3) (ygoal v1)(consec v0 v1)(consec v1 v2)(consec v2 v3))
  (:goal (and  (xpos v3) (ypos v1))))
