(define (problem pN4)
  (:domain AnBn)
  (:objects i0 i1 i2 i3 i4 i5 i6 i7 i8 - index )
  (:init  
	(at i0)
	(current-content a)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(adjacent i4 i5)
	(adjacent i5 i6)
	(adjacent i6 i7)
	(adjacent i7 i8)
	(content i0 a)
	(content i1 a)
	(content i2 a)
	(content i3 a)
	(content i4 b)
	(content i5 b)
	(content i6 b)
	(content i7 b)
	(content i8 empty)
  )
  (:goal (and 
	(at i8)
  ))
)
