( DEFINE ( DOMAIN PROGRAMMING )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	RELATION - OBJECT
	VALUE - OBJECT
	VARIABLE - OBJECT
	STACKROW - OBJECT
	CONDITION-SLOT - OBJECT
	CONDITION-VARIABLE - OBJECT
)
( :CONSTANTS
	ONE ZERO - RELATION
	V0 V1 X1 X2 - VALUE
	Y - VARIABLE
	ROW-0 - STACKROW
	SLOT-0 SLOT-1 SLOT-2 - CONDITION-SLOT
	CVAR-0 CVAR-1 - CONDITION-VARIABLE
)
( :PREDICATES
	( ASSIGNMENT ?VARIABLE0 - VARIABLE ?VALUE1 - VALUE )
	( ORDINAL-1ARY ?RELATION0 - RELATION )
	( INCLUDES-1ARY ?RELATION0 - RELATION ?VALUE1 - VALUE )
	( EMPTY-STACK )
	( NEXT-STACK-ROW ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
	( TOP-STACK ?STACKROW0 - STACKROW )
	( ACCUMULATOR )
	( DONE-EVALUATING )
	( DONE-PROGRAMMING )
	( STACK-MAIN ?STACKROW0 - STACKROW )
	( STACK-LINE-0 ?STACKROW0 - STACKROW )
	( STACK-LINE-1 ?STACKROW0 - STACKROW )
	( STACK-LINE-2 ?STACKROW0 - STACKROW )
	( STACK-LINE-3 ?STACKROW0 - STACKROW )
	( STACK-LINE-4 ?STACKROW0 - STACKROW )
	( TEST-0 )
	( TEST-1 )
	( TEST-2 )
	( TEST-3 )
	( EMPTY-0 )
	( EMPTY-1 )
	( EMPTY-2 )
	( EMPTY-3 )
	( EMPTY-4 )
	( INS-END-1 )
	( INS-END-2 )
	( INS-END-3 )
	( INS-END-4 )
	( CALL-0-0-0 )
	( CALL-0-0-1 )
	( CALL-0-0-2 )
	( CALL-0-0-3 )
	( INS-SET-Y-V0-0 )
	( INS-SET-Y-V0-1 )
	( INS-SET-Y-V0-2 )
	( INS-SET-Y-V0-3 )
	( INS-SET-Y-V1-0 )
	( INS-SET-Y-V1-1 )
	( INS-SET-Y-V1-2 )
	( INS-SET-Y-V1-3 )
	( GOTO-0-0-0 )
	( GOTO-0-0-1 )
	( GOTO-0-0-2 )
	( GOTO-0-0-3 )
	( GOTO-0-0-4 )
	( GOTO-0-1-0 )
	( GOTO-0-1-1 )
	( GOTO-0-1-2 )
	( GOTO-0-1-3 )
	( GOTO-0-1-4 )
	( GOTO-0-2-0 )
	( GOTO-0-2-1 )
	( GOTO-0-2-2 )
	( GOTO-0-2-3 )
	( GOTO-0-2-4 )
	( GOTO-0-3-0 )
	( GOTO-0-3-1 )
	( GOTO-0-3-2 )
	( GOTO-0-3-3 )
	( GOTO-0-3-4 )
	( COND-ASSIGNMENT-0-0-1 ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-ASSIGNMENT-0-0-2 ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-ASSIGNMENT-0-1-1 ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-ASSIGNMENT-0-1-2 ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-ASSIGNMENT-0-2-1 ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-ASSIGNMENT-0-2-2 ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-ASSIGNMENT-0-3-1 ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-ASSIGNMENT-0-3-2 ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-INCLUDES-1ARY-0-0-1 ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-INCLUDES-1ARY-0-0-2 ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-INCLUDES-1ARY-0-1-1 ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-INCLUDES-1ARY-0-1-2 ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-INCLUDES-1ARY-0-2-1 ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-INCLUDES-1ARY-0-2-2 ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-INCLUDES-1ARY-0-3-1 ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( COND-INCLUDES-1ARY-0-3-2 ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE )
	( CURRENT-SLOT ?CONDITION-SLOT0 - CONDITION-SLOT )
	( EMPTYSLOT-0 ?CONDITION-SLOT0 - CONDITION-SLOT )
	( EMPTYSLOT-1 ?CONDITION-SLOT0 - CONDITION-SLOT )
	( EMPTYSLOT-2 ?CONDITION-SLOT0 - CONDITION-SLOT )
	( EMPTYSLOT-3 ?CONDITION-SLOT0 - CONDITION-SLOT )
	( POSSIBLE-VALUE ?CONDITION-SLOT0 - CONDITION-SLOT ?VALUE1 - VALUE )
)
( :FUNCTIONS
	( TOTAL-COST )
)
( :ACTION PROGRAM-SET-Y-V0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V1 ) )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-SET-Y-V0-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-SET-Y-V0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V1 ) )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-SET-Y-V0-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-SET-Y-V0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V1 ) )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-SET-Y-V0-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-SET-Y-V0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V1 ) )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-SET-Y-V0-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-SET-Y-V1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V0 ) )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-SET-Y-V1-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-SET-Y-V1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V0 ) )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-SET-Y-V1-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-SET-Y-V1-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V0 ) )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-SET-Y-V1-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-SET-Y-V1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V0 ) )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-SET-Y-V1-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-2 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-0 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-3 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-0 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-4 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-0 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-0 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-1 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-3 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-1 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-4 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-1 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-0 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-2 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-1 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-2 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-2-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-4 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-2 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-3-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( GOTO-0-3-0 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-3 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-3-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( GOTO-0-3-1 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-3 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-3-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( GOTO-0-3-2 )
		( FORALL
			( ?CONDITION-SLOT1 - CONDITION-SLOT )
			( EMPTYSLOT-3 ?CONDITION-SLOT1 )
		)
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-END-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
		( TEST-0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-END-1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
		( TEST-0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-END-2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
		( TEST-0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-END-3 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-4 )
		( STACK-LINE-4 ?STACKROW0 )
		( TEST-0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-END-4 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-CALL-0-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( CALL-0-0-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( CALL-0-0-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( CALL-0-0-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( CALL-0-0-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COND-ASSIGNMENT-0-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-0 SLOT-1 )
		( CURRENT-SLOT SLOT-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-0 SLOT-1 ) )
		( COND-ASSIGNMENT-0-0-1 ?VARIABLE0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-ASSIGNMENT-0-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-0 SLOT-2 )
		( CURRENT-SLOT SLOT-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-0 SLOT-2 ) )
		( COND-ASSIGNMENT-0-0-2 ?VARIABLE0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-ASSIGNMENT-1-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-1 SLOT-1 )
		( CURRENT-SLOT SLOT-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-1 SLOT-1 ) )
		( COND-ASSIGNMENT-0-1-1 ?VARIABLE0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-ASSIGNMENT-1-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-1 SLOT-2 )
		( CURRENT-SLOT SLOT-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-1 SLOT-2 ) )
		( COND-ASSIGNMENT-0-1-2 ?VARIABLE0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-ASSIGNMENT-2-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-2 SLOT-1 )
		( CURRENT-SLOT SLOT-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-2 SLOT-1 ) )
		( COND-ASSIGNMENT-0-2-1 ?VARIABLE0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-ASSIGNMENT-2-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-2 SLOT-2 )
		( CURRENT-SLOT SLOT-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-2 SLOT-2 ) )
		( COND-ASSIGNMENT-0-2-2 ?VARIABLE0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-ASSIGNMENT-3-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-3 SLOT-1 )
		( CURRENT-SLOT SLOT-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-3 SLOT-1 ) )
		( COND-ASSIGNMENT-0-3-1 ?VARIABLE0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-ASSIGNMENT-3-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-3 SLOT-2 )
		( CURRENT-SLOT SLOT-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-3 SLOT-2 ) )
		( COND-ASSIGNMENT-0-3-2 ?VARIABLE0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-INCLUDES-1ARY-0-1
  :PARAMETERS ( ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-0 SLOT-1 )
		( CURRENT-SLOT SLOT-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
		( ORDINAL-1ARY ?RELATION0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-0 SLOT-1 ) )
		( COND-INCLUDES-1ARY-0-0-1 ?RELATION0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-INCLUDES-1ARY-0-2
  :PARAMETERS ( ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-0 SLOT-2 )
		( CURRENT-SLOT SLOT-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
		( ORDINAL-1ARY ?RELATION0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-0 SLOT-2 ) )
		( COND-INCLUDES-1ARY-0-0-2 ?RELATION0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-INCLUDES-1ARY-1-1
  :PARAMETERS ( ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-1 SLOT-1 )
		( CURRENT-SLOT SLOT-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
		( ORDINAL-1ARY ?RELATION0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-1 SLOT-1 ) )
		( COND-INCLUDES-1ARY-0-1-1 ?RELATION0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-INCLUDES-1ARY-1-2
  :PARAMETERS ( ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-1 SLOT-2 )
		( CURRENT-SLOT SLOT-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
		( ORDINAL-1ARY ?RELATION0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-1 SLOT-2 ) )
		( COND-INCLUDES-1ARY-0-1-2 ?RELATION0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-INCLUDES-1ARY-2-1
  :PARAMETERS ( ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-2 SLOT-1 )
		( CURRENT-SLOT SLOT-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
		( ORDINAL-1ARY ?RELATION0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-2 SLOT-1 ) )
		( COND-INCLUDES-1ARY-0-2-1 ?RELATION0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-INCLUDES-1ARY-2-2
  :PARAMETERS ( ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-2 SLOT-2 )
		( CURRENT-SLOT SLOT-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
		( ORDINAL-1ARY ?RELATION0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-2 SLOT-2 ) )
		( COND-INCLUDES-1ARY-0-2-2 ?RELATION0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-INCLUDES-1ARY-3-1
  :PARAMETERS ( ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-3 SLOT-1 )
		( CURRENT-SLOT SLOT-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
		( ORDINAL-1ARY ?RELATION0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-3 SLOT-1 ) )
		( COND-INCLUDES-1ARY-0-3-1 ?RELATION0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-COND-INCLUDES-1ARY-3-2
  :PARAMETERS ( ?RELATION0 - RELATION ?CONDITION-VARIABLE1 - CONDITION-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTYSLOT-3 SLOT-2 )
		( CURRENT-SLOT SLOT-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
		( ORDINAL-1ARY ?RELATION0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTYSLOT-3 SLOT-2 ) )
		( COND-INCLUDES-1ARY-0-3-2 ?RELATION0 ?CONDITION-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-SET-Y-V0-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V1 ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-SET-Y-V0-0 )
	)
  :EFFECT
	( AND
		( ASSIGNMENT Y V0 )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-SET-Y-V0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V1 ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( INS-SET-Y-V0-1 )
	)
  :EFFECT
	( AND
		( ASSIGNMENT Y V0 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-SET-Y-V0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V1 ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( INS-SET-Y-V0-2 )
	)
  :EFFECT
	( AND
		( ASSIGNMENT Y V0 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-SET-Y-V0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V1 ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( INS-SET-Y-V0-3 )
	)
  :EFFECT
	( AND
		( ASSIGNMENT Y V0 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-SET-Y-V1-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V0 ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-SET-Y-V1-0 )
	)
  :EFFECT
	( AND
		( ASSIGNMENT Y V1 )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-SET-Y-V1-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V0 ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( INS-SET-Y-V1-1 )
	)
  :EFFECT
	( AND
		( ASSIGNMENT Y V1 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-SET-Y-V1-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V0 ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( INS-SET-Y-V1-2 )
	)
  :EFFECT
	( AND
		( ASSIGNMENT Y V1 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-SET-Y-V1-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ASSIGNMENT Y V0 ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( INS-SET-Y-V1-3 )
	)
  :EFFECT
	( AND
		( ASSIGNMENT Y V1 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-2 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-3 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-4 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-3 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-4 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-1 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-2-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-4 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-3-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-3-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-3-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-3-1 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-3-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-3-2 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-2 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-3 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-4 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-3 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-4 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-1 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-2-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-4 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-3-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-3-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-3-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-3-1 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-3-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-3-2 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-1 ROW-0 )
		( INS-END-1 )
		( TEST-0 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ZERO X1 )
		( INCLUDES-1ARY ONE X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-2 ROW-0 )
		( INS-END-2 )
		( TEST-0 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ZERO X1 )
		( INCLUDES-1ARY ONE X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-3 ROW-0 )
		( INS-END-3 )
		( TEST-0 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ZERO X1 )
		( INCLUDES-1ARY ONE X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-4 ROW-0 )
		( INS-END-4 )
		( TEST-0 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ZERO X1 )
		( INCLUDES-1ARY ONE X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-1 ROW-0 )
		( INS-END-1 )
		( TEST-1 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-1 ) )
		( TEST-2 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ONE X1 )
		( INCLUDES-1ARY ZERO X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-1-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-2 ROW-0 )
		( INS-END-2 )
		( TEST-1 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-1 ) )
		( TEST-2 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ONE X1 )
		( INCLUDES-1ARY ZERO X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-3 ROW-0 )
		( INS-END-3 )
		( TEST-1 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-1 ) )
		( TEST-2 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ONE X1 )
		( INCLUDES-1ARY ZERO X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-4 ROW-0 )
		( INS-END-4 )
		( TEST-1 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-1 ) )
		( TEST-2 )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ONE X1 )
		( INCLUDES-1ARY ZERO X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-1 ROW-0 )
		( INS-END-1 )
		( TEST-2 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-2 ) )
		( TEST-3 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ONE X1 )
		( INCLUDES-1ARY ONE X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-2-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-2 ROW-0 )
		( INS-END-2 )
		( TEST-2 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-2 ) )
		( TEST-3 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ONE X1 )
		( INCLUDES-1ARY ONE X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-2-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-3 ROW-0 )
		( INS-END-3 )
		( TEST-2 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-2 ) )
		( TEST-3 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ONE X1 )
		( INCLUDES-1ARY ONE X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-2-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-4 ROW-0 )
		( INS-END-4 )
		( TEST-2 )
		( ASSIGNMENT Y V0 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-2 ) )
		( TEST-3 )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( ORDINAL-1ARY ZERO )
		( ORDINAL-1ARY ONE )
		( INCLUDES-1ARY ONE X1 )
		( INCLUDES-1ARY ONE X2 )
		( FORALL
			( ?VARIABLE1 - VARIABLE ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( NOT ( ASSIGNMENT ?VARIABLE1 ?VALUE2 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION )
			( WHEN
				( AND
					( ORDINAL-1ARY ?RELATION1 )
				)
				( NOT ( ORDINAL-1ARY ?RELATION1 ) )
			)
		)
		( FORALL
			( ?RELATION1 - RELATION ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( NOT ( INCLUDES-1ARY ?RELATION1 ?VALUE2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-3-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-1 ROW-0 )
		( INS-END-1 )
		( TEST-3 )
		( ASSIGNMENT Y V1 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-3-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-2 ROW-0 )
		( INS-END-2 )
		( TEST-3 )
		( ASSIGNMENT Y V1 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-3-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-3 ROW-0 )
		( INS-END-3 )
		( TEST-3 )
		( ASSIGNMENT Y V1 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-3-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-4 ROW-0 )
		( INS-END-4 )
		( TEST-3 )
		( ASSIGNMENT Y V1 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-4 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-4 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-4 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-4 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-2-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-2-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-2-4
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-4 )
		( TEST-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-4 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-3-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-3-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-3-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-3-4
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-4 )
		( TEST-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-4 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-ASSIGNMENT-0-0-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?VARIABLE1 - VARIABLE )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( COND-ASSIGNMENT-0-0-1 ?VARIABLE1 CVAR-1 )
		( CURRENT-SLOT SLOT-0 )
		( NOT ( DONE-EVALUATING ) )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-0 ) )
		( CURRENT-SLOT SLOT-1 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-ASSIGNMENT-0-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?VARIABLE1 - VARIABLE )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( COND-ASSIGNMENT-0-0-2 ?VARIABLE1 CVAR-1 )
		( CURRENT-SLOT SLOT-1 )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-1 ) )
		( CURRENT-SLOT SLOT-2 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-2 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-ASSIGNMENT-0-1-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?VARIABLE1 - VARIABLE )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( COND-ASSIGNMENT-0-1-1 ?VARIABLE1 CVAR-1 )
		( CURRENT-SLOT SLOT-0 )
		( NOT ( DONE-EVALUATING ) )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-0 ) )
		( CURRENT-SLOT SLOT-1 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-ASSIGNMENT-0-1-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?VARIABLE1 - VARIABLE )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( COND-ASSIGNMENT-0-1-2 ?VARIABLE1 CVAR-1 )
		( CURRENT-SLOT SLOT-1 )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-1 ) )
		( CURRENT-SLOT SLOT-2 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-2 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-ASSIGNMENT-0-2-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?VARIABLE1 - VARIABLE )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( COND-ASSIGNMENT-0-2-1 ?VARIABLE1 CVAR-1 )
		( CURRENT-SLOT SLOT-0 )
		( NOT ( DONE-EVALUATING ) )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-0 ) )
		( CURRENT-SLOT SLOT-1 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-ASSIGNMENT-0-2-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?VARIABLE1 - VARIABLE )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( COND-ASSIGNMENT-0-2-2 ?VARIABLE1 CVAR-1 )
		( CURRENT-SLOT SLOT-1 )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-1 ) )
		( CURRENT-SLOT SLOT-2 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-2 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-ASSIGNMENT-0-3-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?VARIABLE1 - VARIABLE )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( COND-ASSIGNMENT-0-3-1 ?VARIABLE1 CVAR-1 )
		( CURRENT-SLOT SLOT-0 )
		( NOT ( DONE-EVALUATING ) )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-0 ) )
		( CURRENT-SLOT SLOT-1 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-ASSIGNMENT-0-3-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?VARIABLE1 - VARIABLE )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( COND-ASSIGNMENT-0-3-2 ?VARIABLE1 CVAR-1 )
		( CURRENT-SLOT SLOT-1 )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-1 ) )
		( CURRENT-SLOT SLOT-2 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
					( ASSIGNMENT ?VARIABLE1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-2 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-INCLUDES-1ARY-0-0-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?RELATION1 - RELATION )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( COND-INCLUDES-1ARY-0-0-1 ?RELATION1 CVAR-1 )
		( CURRENT-SLOT SLOT-0 )
		( NOT ( DONE-EVALUATING ) )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-0 ) )
		( CURRENT-SLOT SLOT-1 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-INCLUDES-1ARY-0-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?RELATION1 - RELATION )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( COND-INCLUDES-1ARY-0-0-2 ?RELATION1 CVAR-1 )
		( CURRENT-SLOT SLOT-1 )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-1 ) )
		( CURRENT-SLOT SLOT-2 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-2 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-INCLUDES-1ARY-0-1-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?RELATION1 - RELATION )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( COND-INCLUDES-1ARY-0-1-1 ?RELATION1 CVAR-1 )
		( CURRENT-SLOT SLOT-0 )
		( NOT ( DONE-EVALUATING ) )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-0 ) )
		( CURRENT-SLOT SLOT-1 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-INCLUDES-1ARY-0-1-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?RELATION1 - RELATION )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( COND-INCLUDES-1ARY-0-1-2 ?RELATION1 CVAR-1 )
		( CURRENT-SLOT SLOT-1 )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-1 ) )
		( CURRENT-SLOT SLOT-2 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-2 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-INCLUDES-1ARY-0-2-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?RELATION1 - RELATION )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( COND-INCLUDES-1ARY-0-2-1 ?RELATION1 CVAR-1 )
		( CURRENT-SLOT SLOT-0 )
		( NOT ( DONE-EVALUATING ) )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-0 ) )
		( CURRENT-SLOT SLOT-1 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-INCLUDES-1ARY-0-2-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?RELATION1 - RELATION )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( COND-INCLUDES-1ARY-0-2-2 ?RELATION1 CVAR-1 )
		( CURRENT-SLOT SLOT-1 )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-1 ) )
		( CURRENT-SLOT SLOT-2 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-2 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-INCLUDES-1ARY-0-3-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?RELATION1 - RELATION )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( COND-INCLUDES-1ARY-0-3-1 ?RELATION1 CVAR-1 )
		( CURRENT-SLOT SLOT-0 )
		( NOT ( DONE-EVALUATING ) )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-0 ) )
		( CURRENT-SLOT SLOT-1 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION STEP-COND-INCLUDES-1ARY-0-3-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?RELATION1 - RELATION )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( COND-INCLUDES-1ARY-0-3-2 ?RELATION1 CVAR-1 )
		( CURRENT-SLOT SLOT-1 )
	)
  :EFFECT
	( AND
		( NOT ( CURRENT-SLOT SLOT-1 ) )
		( CURRENT-SLOT SLOT-2 )
		( FORALL
			( ?VALUE2 - VALUE )
			( WHEN
				( AND
					( POSSIBLE-VALUE SLOT-1 ?VALUE2 )
					( INCLUDES-1ARY ?RELATION1 ?VALUE2 )
				)
				( AND
					( POSSIBLE-VALUE SLOT-2 ?VALUE2 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( CURRENT-SLOT SLOT-2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( FORALL
			( ?VALUE1 - VALUE )
			( WHEN
				( POSSIBLE-VALUE SLOT-2 ?VALUE1 )
				( AND
					( ACCUMULATOR )
					( NOT ( POSSIBLE-VALUE SLOT-2 ?VALUE1 ) )
				)
			)
		)
		( NOT ( CURRENT-SLOT SLOT-2 ) )
		( CURRENT-SLOT SLOT-0 )
		( FORALL
			( ?VALUE1 - VALUE )
			( AND
				( NOT ( POSSIBLE-VALUE SLOT-1 ?VALUE1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( CURRENT-SLOT SLOT-2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( FORALL
			( ?VALUE1 - VALUE )
			( WHEN
				( POSSIBLE-VALUE SLOT-2 ?VALUE1 )
				( AND
					( ACCUMULATOR )
					( NOT ( POSSIBLE-VALUE SLOT-2 ?VALUE1 ) )
				)
			)
		)
		( NOT ( CURRENT-SLOT SLOT-2 ) )
		( CURRENT-SLOT SLOT-0 )
		( FORALL
			( ?VALUE1 - VALUE )
			( AND
				( NOT ( POSSIBLE-VALUE SLOT-1 ?VALUE1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( CURRENT-SLOT SLOT-2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( FORALL
			( ?VALUE1 - VALUE )
			( WHEN
				( POSSIBLE-VALUE SLOT-2 ?VALUE1 )
				( AND
					( ACCUMULATOR )
					( NOT ( POSSIBLE-VALUE SLOT-2 ?VALUE1 ) )
				)
			)
		)
		( NOT ( CURRENT-SLOT SLOT-2 ) )
		( CURRENT-SLOT SLOT-0 )
		( FORALL
			( ?VALUE1 - VALUE )
			( AND
				( NOT ( POSSIBLE-VALUE SLOT-1 ?VALUE1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( CURRENT-SLOT SLOT-2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( FORALL
			( ?VALUE1 - VALUE )
			( WHEN
				( POSSIBLE-VALUE SLOT-2 ?VALUE1 )
				( AND
					( ACCUMULATOR )
					( NOT ( POSSIBLE-VALUE SLOT-2 ?VALUE1 ) )
				)
			)
		)
		( NOT ( CURRENT-SLOT SLOT-2 ) )
		( CURRENT-SLOT SLOT-0 )
		( FORALL
			( ?VALUE1 - VALUE )
			( AND
				( NOT ( POSSIBLE-VALUE SLOT-1 ?VALUE1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
)
