# Training Set
./gen.py 2 False a
./gen.py 2 False b
./gen.py 2 False c
./gen.py 2 False d
./gen.py 3 False a
./gen.py 3 False b
./gen.py 3 False c
./gen.py 3 False d
./gen.py 4 False a
./gen.py 4 False b
./gen.py 4 False c
./gen.py 4 False d
./gen.py 5 False a
./gen.py 5 False b
./gen.py 5 False c
./gen.py 5 False d
./gen.py 6 False a
./gen.py 6 False b
./gen.py 6 False c
./gen.py 6 False d
./gen.py 7 False a
./gen.py 7 False b
./gen.py 7 False c
./gen.py 7 False d
./gen.py 8 False a
./gen.py 8 False b
./gen.py 8 False c
./gen.py 8 False d
./gen.py 9 False a
./gen.py 9 False b
./gen.py 9 False c
./gen.py 9 False d
./gen.py 10 False a
./gen.py 10 False b
./gen.py 10 False c
./gen.py 10 False d
./gen.py 11 False a
./gen.py 11 False b
./gen.py 11 False c
./gen.py 11 False d
./gen.py 12 False a
./gen.py 12 False b
./gen.py 12 False c
./gen.py 12 False d
./gen.py 13 False a
./gen.py 13 False b
./gen.py 13 False c
./gen.py 13 False d
./gen.py 14 False a
./gen.py 14 False b
./gen.py 14 False c
./gen.py 14 False d
./gen.py 15 False a
./gen.py 15 False b
./gen.py 15 False c
./gen.py 15 False d
./gen.py 16 False a
./gen.py 16 False b
./gen.py 16 False c
./gen.py 16 False d
./gen.py 17 False a
./gen.py 17 False b
./gen.py 17 False c
./gen.py 17 False d
./gen.py 18 False a
./gen.py 18 False b
./gen.py 18 False c
./gen.py 18 False d
./gen.py 19 False a
./gen.py 19 False b
./gen.py 19 False c
./gen.py 19 False d
./gen.py 20 False a
./gen.py 20 False b
./gen.py 20 False c
./gen.py 20 False d
./gen.py 21 False a
./gen.py 21 False b
./gen.py 21 False c
./gen.py 21 False d
./gen.py 2 True a
./gen.py 3 True a
./gen.py 4 True a
./gen.py 5 True a
./gen.py 6 True a
./gen.py 7 True a
./gen.py 8 True a
./gen.py 9 True a
./gen.py 10 True a
./gen.py 11 True a
./gen.py 12 True a
./gen.py 13 True a
./gen.py 14 True a
./gen.py 15 True a
./gen.py 16 True a
./gen.py 17 True a
./gen.py 18 True a
./gen.py 19 True a
./gen.py 20 True a
./gen.py 21 True a
