(define (problem gripper5-pos-a)
  (:domain gripper)
  (:objects b1 b2 b3 b4 b5 - ball )
  (:init (at-robby roomA) (free left) (free right) ( next-ball b1 ) ( at b5 roomB ) 
     (succ-balls b1 b2)
     (succ-balls b2 b3)
     (succ-balls b3 b4)
     (succ-balls b4 b5)
     (at b1 roomA)
     (at b2 roomA)
     (at b3 roomA)
     (at b4 roomA)
)
  (:goal (and 
      (at b1 roomB )
      (at b2 roomB )
      (at b3 roomB )
      (at b4 roomB )
)))
