(define (problem gripper8-neg-c)
  (:domain gripper)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 - ball )
  (:init (at-robby roomA) (free left) (free right) ( next-ball b1 ) ( at b8 roomB ) 
     (succ-balls b1 b2)
     (succ-balls b2 b3)
     (succ-balls b3 b4)
     (succ-balls b4 b5)
     (succ-balls b5 b6)
     (succ-balls b6 b7)
     (succ-balls b7 b8)
     (at b1 roomA)
     (at b2 roomB)
     (at b3 roomA)
     (at b4 roomA)
     (at b5 roomB)
     (at b6 roomB)
     (at b7 roomA)
)
  (:goal (and 
      (at b1 roomB )
      (at b2 roomA )
      (at b3 roomA )
      (at b4 roomA )
      (at b5 roomB )
      (at b6 roomB )
      (at b7 roomB )
)))
