(define (problem gripper3-neg-b)
  (:domain gripper)
  (:objects b1 b2 b3 - ball )
  (:init (at-robby roomA) (free left) (free right) ( next-ball b1 ) ( at b3 roomB ) 
     (succ-balls b1 b2)
     (succ-balls b2 b3)
     (at b1 roomB)
     (at b2 roomA)
)
  (:goal (and 
      (at b1 roomB )
      (at b2 roomA )
)))
