(define (problem gb6-neg-a)
  (:domain blocks)
  (:objects b1 b2 b3 b4 b5 b6 - block )
  (:init (clear b1) (ontable b6)       ( on b1 b2 )
      ( on b2 b3 )
      ( on b3 b4 )
      ( on b4 b5 )
      ( on b5 b6 )
(empty) (green b5) ) 
  (:goal (and (have b4))))
