(define (problem gb8-neg-b)
  (:domain blocks)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block )
  (:init (clear b1) (ontable b8)       ( on b1 b2 )
      ( on b2 b3 )
      ( on b3 b4 )
      ( on b4 b5 )
      ( on b5 b6 )
      ( on b6 b7 )
      ( on b7 b8 )
(empty) (green b5) ) 
  (:goal (and (have b1))))
