./scripts/neg/aaai20/rp-val/rp-NEG-1-1-a-val.sh experiments/neg/aaai20/rp/1.neg.program > experiments/neg/aaai20/rp/1.neg.val 2> experiments/neg/aaai20/rp/1.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-1-b-val.sh experiments/neg/aaai20/rp/2.neg.program > experiments/neg/aaai20/rp/2.neg.val 2> experiments/neg/aaai20/rp/2.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-1-c-val.sh experiments/neg/aaai20/rp/3.neg.program > experiments/neg/aaai20/rp/3.neg.val 2> experiments/neg/aaai20/rp/3.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-1-d-val.sh experiments/neg/aaai20/rp/4.neg.program > experiments/neg/aaai20/rp/4.neg.val 2> experiments/neg/aaai20/rp/4.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-2-a-val.sh experiments/neg/aaai20/rp/5.neg.program > experiments/neg/aaai20/rp/5.neg.val 2> experiments/neg/aaai20/rp/5.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-2-b-val.sh experiments/neg/aaai20/rp/6.neg.program > experiments/neg/aaai20/rp/6.neg.val 2> experiments/neg/aaai20/rp/6.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-2-c-val.sh experiments/neg/aaai20/rp/7.neg.program > experiments/neg/aaai20/rp/7.neg.val 2> experiments/neg/aaai20/rp/7.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-3-1-a-val.sh experiments/neg/aaai20/rp/8.neg.program > experiments/neg/aaai20/rp/8.neg.val 2> experiments/neg/aaai20/rp/8.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-2-d-val.sh experiments/neg/aaai20/rp/9.neg.program > experiments/neg/aaai20/rp/9.neg.val 2> experiments/neg/aaai20/rp/9.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-3-1-b-val.sh experiments/neg/aaai20/rp/10.neg.program > experiments/neg/aaai20/rp/10.neg.val 2> experiments/neg/aaai20/rp/10.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-3-a-val.sh experiments/neg/aaai20/rp/11.neg.program > experiments/neg/aaai20/rp/11.neg.val 2> experiments/neg/aaai20/rp/11.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-3-1-c-val.sh experiments/neg/aaai20/rp/12.neg.program > experiments/neg/aaai20/rp/12.neg.val 2> experiments/neg/aaai20/rp/12.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-3-b-val.sh experiments/neg/aaai20/rp/13.neg.program > experiments/neg/aaai20/rp/13.neg.val 2> experiments/neg/aaai20/rp/13.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-3-1-d-val.sh experiments/neg/aaai20/rp/14.neg.program > experiments/neg/aaai20/rp/14.neg.val 2> experiments/neg/aaai20/rp/14.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-3-c-val.sh experiments/neg/aaai20/rp/15.neg.program > experiments/neg/aaai20/rp/15.neg.val 2> experiments/neg/aaai20/rp/15.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-3-2-a-val.sh experiments/neg/aaai20/rp/16.neg.program > experiments/neg/aaai20/rp/16.neg.val 2> experiments/neg/aaai20/rp/16.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-3-d-val.sh experiments/neg/aaai20/rp/17.neg.program > experiments/neg/aaai20/rp/17.neg.val 2> experiments/neg/aaai20/rp/17.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-3-2-b-val.sh experiments/neg/aaai20/rp/18.neg.program > experiments/neg/aaai20/rp/18.neg.val 2> experiments/neg/aaai20/rp/18.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-4-a-val.sh experiments/neg/aaai20/rp/19.neg.program > experiments/neg/aaai20/rp/19.neg.val 2> experiments/neg/aaai20/rp/19.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-3-2-c-val.sh experiments/neg/aaai20/rp/20.neg.program > experiments/neg/aaai20/rp/20.neg.val 2> experiments/neg/aaai20/rp/20.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-4-b-val.sh experiments/neg/aaai20/rp/21.neg.program > experiments/neg/aaai20/rp/21.neg.val 2> experiments/neg/aaai20/rp/21.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-3-2-d-val.sh experiments/neg/aaai20/rp/22.neg.program > experiments/neg/aaai20/rp/22.neg.val 2> experiments/neg/aaai20/rp/22.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-4-c-val.sh experiments/neg/aaai20/rp/23.neg.program > experiments/neg/aaai20/rp/23.neg.val 2> experiments/neg/aaai20/rp/23.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-1-4-d-val.sh experiments/neg/aaai20/rp/24.neg.program > experiments/neg/aaai20/rp/24.neg.val 2> experiments/neg/aaai20/rp/24.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-1-a-val.sh experiments/neg/aaai20/rp/25.neg.program > experiments/neg/aaai20/rp/25.neg.val 2> experiments/neg/aaai20/rp/25.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-1-b-val.sh experiments/neg/aaai20/rp/26.neg.program > experiments/neg/aaai20/rp/26.neg.val 2> experiments/neg/aaai20/rp/26.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-1-c-val.sh experiments/neg/aaai20/rp/27.neg.program > experiments/neg/aaai20/rp/27.neg.val 2> experiments/neg/aaai20/rp/27.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-1-d-val.sh experiments/neg/aaai20/rp/28.neg.program > experiments/neg/aaai20/rp/28.neg.val 2> experiments/neg/aaai20/rp/28.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-2-a-val.sh experiments/neg/aaai20/rp/29.neg.program > experiments/neg/aaai20/rp/29.neg.val 2> experiments/neg/aaai20/rp/29.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-2-b-val.sh experiments/neg/aaai20/rp/30.neg.program > experiments/neg/aaai20/rp/30.neg.val 2> experiments/neg/aaai20/rp/30.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-2-c-val.sh experiments/neg/aaai20/rp/31.neg.program > experiments/neg/aaai20/rp/31.neg.val 2> experiments/neg/aaai20/rp/31.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-4-1-a-val.sh experiments/neg/aaai20/rp/32.neg.program > experiments/neg/aaai20/rp/32.neg.val 2> experiments/neg/aaai20/rp/32.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-2-d-val.sh experiments/neg/aaai20/rp/33.neg.program > experiments/neg/aaai20/rp/33.neg.val 2> experiments/neg/aaai20/rp/33.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-4-1-b-val.sh experiments/neg/aaai20/rp/34.neg.program > experiments/neg/aaai20/rp/34.neg.val 2> experiments/neg/aaai20/rp/34.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-3-a-val.sh experiments/neg/aaai20/rp/35.neg.program > experiments/neg/aaai20/rp/35.neg.val 2> experiments/neg/aaai20/rp/35.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-4-1-c-val.sh experiments/neg/aaai20/rp/36.neg.program > experiments/neg/aaai20/rp/36.neg.val 2> experiments/neg/aaai20/rp/36.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-3-b-val.sh experiments/neg/aaai20/rp/37.neg.program > experiments/neg/aaai20/rp/37.neg.val 2> experiments/neg/aaai20/rp/37.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-4-1-d-val.sh experiments/neg/aaai20/rp/38.neg.program > experiments/neg/aaai20/rp/38.neg.val 2> experiments/neg/aaai20/rp/38.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-3-c-val.sh experiments/neg/aaai20/rp/39.neg.program > experiments/neg/aaai20/rp/39.neg.val 2> experiments/neg/aaai20/rp/39.neg.val.err
./scripts/neg/aaai20/rp-val/rp-NEG-2-3-d-val.sh experiments/neg/aaai20/rp/40.neg.program > experiments/neg/aaai20/rp/40.neg.val 2> experiments/neg/aaai20/rp/40.neg.val.err

