./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-1-a-val.sh experiments/neg/aaai20/rp/1.neglite.program > experiments/neg/aaai20/rp/1.neglite.val 2> experiments/neg/aaai20/rp/1.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-1-b-val.sh experiments/neg/aaai20/rp/2.neglite.program > experiments/neg/aaai20/rp/2.neglite.val 2> experiments/neg/aaai20/rp/2.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-1-c-val.sh experiments/neg/aaai20/rp/3.neglite.program > experiments/neg/aaai20/rp/3.neglite.val 2> experiments/neg/aaai20/rp/3.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-1-d-val.sh experiments/neg/aaai20/rp/4.neglite.program > experiments/neg/aaai20/rp/4.neglite.val 2> experiments/neg/aaai20/rp/4.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-2-a-val.sh experiments/neg/aaai20/rp/5.neglite.program > experiments/neg/aaai20/rp/5.neglite.val 2> experiments/neg/aaai20/rp/5.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-2-b-val.sh experiments/neg/aaai20/rp/6.neglite.program > experiments/neg/aaai20/rp/6.neglite.val 2> experiments/neg/aaai20/rp/6.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-2-c-val.sh experiments/neg/aaai20/rp/7.neglite.program > experiments/neg/aaai20/rp/7.neglite.val 2> experiments/neg/aaai20/rp/7.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-3-1-a-val.sh experiments/neg/aaai20/rp/8.neglite.program > experiments/neg/aaai20/rp/8.neglite.val 2> experiments/neg/aaai20/rp/8.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-2-d-val.sh experiments/neg/aaai20/rp/9.neglite.program > experiments/neg/aaai20/rp/9.neglite.val 2> experiments/neg/aaai20/rp/9.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-3-1-b-val.sh experiments/neg/aaai20/rp/10.neglite.program > experiments/neg/aaai20/rp/10.neglite.val 2> experiments/neg/aaai20/rp/10.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-3-a-val.sh experiments/neg/aaai20/rp/11.neglite.program > experiments/neg/aaai20/rp/11.neglite.val 2> experiments/neg/aaai20/rp/11.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-3-1-c-val.sh experiments/neg/aaai20/rp/12.neglite.program > experiments/neg/aaai20/rp/12.neglite.val 2> experiments/neg/aaai20/rp/12.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-3-b-val.sh experiments/neg/aaai20/rp/13.neglite.program > experiments/neg/aaai20/rp/13.neglite.val 2> experiments/neg/aaai20/rp/13.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-3-1-d-val.sh experiments/neg/aaai20/rp/14.neglite.program > experiments/neg/aaai20/rp/14.neglite.val 2> experiments/neg/aaai20/rp/14.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-3-c-val.sh experiments/neg/aaai20/rp/15.neglite.program > experiments/neg/aaai20/rp/15.neglite.val 2> experiments/neg/aaai20/rp/15.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-3-2-a-val.sh experiments/neg/aaai20/rp/16.neglite.program > experiments/neg/aaai20/rp/16.neglite.val 2> experiments/neg/aaai20/rp/16.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-3-d-val.sh experiments/neg/aaai20/rp/17.neglite.program > experiments/neg/aaai20/rp/17.neglite.val 2> experiments/neg/aaai20/rp/17.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-3-2-b-val.sh experiments/neg/aaai20/rp/18.neglite.program > experiments/neg/aaai20/rp/18.neglite.val 2> experiments/neg/aaai20/rp/18.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-4-a-val.sh experiments/neg/aaai20/rp/19.neglite.program > experiments/neg/aaai20/rp/19.neglite.val 2> experiments/neg/aaai20/rp/19.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-3-2-c-val.sh experiments/neg/aaai20/rp/20.neglite.program > experiments/neg/aaai20/rp/20.neglite.val 2> experiments/neg/aaai20/rp/20.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-4-b-val.sh experiments/neg/aaai20/rp/21.neglite.program > experiments/neg/aaai20/rp/21.neglite.val 2> experiments/neg/aaai20/rp/21.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-3-2-d-val.sh experiments/neg/aaai20/rp/22.neglite.program > experiments/neg/aaai20/rp/22.neglite.val 2> experiments/neg/aaai20/rp/22.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-4-c-val.sh experiments/neg/aaai20/rp/23.neglite.program > experiments/neg/aaai20/rp/23.neglite.val 2> experiments/neg/aaai20/rp/23.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-1-4-d-val.sh experiments/neg/aaai20/rp/24.neglite.program > experiments/neg/aaai20/rp/24.neglite.val 2> experiments/neg/aaai20/rp/24.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-1-a-val.sh experiments/neg/aaai20/rp/25.neglite.program > experiments/neg/aaai20/rp/25.neglite.val 2> experiments/neg/aaai20/rp/25.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-1-b-val.sh experiments/neg/aaai20/rp/26.neglite.program > experiments/neg/aaai20/rp/26.neglite.val 2> experiments/neg/aaai20/rp/26.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-1-c-val.sh experiments/neg/aaai20/rp/27.neglite.program > experiments/neg/aaai20/rp/27.neglite.val 2> experiments/neg/aaai20/rp/27.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-1-d-val.sh experiments/neg/aaai20/rp/28.neglite.program > experiments/neg/aaai20/rp/28.neglite.val 2> experiments/neg/aaai20/rp/28.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-2-a-val.sh experiments/neg/aaai20/rp/29.neglite.program > experiments/neg/aaai20/rp/29.neglite.val 2> experiments/neg/aaai20/rp/29.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-2-b-val.sh experiments/neg/aaai20/rp/30.neglite.program > experiments/neg/aaai20/rp/30.neglite.val 2> experiments/neg/aaai20/rp/30.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-2-c-val.sh experiments/neg/aaai20/rp/31.neglite.program > experiments/neg/aaai20/rp/31.neglite.val 2> experiments/neg/aaai20/rp/31.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-4-1-a-val.sh experiments/neg/aaai20/rp/32.neglite.program > experiments/neg/aaai20/rp/32.neglite.val 2> experiments/neg/aaai20/rp/32.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-2-d-val.sh experiments/neg/aaai20/rp/33.neglite.program > experiments/neg/aaai20/rp/33.neglite.val 2> experiments/neg/aaai20/rp/33.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-4-1-b-val.sh experiments/neg/aaai20/rp/34.neglite.program > experiments/neg/aaai20/rp/34.neglite.val 2> experiments/neg/aaai20/rp/34.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-3-a-val.sh experiments/neg/aaai20/rp/35.neglite.program > experiments/neg/aaai20/rp/35.neglite.val 2> experiments/neg/aaai20/rp/35.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-4-1-c-val.sh experiments/neg/aaai20/rp/36.neglite.program > experiments/neg/aaai20/rp/36.neglite.val 2> experiments/neg/aaai20/rp/36.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-3-b-val.sh experiments/neg/aaai20/rp/37.neglite.program > experiments/neg/aaai20/rp/37.neglite.val 2> experiments/neg/aaai20/rp/37.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-4-1-d-val.sh experiments/neg/aaai20/rp/38.neglite.program > experiments/neg/aaai20/rp/38.neglite.val 2> experiments/neg/aaai20/rp/38.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-3-c-val.sh experiments/neg/aaai20/rp/39.neglite.program > experiments/neg/aaai20/rp/39.neglite.val 2> experiments/neg/aaai20/rp/39.neglite.val.err
./scripts/neg/aaai20/rp-val/rp-NEGLITE-2-3-d-val.sh experiments/neg/aaai20/rp/40.neglite.program > experiments/neg/aaai20/rp/40.neglite.val 2> experiments/neg/aaai20/rp/40.neglite.val.err

