(define (problem p10-square-brackets)
  (:domain parenthesis)
  (:objects i0 i1 i2 i3 i4 i5 i6 i7 i8 i9 i10 - index )
  (:init  
	(at i0)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(adjacent i4 i5)
	(adjacent i5 i6)
	(adjacent i6 i7)
	(adjacent i7 i8)
	(adjacent i8 i9)
	(adjacent i9 i10)
	(content i0 lsqbra)
	(content i1 rsqbra)
	(content i2 lsqbra)
	(content i3 rsqbra)
	(content i4 lsqbra)
	(content i5 rsqbra)
	(content i6 lsqbra)
	(content i7 rsqbra)
	(content i8 lsqbra)
	(content i9 rsqbra)
  )
  (:goal (and 
	(at i10)
  ))
)
