(define (problem p10)
  (:domain parenthesis)
  (:objects i0 i1 i2 i3 i4 i5 i6 i7 i8 i9 i10 - index )
  (:init  
	(at i0)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(adjacent i4 i5)
	(adjacent i5 i6)
	(adjacent i6 i7)
	(adjacent i7 i8)
	(adjacent i8 i9)
	(adjacent i9 i10)
	(content i0 lpar)
	(content i1 rpar)
	(content i2 lpar)
	(content i3 rpar)
	(content i4 lpar)
	(content i5 rpar)
	(content i6 lpar)
	(content i7 rpar)
	(content i8 lpar)
	(content i9 rpar)
	(current-content lpar )
	(content i10 empty)
  )
  (:goal (and 
	(at i10)
  ))
)
