(define (problem p4b)
  (:domain parenthesis)
  (:objects i0 i1 i2 i3 i4 - index )
  (:init  
	(at i0)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(content i0 lpar)
	(content i1 lpar)
	(content i2 rpar)
	(content i3 rpar)
	(current-content lpar)
	(content i4 empty)	
  )
  (:goal (and 
	(at i4)
  ))
)
