(define (problem p8-curly-brackets)
  (:domain complex-parenthesis)
  (:objects i0 i1 i2 i3 i4 i5 i6 i7 i8 - index )
  (:init  
	(at i0)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(adjacent i4 i5)
	(adjacent i5 i6)
	(adjacent i6 i7)
	(adjacent i7 i8)
	(content i0 lcubra)
	(content i1 lcubra)
	(content i2 lcubra)
	(content i3 lcubra)
	(content i4 rcubra)
	(content i5 rcubra)
	(content i6 rcubra)
	(content i7 rcubra)
	(current-content lcubra)
	(content i8 empty)
  )
  (:goal (and 
	(at i8)
  ))
)
