(define (problem p8-par)
  (:domain complex-parenthesis)
  (:objects i0 i1 i2 i3 i4 i5 i6 i7 i8 - index )
  (:init  
	(at i0)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(adjacent i4 i5)
	(adjacent i5 i6)
	(adjacent i6 i7)
	(adjacent i7 i8)
	(content i0 lpar)
	(content i1 lpar)
	(content i2 lpar)
	(content i3 lpar)
	(content i4 rpar)
	(content i5 rpar)
	(content i6 rpar)
	(content i7 rpar)
	(current-content lpar)
	(content i8 empty)
  )
  (:goal (and 
	(at i8)
  ))
)
