( DEFINE ( DOMAIN TREES_ALT )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	VARIABLE - OBJECT
	NODE - OBJECT
	STACKROW - OBJECT
)
( :CONSTANTS
	CHILD CURRENT - VARIABLE
	N1 N2 N3 N4 N5 N6 N7 - NODE
	ROW0 ROW1 ROW2 ROW3 ROW4 - STACKROW
)
( :PREDICATES
	( LEFT-CHILD ?NODE0 - NODE ?NODE1 - NODE )
	( RIGHT-CHILD ?NODE0 - NODE ?NODE1 - NODE )
	( INTERNAL ?NODE0 - NODE )
	( VISITED ?NODE0 - NODE )
	( ASSIGNMENT ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
	( ISINTERNAL ?VARIABLE0 - VARIABLE )
	( EMPTY-STACK )
	( NEXT-STACK-ROW ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
	( TOP-STACK ?STACKROW0 - STACKROW )
	( STACK-MAIN ?STACKROW0 - STACKROW )
	( STACK-LINE-0 ?STACKROW0 - STACKROW )
	( STACK-LINE-1 ?STACKROW0 - STACKROW )
	( STACK-LINE-2 ?STACKROW0 - STACKROW )
	( STACK-LINE-3 ?STACKROW0 - STACKROW )
	( STACK-LINE-4 ?STACKROW0 - STACKROW )
	( STACK-LINE-5 ?STACKROW0 - STACKROW )
	( STACK-LINE-6 ?STACKROW0 - STACKROW )
	( TEST-0 )
	( CALL-0-0-0 ?VARIABLE0 - VARIABLE )
	( CALL-0-0-1 ?VARIABLE0 - VARIABLE )
	( CALL-0-0-2 ?VARIABLE0 - VARIABLE )
	( CALL-0-0-3 ?VARIABLE0 - VARIABLE )
	( CALL-0-0-4 ?VARIABLE0 - VARIABLE )
	( CALL-0-0-5 ?VARIABLE0 - VARIABLE )
	( EMPTY-0 )
	( EMPTY-1 )
	( EMPTY-2 )
	( EMPTY-3 )
	( EMPTY-4 )
	( EMPTY-5 )
	( EMPTY-6 )
	( INS-COPY-LEFT-0 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-LEFT-1 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-LEFT-2 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-LEFT-3 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-LEFT-4 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-LEFT-5 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-RIGHT-0 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-RIGHT-1 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-RIGHT-2 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-RIGHT-3 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-RIGHT-4 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-COPY-RIGHT-5 ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE )
	( INS-VISIT-0 ?VARIABLE0 - VARIABLE )
	( INS-VISIT-1 ?VARIABLE0 - VARIABLE )
	( INS-VISIT-2 ?VARIABLE0 - VARIABLE )
	( INS-VISIT-3 ?VARIABLE0 - VARIABLE )
	( INS-VISIT-4 ?VARIABLE0 - VARIABLE )
	( INS-VISIT-5 ?VARIABLE0 - VARIABLE )
	( INS-END-1 )
	( INS-END-2 )
	( INS-END-3 )
	( INS-END-4 )
	( INS-END-5 )
	( INS-END-6 )
	( ACCUMULATOR )
	( DONE-EVALUATING )
	( DONE-PROGRAMMING )
	( COND-VISITED-0-0 ?NODE0 - NODE )
	( COND-ASSIGNMENT-0-0 ?VARIABLE0 - VARIABLE ?NODE1 - NODE )
	( COND-ISINTERNAL-0-0 ?VARIABLE0 - VARIABLE )
	( JMP-0-0-2 )
	( JMP-0-0-3 )
	( JMP-0-0-4 )
	( JMP-0-0-5 )
	( JMP-0-0-6 )
	( COND-VISITED-0-1 ?NODE0 - NODE )
	( COND-ASSIGNMENT-0-1 ?VARIABLE0 - VARIABLE ?NODE1 - NODE )
	( COND-ISINTERNAL-0-1 ?VARIABLE0 - VARIABLE )
	( JMP-0-1-0 )
	( JMP-0-1-3 )
	( JMP-0-1-4 )
	( JMP-0-1-5 )
	( JMP-0-1-6 )
	( COND-VISITED-0-2 ?NODE0 - NODE )
	( COND-ASSIGNMENT-0-2 ?VARIABLE0 - VARIABLE ?NODE1 - NODE )
	( COND-ISINTERNAL-0-2 ?VARIABLE0 - VARIABLE )
	( JMP-0-2-0 )
	( JMP-0-2-1 )
	( JMP-0-2-4 )
	( JMP-0-2-5 )
	( JMP-0-2-6 )
	( COND-VISITED-0-3 ?NODE0 - NODE )
	( COND-ASSIGNMENT-0-3 ?VARIABLE0 - VARIABLE ?NODE1 - NODE )
	( COND-ISINTERNAL-0-3 ?VARIABLE0 - VARIABLE )
	( JMP-0-3-0 )
	( JMP-0-3-1 )
	( JMP-0-3-2 )
	( JMP-0-3-5 )
	( JMP-0-3-6 )
	( COND-VISITED-0-4 ?NODE0 - NODE )
	( COND-ASSIGNMENT-0-4 ?VARIABLE0 - VARIABLE ?NODE1 - NODE )
	( COND-ISINTERNAL-0-4 ?VARIABLE0 - VARIABLE )
	( JMP-0-4-0 )
	( JMP-0-4-1 )
	( JMP-0-4-2 )
	( JMP-0-4-3 )
	( JMP-0-4-6 )
	( COND-VISITED-0-5 ?NODE0 - NODE )
	( COND-ASSIGNMENT-0-5 ?VARIABLE0 - VARIABLE ?NODE1 - NODE )
	( COND-ISINTERNAL-0-5 ?VARIABLE0 - VARIABLE )
	( JMP-0-5-0 )
	( JMP-0-5-1 )
	( JMP-0-5-2 )
	( JMP-0-5-3 )
	( JMP-0-5-4 )
)
( :FUNCTIONS
	( TOTAL-COST )
)
( :ACTION PROGRAM-COPY-LEFT-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-COPY-LEFT-0 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-LEFT-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-COPY-LEFT-1 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-LEFT-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-COPY-LEFT-2 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-LEFT-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-COPY-LEFT-3 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-LEFT-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-COPY-LEFT-4 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-LEFT-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-COPY-LEFT-5 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-RIGHT-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-COPY-RIGHT-0 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-RIGHT-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-COPY-RIGHT-1 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-RIGHT-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-COPY-RIGHT-2 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-RIGHT-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-COPY-RIGHT-3 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-RIGHT-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-COPY-RIGHT-4 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-COPY-RIGHT-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-COPY-RIGHT-5 ?VARIABLE0 ?VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-VISIT-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-VISIT-0 ?VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-VISIT-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-VISIT-1 ?VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-VISIT-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-VISIT-2 ?VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-VISIT-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-VISIT-3 ?VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-VISIT-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-VISIT-4 ?VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-VISIT-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-VISIT-5 ?VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION REPEAT-COPY-LEFT-0-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-LEFT-0 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( LEFT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW2 ) )
		( STACK-LINE-1 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-LEFT-0-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-LEFT-1 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( LEFT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW2 ) )
		( STACK-LINE-2 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-LEFT-0-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-LEFT-2 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( LEFT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW2 ) )
		( STACK-LINE-3 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-LEFT-0-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-LEFT-3 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( LEFT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-3 ?STACKROW2 ) )
		( STACK-LINE-4 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-LEFT-0-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-LEFT-4 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( LEFT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-4 ?STACKROW2 ) )
		( STACK-LINE-5 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-LEFT-0-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-LEFT-5 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( LEFT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-5 ?STACKROW2 ) )
		( STACK-LINE-6 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-RIGHT-0-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-RIGHT-0 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( RIGHT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW2 ) )
		( STACK-LINE-1 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-RIGHT-0-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-RIGHT-1 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( RIGHT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW2 ) )
		( STACK-LINE-2 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-RIGHT-0-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-RIGHT-2 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( RIGHT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW2 ) )
		( STACK-LINE-3 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-RIGHT-0-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-RIGHT-3 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( RIGHT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-3 ?STACKROW2 ) )
		( STACK-LINE-4 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-RIGHT-0-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-RIGHT-4 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( RIGHT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-4 ?STACKROW2 ) )
		( STACK-LINE-5 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-COPY-RIGHT-0-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?VARIABLE1 - VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( INS-COPY-RIGHT-5 ?VARIABLE0 ?VARIABLE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE3 - NODE )
			( NOT ( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 ) )
		)
		( FORALL
			( ?NODE3 - NODE ?NODE4 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE4 ?STACKROW2 )
					( RIGHT-CHILD ?NODE3 ?NODE4 )
				)
				( AND
					( ASSIGNMENT ?VARIABLE1 ?NODE3 ?STACKROW2 )
				)
			)
		)
		( NOT ( STACK-LINE-5 ?STACKROW2 ) )
		( STACK-LINE-6 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-VISIT-0-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-VISIT-0 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
				)
				( AND
					( VISITED ?NODE2 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW1 ) )
		( STACK-LINE-1 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-VISIT-0-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-VISIT-1 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
				)
				( AND
					( VISITED ?NODE2 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( STACK-LINE-2 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-VISIT-0-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-VISIT-2 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
				)
				( AND
					( VISITED ?NODE2 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( STACK-LINE-3 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-VISIT-0-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-VISIT-3 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
				)
				( AND
					( VISITED ?NODE2 )
				)
			)
		)
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( STACK-LINE-4 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-VISIT-0-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-VISIT-4 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
				)
				( AND
					( VISITED ?NODE2 )
				)
			)
		)
		( NOT ( STACK-LINE-4 ?STACKROW1 ) )
		( STACK-LINE-5 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-VISIT-0-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-VISIT-5 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
				)
				( AND
					( VISITED ?NODE2 )
				)
			)
		)
		( NOT ( STACK-LINE-5 ?STACKROW1 ) )
		( STACK-LINE-6 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-0-2
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-VISITED-0-0 ?NODE0 )
		( JMP-0-0-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-0-3
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-VISITED-0-0 ?NODE0 )
		( JMP-0-0-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-0-4
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-VISITED-0-0 ?NODE0 )
		( JMP-0-0-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-0-5
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-VISITED-0-0 ?NODE0 )
		( JMP-0-0-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-0-6
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-VISITED-0-0 ?NODE0 )
		( JMP-0-0-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-1-0
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-VISITED-0-1 ?NODE0 )
		( JMP-0-1-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-1-3
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-VISITED-0-1 ?NODE0 )
		( JMP-0-1-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-1-4
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-VISITED-0-1 ?NODE0 )
		( JMP-0-1-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-1-5
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-VISITED-0-1 ?NODE0 )
		( JMP-0-1-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-1-6
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-VISITED-0-1 ?NODE0 )
		( JMP-0-1-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-2-0
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-VISITED-0-2 ?NODE0 )
		( JMP-0-2-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-2-1
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-VISITED-0-2 ?NODE0 )
		( JMP-0-2-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-2-4
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-VISITED-0-2 ?NODE0 )
		( JMP-0-2-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-2-5
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-VISITED-0-2 ?NODE0 )
		( JMP-0-2-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-2-6
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-VISITED-0-2 ?NODE0 )
		( JMP-0-2-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-3-0
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-VISITED-0-3 ?NODE0 )
		( JMP-0-3-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-3-1
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-VISITED-0-3 ?NODE0 )
		( JMP-0-3-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-3-2
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-VISITED-0-3 ?NODE0 )
		( JMP-0-3-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-3-5
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-VISITED-0-3 ?NODE0 )
		( JMP-0-3-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-3-6
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-VISITED-0-3 ?NODE0 )
		( JMP-0-3-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-4-0
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-VISITED-0-4 ?NODE0 )
		( JMP-0-4-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-4-1
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-VISITED-0-4 ?NODE0 )
		( JMP-0-4-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-4-2
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-VISITED-0-4 ?NODE0 )
		( JMP-0-4-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-4-3
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-VISITED-0-4 ?NODE0 )
		( JMP-0-4-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-4-6
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-VISITED-0-4 ?NODE0 )
		( JMP-0-4-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-5-0
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-VISITED-0-5 ?NODE0 )
		( JMP-0-5-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-5-1
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-VISITED-0-5 ?NODE0 )
		( JMP-0-5-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-5-2
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-VISITED-0-5 ?NODE0 )
		( JMP-0-5-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-5-3
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-VISITED-0-5 ?NODE0 )
		( JMP-0-5-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-VISITED-5-4
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-VISITED-0-5 ?NODE0 )
		( JMP-0-5-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-0-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ASSIGNMENT-0-0 ?VARIABLE0 ?NODE1 )
		( JMP-0-0-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-0-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ASSIGNMENT-0-0 ?VARIABLE0 ?NODE1 )
		( JMP-0-0-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-0-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ASSIGNMENT-0-0 ?VARIABLE0 ?NODE1 )
		( JMP-0-0-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-0-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ASSIGNMENT-0-0 ?VARIABLE0 ?NODE1 )
		( JMP-0-0-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-0-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ASSIGNMENT-0-0 ?VARIABLE0 ?NODE1 )
		( JMP-0-0-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-1-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ASSIGNMENT-0-1 ?VARIABLE0 ?NODE1 )
		( JMP-0-1-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-1-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ASSIGNMENT-0-1 ?VARIABLE0 ?NODE1 )
		( JMP-0-1-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-1-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ASSIGNMENT-0-1 ?VARIABLE0 ?NODE1 )
		( JMP-0-1-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-1-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ASSIGNMENT-0-1 ?VARIABLE0 ?NODE1 )
		( JMP-0-1-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-1-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ASSIGNMENT-0-1 ?VARIABLE0 ?NODE1 )
		( JMP-0-1-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-2-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ASSIGNMENT-0-2 ?VARIABLE0 ?NODE1 )
		( JMP-0-2-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-2-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ASSIGNMENT-0-2 ?VARIABLE0 ?NODE1 )
		( JMP-0-2-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-2-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ASSIGNMENT-0-2 ?VARIABLE0 ?NODE1 )
		( JMP-0-2-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-2-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ASSIGNMENT-0-2 ?VARIABLE0 ?NODE1 )
		( JMP-0-2-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-2-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ASSIGNMENT-0-2 ?VARIABLE0 ?NODE1 )
		( JMP-0-2-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-3-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ASSIGNMENT-0-3 ?VARIABLE0 ?NODE1 )
		( JMP-0-3-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-3-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ASSIGNMENT-0-3 ?VARIABLE0 ?NODE1 )
		( JMP-0-3-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-3-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ASSIGNMENT-0-3 ?VARIABLE0 ?NODE1 )
		( JMP-0-3-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-3-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ASSIGNMENT-0-3 ?VARIABLE0 ?NODE1 )
		( JMP-0-3-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-3-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ASSIGNMENT-0-3 ?VARIABLE0 ?NODE1 )
		( JMP-0-3-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-4-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ASSIGNMENT-0-4 ?VARIABLE0 ?NODE1 )
		( JMP-0-4-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-4-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ASSIGNMENT-0-4 ?VARIABLE0 ?NODE1 )
		( JMP-0-4-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-4-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ASSIGNMENT-0-4 ?VARIABLE0 ?NODE1 )
		( JMP-0-4-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-4-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ASSIGNMENT-0-4 ?VARIABLE0 ?NODE1 )
		( JMP-0-4-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-4-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ASSIGNMENT-0-4 ?VARIABLE0 ?NODE1 )
		( JMP-0-4-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-5-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ASSIGNMENT-0-5 ?VARIABLE0 ?NODE1 )
		( JMP-0-5-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-5-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ASSIGNMENT-0-5 ?VARIABLE0 ?NODE1 )
		( JMP-0-5-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-5-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ASSIGNMENT-0-5 ?VARIABLE0 ?NODE1 )
		( JMP-0-5-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-5-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ASSIGNMENT-0-5 ?VARIABLE0 ?NODE1 )
		( JMP-0-5-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ASSIGNMENT-5-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ASSIGNMENT-0-5 ?VARIABLE0 ?NODE1 )
		( JMP-0-5-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-0-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ISINTERNAL-0-0 ?VARIABLE0 )
		( JMP-0-0-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-0-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ISINTERNAL-0-0 ?VARIABLE0 )
		( JMP-0-0-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-0-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ISINTERNAL-0-0 ?VARIABLE0 )
		( JMP-0-0-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-0-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ISINTERNAL-0-0 ?VARIABLE0 )
		( JMP-0-0-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-0-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( COND-ISINTERNAL-0-0 ?VARIABLE0 )
		( JMP-0-0-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-1-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ISINTERNAL-0-1 ?VARIABLE0 )
		( JMP-0-1-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-1-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ISINTERNAL-0-1 ?VARIABLE0 )
		( JMP-0-1-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-1-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ISINTERNAL-0-1 ?VARIABLE0 )
		( JMP-0-1-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-1-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ISINTERNAL-0-1 ?VARIABLE0 )
		( JMP-0-1-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-1-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( COND-ISINTERNAL-0-1 ?VARIABLE0 )
		( JMP-0-1-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-2-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ISINTERNAL-0-2 ?VARIABLE0 )
		( JMP-0-2-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-2-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ISINTERNAL-0-2 ?VARIABLE0 )
		( JMP-0-2-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-2-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ISINTERNAL-0-2 ?VARIABLE0 )
		( JMP-0-2-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-2-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ISINTERNAL-0-2 ?VARIABLE0 )
		( JMP-0-2-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-2-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( COND-ISINTERNAL-0-2 ?VARIABLE0 )
		( JMP-0-2-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-3-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ISINTERNAL-0-3 ?VARIABLE0 )
		( JMP-0-3-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-3-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ISINTERNAL-0-3 ?VARIABLE0 )
		( JMP-0-3-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-3-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ISINTERNAL-0-3 ?VARIABLE0 )
		( JMP-0-3-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-3-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ISINTERNAL-0-3 ?VARIABLE0 )
		( JMP-0-3-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-3-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( COND-ISINTERNAL-0-3 ?VARIABLE0 )
		( JMP-0-3-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-4-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ISINTERNAL-0-4 ?VARIABLE0 )
		( JMP-0-4-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-4-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ISINTERNAL-0-4 ?VARIABLE0 )
		( JMP-0-4-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-4-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ISINTERNAL-0-4 ?VARIABLE0 )
		( JMP-0-4-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-4-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ISINTERNAL-0-4 ?VARIABLE0 )
		( JMP-0-4-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-4-6
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( COND-ISINTERNAL-0-4 ?VARIABLE0 )
		( JMP-0-4-6 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-5-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ISINTERNAL-0-5 ?VARIABLE0 )
		( JMP-0-5-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-5-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ISINTERNAL-0-5 ?VARIABLE0 )
		( JMP-0-5-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-5-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ISINTERNAL-0-5 ?VARIABLE0 )
		( JMP-0-5-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-5-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ISINTERNAL-0-5 ?VARIABLE0 )
		( JMP-0-5-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-JMP-ISINTERNAL-5-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( COND-ISINTERNAL-0-5 ?VARIABLE0 )
		( JMP-0-5-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION DO-JMP-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-2 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-3 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-4 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-5 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-0-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-6 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-3 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-4 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-1-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-5 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-1-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-6 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-1 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-2-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-4 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-2-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-5 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-2-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-6 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-3-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-3-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-1 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-3-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-2 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-3-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-5 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-3-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-6 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-4-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-4-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-1 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-4-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-2 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-4-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-3 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-4-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-6 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-5-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-5-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-1 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-5-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-2 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-5-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-3 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-JMP-0-5-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-4 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-VISITED-0-0
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-VISITED-0-0 ?NODE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( VISITED ?NODE0 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-0 ?VARIABLE0 ?NODE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?VARIABLE0 ?NODE1 ?STACKROW2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ISINTERNAL-0-0
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ISINTERNAL-0-0 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( ISINTERNAL ?VARIABLE0 ) )
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
					( INTERNAL ?NODE2 )
				)
				( AND
					( ACCUMULATOR )
					( ISINTERNAL ?VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-VISITED-0-1
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-VISITED-0-1 ?NODE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( VISITED ?NODE0 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-1 ?VARIABLE0 ?NODE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?VARIABLE0 ?NODE1 ?STACKROW2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ISINTERNAL-0-1
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ISINTERNAL-0-1 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( ISINTERNAL ?VARIABLE0 ) )
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
					( INTERNAL ?NODE2 )
				)
				( AND
					( ACCUMULATOR )
					( ISINTERNAL ?VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-VISITED-0-2
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-VISITED-0-2 ?NODE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( VISITED ?NODE0 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-2 ?VARIABLE0 ?NODE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?VARIABLE0 ?NODE1 ?STACKROW2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ISINTERNAL-0-2
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ISINTERNAL-0-2 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( ISINTERNAL ?VARIABLE0 ) )
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
					( INTERNAL ?NODE2 )
				)
				( AND
					( ACCUMULATOR )
					( ISINTERNAL ?VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-VISITED-0-3
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-VISITED-0-3 ?NODE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( VISITED ?NODE0 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-3 ?VARIABLE0 ?NODE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-3 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?VARIABLE0 ?NODE1 ?STACKROW2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ISINTERNAL-0-3
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ISINTERNAL-0-3 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( ISINTERNAL ?VARIABLE0 ) )
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
					( INTERNAL ?NODE2 )
				)
				( AND
					( ACCUMULATOR )
					( ISINTERNAL ?VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-VISITED-0-4
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-VISITED-0-4 ?NODE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( VISITED ?NODE0 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-4 ?VARIABLE0 ?NODE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-4 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?VARIABLE0 ?NODE1 ?STACKROW2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ISINTERNAL-0-4
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ISINTERNAL-0-4 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( ISINTERNAL ?VARIABLE0 ) )
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
					( INTERNAL ?NODE2 )
				)
				( AND
					( ACCUMULATOR )
					( ISINTERNAL ?VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-VISITED-0-5
  :PARAMETERS ( ?NODE0 - NODE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-VISITED-0-5 ?NODE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( VISITED ?NODE0 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?NODE1 - NODE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-5 ?VARIABLE0 ?NODE1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-5 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?VARIABLE0 ?NODE1 ?STACKROW2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ISINTERNAL-0-5
  :PARAMETERS ( ?VARIABLE0 - VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ISINTERNAL-0-5 ?VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( ISINTERNAL ?VARIABLE0 ) )
		( FORALL
			( ?NODE2 - NODE )
			( WHEN
				( AND
					( ASSIGNMENT ?VARIABLE0 ?NODE2 ?STACKROW1 )
					( INTERNAL ?NODE2 )
				)
				( AND
					( ACCUMULATOR )
					( ISINTERNAL ?VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-2 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-3 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-4 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-5 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-0-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-0-6 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-3 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-4 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-1-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-5 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-1-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-1-6 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-1 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-2-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-4 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-2-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-5 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-2-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-2-6 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-3-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-3-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-1 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-3-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-2 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-3-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-5 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-3-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-3-6 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-4-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-4-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-1 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-4-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-2 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-4-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-3 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-4-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-4-6 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-5-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-5-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-1 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-5-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-2 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-5-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-3 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-NOJMP-0-5-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( JMP-0-5-4 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( ACCUMULATOR ) )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-END-1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-END-2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-END-3 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-END-4 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-END-5 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-6 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-6 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-6 ) )
		( INS-END-6 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( TOP-STACK ROW0 )
		( VISITED N1 )
		( VISITED N2 )
		( VISITED N3 )
		( VISITED N4 )
		( VISITED N5 )
		( VISITED N6 )
		( VISITED N7 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( TOP-STACK ROW0 )
		( VISITED N1 )
		( VISITED N2 )
		( VISITED N3 )
		( VISITED N4 )
		( VISITED N5 )
		( VISITED N6 )
		( VISITED N7 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-3-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( TOP-STACK ROW0 )
		( VISITED N1 )
		( VISITED N2 )
		( VISITED N3 )
		( VISITED N4 )
		( VISITED N5 )
		( VISITED N6 )
		( VISITED N7 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-4-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-4 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
		( TOP-STACK ROW0 )
		( VISITED N1 )
		( VISITED N2 )
		( VISITED N3 )
		( VISITED N4 )
		( VISITED N5 )
		( VISITED N6 )
		( VISITED N7 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-5-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-5 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
		( TOP-STACK ROW0 )
		( VISITED N1 )
		( VISITED N2 )
		( VISITED N3 )
		( VISITED N4 )
		( VISITED N5 )
		( VISITED N6 )
		( VISITED N7 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-6-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-6 )
		( TEST-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-6 ?STACKROW0 )
		( TOP-STACK ROW0 )
		( VISITED N1 )
		( VISITED N2 )
		( VISITED N3 )
		( VISITED N4 )
		( VISITED N5 )
		( VISITED N6 )
		( VISITED N7 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( FORALL ( ?VARIABLE2 - VARIABLE ?NODE3 - NODE )
			( AND ( NOT ( ASSIGNMENT ?VARIABLE2 ?NODE3 ?STACKROW1 ) ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( FORALL ( ?VARIABLE2 - VARIABLE ?NODE3 - NODE )
			( AND ( NOT ( ASSIGNMENT ?VARIABLE2 ?NODE3 ?STACKROW1 ) ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-3-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( FORALL ( ?VARIABLE2 - VARIABLE ?NODE3 - NODE )
			( AND ( NOT ( ASSIGNMENT ?VARIABLE2 ?NODE3 ?STACKROW1 ) ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-4-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-4 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-4 ?STACKROW1 ) )
		( FORALL ( ?VARIABLE2 - VARIABLE ?NODE3 - NODE )
			( AND ( NOT ( ASSIGNMENT ?VARIABLE2 ?NODE3 ?STACKROW1 ) ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-5-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-5 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-5 ?STACKROW1 ) )
		( FORALL ( ?VARIABLE2 - VARIABLE ?NODE3 - NODE )
			( AND ( NOT ( ASSIGNMENT ?VARIABLE2 ?NODE3 ?STACKROW1 ) ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-6-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-6 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-6 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-6 ?STACKROW1 ) )
		( FORALL ( ?VARIABLE2 - VARIABLE ?NODE3 - NODE )
			( AND ( NOT ( ASSIGNMENT ?VARIABLE2 ?NODE3 ?STACKROW1 ) ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-CALL-0-0-0
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( CALL-0-0-0 ?VARIABLE2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-1
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( CALL-0-0-1 ?VARIABLE2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-2
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( CALL-0-0-2 ?VARIABLE2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-3
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( CALL-0-0-3 ?VARIABLE2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-4
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( CALL-0-0-4 ?VARIABLE2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-5
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( CALL-0-0-5 ?VARIABLE2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION REPEAT-CALL-0-0-0
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-0 ?VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( FORALL (?NODE - NODE)
			( WHEN ( ASSIGNMENT ?VARIABLE2 ?NODE ?STACKROW0 ) ( ASSIGNMENT CURRENT ?NODE ?STACKROW1 ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-1
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-1 ?VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( FORALL (?NODE - NODE)
			( WHEN ( ASSIGNMENT ?VARIABLE2 ?NODE ?STACKROW0 ) ( ASSIGNMENT CURRENT ?NODE ?STACKROW1 ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-2
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-2 ?VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( FORALL (?NODE - NODE)
			( WHEN ( ASSIGNMENT ?VARIABLE2 ?NODE ?STACKROW0 ) ( ASSIGNMENT CURRENT ?NODE ?STACKROW1 ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-3
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-3 ?VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( FORALL (?NODE - NODE)
			( WHEN ( ASSIGNMENT ?VARIABLE2 ?NODE ?STACKROW0 ) ( ASSIGNMENT CURRENT ?NODE ?STACKROW1 ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-4
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-4 ?VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( FORALL (?NODE - NODE)
			( WHEN ( ASSIGNMENT ?VARIABLE2 ?NODE ?STACKROW0 ) ( ASSIGNMENT CURRENT ?NODE ?STACKROW1 ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-5
  :PARAMETERS ( ?VARIABLE2 - VARIABLE ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-5 ?VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( FORALL (?NODE - NODE)
			( WHEN ( ASSIGNMENT ?VARIABLE2 ?NODE ?STACKROW0 ) ( ASSIGNMENT CURRENT ?NODE ?STACKROW1 ) )
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
)
