(define (problem p10d)
  (:domain trees_alt )
  (:objects 
	 current childs - variable
	 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 - node )
	
  (:init
	( assignment current n9 )
	( internal n9 )
	( right-child n6 n9 )
	( internal n6 )
	( right-child n3 n6 )
	( internal n3 )
	( right-child n4 n3 )
	( left-child n8 n3 )
	( internal n8 )
	( right-child n10 n8 )
	( internal n10 )
	( right-child n1 n10 )
	( internal n1 )
	( left-child n5 n1 )
	( left-child n2 n6 )
	( left-child n7 n9 ) )
  (:goal
	( and 
	( visited n9 )
	( visited n6 )
	( visited n3 )
	( visited n4 )
	( visited n8 )
	( visited n10 )
	( visited n1 )
	( visited n5 )
	( visited n2 )
	( visited n7 )
	)
  )
)