(define (problem p5x4)
  (:domain 1corner)
  (:objects v0 v1 v2 v3 v4 - value )
  (:init 
	(xpos v0)(ypos v0)
	(xmin v0)(ymin v0)
	(xmax v4)(ymax v1) 
	(consec v0 v1)
	(consec v1 v2)
	(consec v2 v3)
	(consec v3 v4))
  (:goal (and  (visited v4 v1) )))
