(define (problem p1-3-neg)
  (:domain list)
  (:objects n1 n2 n3 nlast - node )
  (:init  (at n1) (adjacent n1 n3) (adjacent n3 n2)(adjacent n2 nlast) 
			(not-visited n1)(not-visited n2)(not-visited n3)(not-visited nlast)
	)
  (:goal (and (visited n1) (visited n3) (not-visited n2) ))
)
