(define (problem p1-3)
  (:domain list)
  (:objects n1 n2 n3 nlast - node )
  (:init  (at n1) (adjacent n1 n2) (adjacent n2 n3)(adjacent n3 nlast) 
			(not-visited n1)(not-visited n2)(not-visited n3)(not-visited nlast)
	)
  (:goal (and (visited n1) (visited n2) (visited n3) ))
)
