(define (problem neg2)
  (:domain regularExpressions)
  (:objects i0 i1 i2 i3 i4 i5 - index )
  (:init  
	(at i0)
	(current-content a)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(adjacent i4 i5)
	(content i0 a)
	(content i1 b)
	(content i2 a)
	(content i3 b)
	(content i4 a)
	(content i5 empty)
  )
  (:goal (and 
	(at i4)
  ))
)
