(define (problem p4d)
  (:domain reverse)
  (:objects v0 v1 v2 v3 - value i0 i1 i2 i3 - index )
  (:init 
		(consec i0 i1)
		(consec i1 i2)
		(consec i2 i3)
		(greatereq-than i1 i0)
		(greatereq-than i3 i0)
		(greatereq-than i1 i1)
		(greatereq-than i3 i1)
		(greatereq-than i3 i2)
		(greatereq-than i3 i3)
		(greatereq-than i2 i2)
		(greatereq-than i2 i1)
		(greatereq-than i0 i0)
		(greatereq-than i2 i0) 
		(assignment i0 v1) (assignment i1 v0) (assignment i2 v2) (assignment i3 v3)
		(iterator1 i0) (iterator2 i3) 
		(i1val v1)(i2val v3) )
  (:goal (and  (assignment i0 v3) (assignment i1 v2) (assignment i2 v0) (assignment i3 v1))))
