(define (problem p-neg-1m)
  (:domain variables)
  (:objects v2 - value)
  (:init (assignment a v2) (assignment b v1) (assignment c v0) (assignment d v1)
	(sum v0 v0 v0)
	(sum v0 v1 v1)
	(sum v0 v2 v2)
	(sum v1 v0 v1)
	(sum v1 v1 v2)
	(sum v2 v0 v2))
  (:goal (and  (assignment a v2) (assignment b v1) (assignment c v0) (assignment d v1))))
