(define (problem prob5x1)
	(:domain visitall)
	(:objects vmin v0 v1 v2 v3 v4 v5 - value )
	(:init
		(xpos v0)
		(ypos v0)
		(xmin vmin)
		(ymin vmin)
		(xmax v5)
		(ymax v1)
		(consec vmin v0)
		(consec v0 v1)
		(consec v1 v2)
		(consec v2 v3)
		(consec v3 v4)
		(consec v4 v5)
	)
	(:goal (and
		(visited v0 v0)
		(visited v1 v0)
		(visited v2 v0)
		(visited v3 v0)
		(visited v4 v0)
		(xpos v4)(ypos v0)
	))
)
