(define (problem prob3x1b)
	(:domain visitall)
	;(:objects vmin v0 v1 v2 v3 - value )
	(:objects v0 v1 v2 v3 - value )
	(:init
		(xpos v2)
		(ypos v0)
		;(xmin vmin)
		;(ymin vmin)
		(xmax v3)
		(ymax v1)
		;(consec vmin v0)
		(consec v0 v1)
		(consec v1 v2)
		(consec v2 v3)
	)
	(:goal (and
		(xpos v0)		
		;(ypos v0)
	))
)
