(define (problem prob4x4)
	(:domain visitall)
	(:objects vmin v0 v1 v2 v3 v4 - value )
	(:init
		(xpos v0)
		(ypos v0)
		(xmin vmin)
		(ymin vmin)
		(xmax v4)
		(ymax v4)
		(consec vmin v0)
		(consec v0 v1)
		(consec v1 v2)
		(consec v2 v3)
		(consec v3 v4)
	)
	(:goal (and
		(visited v0 v0)
		(visited v1 v0)
		(visited v2 v0)
		(visited v3 v0)
		(visited v0 v1)
		(visited v1 v1)
		(visited v2 v1)
		(visited v3 v1)
		(visited v0 v2)
		(visited v1 v2)
		(visited v2 v2)
		(visited v3 v2)
		(visited v0 v3)
		(visited v1 v3)
		(visited v2 v3)
		(visited v3 v3)
		
	))
)
