(define (problem ab-regex-5)
  (:domain regularExpressions)
  (:objects i0 i1 i2 i3 i4 i5 - index)
  (:init (at i0)(current-content a)(adjacent i0 i1)(content i0 a)(adjacent i1 i2)(content i1 b)(adjacent i2 i3)(content i2 a)(adjacent i3 i4)(content i3 b)(adjacent i4 i5)(content i4 a)(content i5 empty ) )
  (:goal (and  (at i5) )))
