(define (problem visualm3x6)
	(:domain programming)
	(:objects
		; block not really necessary!
		block empty green next - relation
		v0 v1 v2 v3 v4 v5 v6 - value
		x y xm ym - variable
	)
	(:init 
		(assignment x v0)
		(assignment y v0)
		(assignment xm v3)
		(assignment ym v6)
		(ordinal-2ary next)
		(conditional-2ary block)
		(conditional-2ary green)
		(conditional-2ary empty)
		(includes-2ary next v0 v1)
		(includes-2ary next v1 v2)
		(includes-2ary next v2 v3)
		(includes-2ary next v3 v4)
		(includes-2ary next v4 v5)
		(includes-2ary next v5 v6)
		(includes-2ary block v0 v0)
		(includes-2ary block v0 v1)
		(includes-2ary empty v0 v2)
		(includes-2ary empty v0 v3)
		(includes-2ary empty v0 v4)
		(includes-2ary empty v0 v5)
		(includes-2ary block v1 v0)
		(includes-2ary empty v1 v1)
		(includes-2ary empty v1 v2)
		(includes-2ary empty v1 v3)
		(includes-2ary empty v1 v4)
		(includes-2ary empty v1 v5)
		(includes-2ary block v2 v0)
		(includes-2ary block v2 v1)
		(includes-2ary block v2 v2)
		(includes-2ary block v2 v3)
		(includes-2ary block v2 v4)
		(includes-2ary green v2 v4)
		(includes-2ary empty v2 v5)
	)
	(:goal (and
		(assignment x v2)
		(assignment y v4)
	))
)
