(define (problem p4-23092015125622)
  (:domain htower)
  (:objects v0 v1 v2 v3  vNULL - value )
  (:init (consecA vNULL v0)(consecA v0 v1)(consecA v1 v2)(consecA v2 v3)(clearA v3)(clearB vNULL)(clearC vNULL)(greater-than vNULL v0)(greater-than vNULL v1)(greater-than v0 v1)(greater-than vNULL v2)(greater-than vNULL v3)(greater-than v0 v2)(greater-than v0 v3)(greater-than v1 v2)(greater-than v2 v3)(greater-than v1 v3)(handempty))
  (:goal (and (consecC vNULL v0)(consecC v0 v1)(consecC v1 v2)(consecC v2 v3))))
