(define (problem p2-23092015125750)
  (:domain htower)
  (:objects v0 v1  vNULL - value )
  (:init (consecA vNULL v0)(consecA v0 v1)(clearA v1)(clearB vNULL)(clearC vNULL)(greater-than v0 v1)(greater-than vNULL v0)(greater-than vNULL v1)(handempty))
  (:goal (and (consecC vNULL v0)(consecC v0 v1))))
