(define (problem p10-lifted)
  (:domain blocks)
  (:objects b1 b2 b3 b4 b5 b6 - value )
  (:init 
		(includes-1ary clear b6)
		(includes-2ary on b6 b5)
		(includes-2ary on b5 b4)
		(includes-2ary on b4 b3)
		(includes-2ary on b3 b2)
		(includes-2ary on b2 b1)
		(includes-1ary ontable b1)
		(handempty) 
		(includes-1ary green b6)
		;(includes-1ary green b3)
		;(includes-1ary green b1)
     
		(arity-1 ontable)
		(arity-1 clear)
		(arity-1 hold)
		(arity-1 green)
		(arity-1 have)
		(arity-1 havent)
		(arity-2 on)
  )
  (:goal (and 
		(includes-1ary have b6)
  ))
)
