(define (problem prob3x2)
	(:domain visitall)
	;(:objects vmin v0 v1 v2 v3 - value )
	(:objects v0 v1 v2 v3 - value )
	(:init
		(xpos v0)
		(ypos v0)
		;(xmin vmin)
		;(ymin vmin)
		(xmax v3)
		(ymax v2)
		;(consec vmin v0)
		(consec v0 v1)
		(consec v1 v2)
		(consec v2 v3)
	)
	(:goal (and
		(visited v0 v0)
		(visited v1 v0)
		(visited v2 v0)
		(visited v0 v1)
		(visited v1 v1)
		(visited v2 v1)
		
	))
)
