(define (problem prob5x1b)
	(:domain visitall)
	;(:objects vmin v0 v1 v2 v3 v4 v5 - value )
	(:objects vmin v0 v1 v2 v3 v4 v5 - value )
	(:init
		(xpos v4)
		(ypos v0)
		;(xmin vmin)
		;(ymin vmin)
		(xmax v5)
		(ymax v1)
		;(consec vmin v0)
		(consec v0 v1)
		(consec v1 v2)
		(consec v2 v3)
		(consec v3 v4)
		(consec v4 v5)
	)
	(:goal (and
		(xpos v0)
		;(ypos v0)
		
	))
)
