(define (problem prob4x1)
	(:domain visitall)
	(:objects v0 v1 v2 v3 v4 - value )
	(:init
		(xpos v0)
		(ypos v0)
		(xmax v4)
		(ymax v0)
		(consec v0 v1)
		(consec v1 v2)
		(consec v2 v3)
		(consec v3 v4)
	)
	(:goal (and
		(visited v0 v0)
		(visited v1 v0)
		(visited v2 v0)
		(visited v3 v0)
	))
)
