(define (problem p4x4d)
  (:domain sorting )
  (:objects 
	 i0 i1 i2 i3 - index
	 v0 v1 v2 v3 - value 
  )
  (:init
	( assignment i0 v3 )
	( assignment i1 v2 )
	( assignment i2 v1 )
	( assignment i3 v2 )
	( consec i0 i1 )
	( consec i1 i2 )
	( consec i2 i3 )
	( lessthan v0 v1 )
	( lessthan v0 v2 )
	( lessthan v0 v3 )
	( lessthan v1 v2 )
	( lessthan v1 v3 )
	( lessthan v2 v3 )
	( outeriter i0)
	( outerval v3)
	( iterator i0)
	( currentval v3)
	( itermax i3)
	( itermark i0)
	( valuemark v3) )
  (:goal
	( and 
	( assignment i0 v1 )
	( assignment i1 v2 )
	( assignment i2 v2 )
	( assignment i3 v3 )
	)
  )
)