./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-5-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-5-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-5-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-5-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-5-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-6-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-6-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-6-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-6-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-6-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-7-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-7-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-7-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-7-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-7-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-8-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-8-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-8-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-8-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-8-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-9-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-9-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-9-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-9-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-9-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-10-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-10-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-10-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-10-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-10-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-11-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-11-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-11-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-11-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-11-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-12-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-12-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-12-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-12-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-12-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-13-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-13-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-13-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-13-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-13-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-14-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-14-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-14-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-14-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-14-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-3-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-2-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-1-pos-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-1-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-2-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-2-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-3-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-3-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-1-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-4-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-4-neg-d.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-1-neg-b.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-2-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-4-neg-a.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-4-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-1-neg-c.pddl $1
./universal-planning-validator/validator/validate.bin -p domains/neg/ts/domain.pddl domains/neg/ts/ts-3-neg-c.pddl $1
