./scripts/neg/aaai20/list-val/list-NEGLITE-1-1-a-val.sh experiments/neg/aaai20/list/1.neglite.program > experiments/neg/aaai20/list/1.neglite.val 2> experiments/neg/aaai20/list/1.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-1-b-val.sh experiments/neg/aaai20/list/2.neglite.program > experiments/neg/aaai20/list/2.neglite.val 2> experiments/neg/aaai20/list/2.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-1-c-val.sh experiments/neg/aaai20/list/3.neglite.program > experiments/neg/aaai20/list/3.neglite.val 2> experiments/neg/aaai20/list/3.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-1-d-val.sh experiments/neg/aaai20/list/4.neglite.program > experiments/neg/aaai20/list/4.neglite.val 2> experiments/neg/aaai20/list/4.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-2-a-val.sh experiments/neg/aaai20/list/5.neglite.program > experiments/neg/aaai20/list/5.neglite.val 2> experiments/neg/aaai20/list/5.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-2-b-val.sh experiments/neg/aaai20/list/6.neglite.program > experiments/neg/aaai20/list/6.neglite.val 2> experiments/neg/aaai20/list/6.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-2-c-val.sh experiments/neg/aaai20/list/7.neglite.program > experiments/neg/aaai20/list/7.neglite.val 2> experiments/neg/aaai20/list/7.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-3-1-a-val.sh experiments/neg/aaai20/list/8.neglite.program > experiments/neg/aaai20/list/8.neglite.val 2> experiments/neg/aaai20/list/8.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-2-d-val.sh experiments/neg/aaai20/list/9.neglite.program > experiments/neg/aaai20/list/9.neglite.val 2> experiments/neg/aaai20/list/9.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-3-1-b-val.sh experiments/neg/aaai20/list/10.neglite.program > experiments/neg/aaai20/list/10.neglite.val 2> experiments/neg/aaai20/list/10.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-3-a-val.sh experiments/neg/aaai20/list/11.neglite.program > experiments/neg/aaai20/list/11.neglite.val 2> experiments/neg/aaai20/list/11.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-3-1-c-val.sh experiments/neg/aaai20/list/12.neglite.program > experiments/neg/aaai20/list/12.neglite.val 2> experiments/neg/aaai20/list/12.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-3-b-val.sh experiments/neg/aaai20/list/13.neglite.program > experiments/neg/aaai20/list/13.neglite.val 2> experiments/neg/aaai20/list/13.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-3-1-d-val.sh experiments/neg/aaai20/list/14.neglite.program > experiments/neg/aaai20/list/14.neglite.val 2> experiments/neg/aaai20/list/14.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-3-c-val.sh experiments/neg/aaai20/list/15.neglite.program > experiments/neg/aaai20/list/15.neglite.val 2> experiments/neg/aaai20/list/15.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-3-2-a-val.sh experiments/neg/aaai20/list/16.neglite.program > experiments/neg/aaai20/list/16.neglite.val 2> experiments/neg/aaai20/list/16.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-3-d-val.sh experiments/neg/aaai20/list/17.neglite.program > experiments/neg/aaai20/list/17.neglite.val 2> experiments/neg/aaai20/list/17.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-3-2-b-val.sh experiments/neg/aaai20/list/18.neglite.program > experiments/neg/aaai20/list/18.neglite.val 2> experiments/neg/aaai20/list/18.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-4-a-val.sh experiments/neg/aaai20/list/19.neglite.program > experiments/neg/aaai20/list/19.neglite.val 2> experiments/neg/aaai20/list/19.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-3-2-c-val.sh experiments/neg/aaai20/list/20.neglite.program > experiments/neg/aaai20/list/20.neglite.val 2> experiments/neg/aaai20/list/20.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-4-b-val.sh experiments/neg/aaai20/list/21.neglite.program > experiments/neg/aaai20/list/21.neglite.val 2> experiments/neg/aaai20/list/21.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-3-2-d-val.sh experiments/neg/aaai20/list/22.neglite.program > experiments/neg/aaai20/list/22.neglite.val 2> experiments/neg/aaai20/list/22.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-4-c-val.sh experiments/neg/aaai20/list/23.neglite.program > experiments/neg/aaai20/list/23.neglite.val 2> experiments/neg/aaai20/list/23.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-1-4-d-val.sh experiments/neg/aaai20/list/24.neglite.program > experiments/neg/aaai20/list/24.neglite.val 2> experiments/neg/aaai20/list/24.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-1-a-val.sh experiments/neg/aaai20/list/25.neglite.program > experiments/neg/aaai20/list/25.neglite.val 2> experiments/neg/aaai20/list/25.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-1-b-val.sh experiments/neg/aaai20/list/26.neglite.program > experiments/neg/aaai20/list/26.neglite.val 2> experiments/neg/aaai20/list/26.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-1-c-val.sh experiments/neg/aaai20/list/27.neglite.program > experiments/neg/aaai20/list/27.neglite.val 2> experiments/neg/aaai20/list/27.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-1-d-val.sh experiments/neg/aaai20/list/28.neglite.program > experiments/neg/aaai20/list/28.neglite.val 2> experiments/neg/aaai20/list/28.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-2-a-val.sh experiments/neg/aaai20/list/29.neglite.program > experiments/neg/aaai20/list/29.neglite.val 2> experiments/neg/aaai20/list/29.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-2-b-val.sh experiments/neg/aaai20/list/30.neglite.program > experiments/neg/aaai20/list/30.neglite.val 2> experiments/neg/aaai20/list/30.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-2-c-val.sh experiments/neg/aaai20/list/31.neglite.program > experiments/neg/aaai20/list/31.neglite.val 2> experiments/neg/aaai20/list/31.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-4-1-a-val.sh experiments/neg/aaai20/list/32.neglite.program > experiments/neg/aaai20/list/32.neglite.val 2> experiments/neg/aaai20/list/32.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-2-d-val.sh experiments/neg/aaai20/list/33.neglite.program > experiments/neg/aaai20/list/33.neglite.val 2> experiments/neg/aaai20/list/33.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-4-1-b-val.sh experiments/neg/aaai20/list/34.neglite.program > experiments/neg/aaai20/list/34.neglite.val 2> experiments/neg/aaai20/list/34.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-3-a-val.sh experiments/neg/aaai20/list/35.neglite.program > experiments/neg/aaai20/list/35.neglite.val 2> experiments/neg/aaai20/list/35.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-4-1-c-val.sh experiments/neg/aaai20/list/36.neglite.program > experiments/neg/aaai20/list/36.neglite.val 2> experiments/neg/aaai20/list/36.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-3-b-val.sh experiments/neg/aaai20/list/37.neglite.program > experiments/neg/aaai20/list/37.neglite.val 2> experiments/neg/aaai20/list/37.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-4-1-d-val.sh experiments/neg/aaai20/list/38.neglite.program > experiments/neg/aaai20/list/38.neglite.val 2> experiments/neg/aaai20/list/38.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-3-c-val.sh experiments/neg/aaai20/list/39.neglite.program > experiments/neg/aaai20/list/39.neglite.val 2> experiments/neg/aaai20/list/39.neglite.val.err
./scripts/neg/aaai20/list-val/list-NEGLITE-2-3-d-val.sh experiments/neg/aaai20/list/40.neglite.program > experiments/neg/aaai20/list/40.neglite.val 2> experiments/neg/aaai20/list/40.neglite.val.err

