(define (problem noun_phrase)
  (:domain SimpleGrammar)
  (:objects i0 i1 i2 i3 i4 i5 - index )
  (:init  
	(at i0)
	(current-content adjective)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(adjacent i4 i5)
	(content i0 adjective)
	(content i1 adjective)
	(content i2 adjective)
	(content i3 adjective)
	(content i4 singular-noun)
	(content i5 empty)
  )
  (:goal (and 
	(at i5)
  ))
)
