(define (problem sentence)
  (:domain SimpleGrammar)
  (:objects i0 i1 i2 i3 i4 i5 i6 i7 i8 - index )
  (:init  
	(at i0)
	(current-content adjective)
	(adjacent i0 i1)
	(adjacent i1 i2)
	(adjacent i2 i3)
	(adjacent i3 i4)
	(adjacent i4 i5)
	(adjacent i5 i6)
	(adjacent i6 i7)
	(adjacent i7 i8)
	(content i0 adjective)
	(content i1 adjective)
	(content i2 adjective)
	(content i3 adjective)
	(content i4 adjective)
	(content i5 singular-noun)
	(content i6 singular-verb)
	(content i7 adverb)
	(content i8 empty)
  )
  (:goal (and 
	(at i8)
  ))
)
