( DEFINE ( PROBLEM COPY01 )
( :DOMAIN EXCEL )
( :OBJECTS
	SPACE HYPH COLON DOT - LIMITER
	A B C D E F G H I J K L M N O P Q R S T U V W X Y Z N0 N1 N2 N3 N4 N5 N6 N7 N8 N9 LPAR RPAR - CHAR
	STR - INPUT
	RES - OUTPUT
	I2 I3 I4 I5 I6 - INDEX
	STR-VAR - INPUT-VARIABLE
)
( :INIT
	( ASSIGNMENT STR I0 LPAR )
	( ASSIGNMENT STR I1 A )
	( ASSIGNMENT STR I2 B )
	( ASSIGNMENT STR I3 C )
	( ASSIGNMENT STR I4 D )
	( LOINDEX STR I2 )
	( HIINDEX STR I4 )
	( SIZE STR I5 )
	( SIZE RES I0 )
	( NEXT I0 I1 )
	( NEXT I1 I2 )
	( NEXT I2 I3 )
	( NEXT I3 I4 )
	( NEXT I4 I5 )
	( NEXT I5 I6 )
	( INPUT-ASSIGNMENT STR-VAR STR )
)
( :GOAL
	( AND
		( ASSIGNMENT RES I0 B )
		( ASSIGNMENT RES I1 C )
	)
)
)
