( DEFINE ( DOMAIN SIMPLEGRAMMAR )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	INDEX - OBJECT
	TERMINAL-SYMBOL - OBJECT
	STACKROW - OBJECT
)
( :CONSTANTS
	I0 I1 I2 I3 I4 I5 - INDEX
	ADJECTIVE SINGULAR-NOUN SINGULAR-VERB ADVERB EMPTY - TERMINAL-SYMBOL
	ROW-0 ROW-1 ROW-2 ROW-3 ROW-4 ROW-5 ROW-6 ROW-7 ROW-8 ROW-9 - STACKROW
)
( :PREDICATES
	( AT ?INDEX0 - INDEX )
	( CURRENT-CONTENT ?TERMINAL-SYMBOL0 - TERMINAL-SYMBOL )
	( ADJACENT ?INDEX0 - INDEX ?INDEX1 - INDEX )
	( CONTENT ?INDEX0 - INDEX ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
	( EMPTY-STACK )
	( NEXT-STACK-ROW ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
	( TOP-STACK ?STACKROW0 - STACKROW )
	( ACCUMULATOR )
	( DONE-EVALUATING )
	( DONE-PROGRAMMING )
	( STACK-MAIN ?STACKROW0 - STACKROW )
	( STACK-LINE-0 ?STACKROW0 - STACKROW )
	( STACK-LINE-1 ?STACKROW0 - STACKROW )
	( STACK-LINE-2 ?STACKROW0 - STACKROW )
	( STACK-LINE-3 ?STACKROW0 - STACKROW )
	( STACK-LINE-4 ?STACKROW0 - STACKROW )
	( STACK-LINE-5 ?STACKROW0 - STACKROW )
	( STACK-LINE-6 ?STACKROW0 - STACKROW )
	( TEST-0 )
	( TEST-1 )
	( EMPTY-0 )
	( EMPTY-1 )
	( EMPTY-2 )
	( EMPTY-3 )
	( EMPTY-4 )
	( EMPTY-5 )
	( EMPTY-6 )
	( INS-END-1 )
	( INS-END-2 )
	( INS-END-3 )
	( INS-END-4 )
	( INS-END-5 )
	( INS-END-6 )
	( CALL-0-0-0 )
	( CALL-0-0-1 )
	( CALL-0-0-2 )
	( CALL-0-0-3 )
	( CALL-0-0-4 )
	( CALL-0-0-5 )
	( INS-PROCESS-ADJECTIVE-0 )
	( INS-PROCESS-ADJECTIVE-1 )
	( INS-PROCESS-ADJECTIVE-2 )
	( INS-PROCESS-ADJECTIVE-3 )
	( INS-PROCESS-ADJECTIVE-4 )
	( INS-PROCESS-ADJECTIVE-5 )
	( INS-PROCESS-SINGULAR-NOUN-0 )
	( INS-PROCESS-SINGULAR-NOUN-1 )
	( INS-PROCESS-SINGULAR-NOUN-2 )
	( INS-PROCESS-SINGULAR-NOUN-3 )
	( INS-PROCESS-SINGULAR-NOUN-4 )
	( INS-PROCESS-SINGULAR-NOUN-5 )
	( INS-PROCESS-SINGULAR-VERB-0 )
	( INS-PROCESS-SINGULAR-VERB-1 )
	( INS-PROCESS-SINGULAR-VERB-2 )
	( INS-PROCESS-SINGULAR-VERB-3 )
	( INS-PROCESS-SINGULAR-VERB-4 )
	( INS-PROCESS-SINGULAR-VERB-5 )
	( INS-PROCESS-ADVERB-0 )
	( INS-PROCESS-ADVERB-1 )
	( INS-PROCESS-ADVERB-2 )
	( INS-PROCESS-ADVERB-3 )
	( INS-PROCESS-ADVERB-4 )
	( INS-PROCESS-ADVERB-5 )
	( INS-SELECT-PROGRAM-0 )
	( ALLOWED-LINE-0-0 )
	( ALLOWED-LINE-0-1 )
	( ALLOWED-LINE-0-2 )
	( ALLOWED-LINE-0-3 )
	( ALLOWED-LINE-0-4 )
	( ALLOWED-LINE-0-5 )
	( ALLOWED-LINE-0-6 )
)
( :FUNCTIONS
	( TOTAL-COST )
)
( :ACTION PROGRAM-PROCESS-ADJECTIVE-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-PROCESS-ADJECTIVE-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADJECTIVE-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-PROCESS-ADJECTIVE-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADJECTIVE-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-PROCESS-ADJECTIVE-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADJECTIVE-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-PROCESS-ADJECTIVE-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADJECTIVE-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( EMPTY-4 )
		( STACK-LINE-4 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-PROCESS-ADJECTIVE-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADJECTIVE-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( EMPTY-5 )
		( STACK-LINE-5 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-PROCESS-ADJECTIVE-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-NOUN-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-PROCESS-SINGULAR-NOUN-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-NOUN-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-PROCESS-SINGULAR-NOUN-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-NOUN-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-PROCESS-SINGULAR-NOUN-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-NOUN-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-PROCESS-SINGULAR-NOUN-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-NOUN-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( EMPTY-4 )
		( STACK-LINE-4 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-PROCESS-SINGULAR-NOUN-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-NOUN-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( EMPTY-5 )
		( STACK-LINE-5 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-PROCESS-SINGULAR-NOUN-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-VERB-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-PROCESS-SINGULAR-VERB-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-VERB-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-PROCESS-SINGULAR-VERB-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-VERB-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-PROCESS-SINGULAR-VERB-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-VERB-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-PROCESS-SINGULAR-VERB-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-VERB-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( EMPTY-4 )
		( STACK-LINE-4 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-PROCESS-SINGULAR-VERB-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-SINGULAR-VERB-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( EMPTY-5 )
		( STACK-LINE-5 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-PROCESS-SINGULAR-VERB-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADVERB-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-PROCESS-ADVERB-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADVERB-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-PROCESS-ADVERB-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADVERB-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-PROCESS-ADVERB-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADVERB-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-PROCESS-ADVERB-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADVERB-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( EMPTY-4 )
		( STACK-LINE-4 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-PROCESS-ADVERB-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-PROCESS-ADVERB-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( EMPTY-5 )
		( STACK-LINE-5 ?STACKROW0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-PROCESS-ADVERB-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-END-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-END-1 )
		( ALLOWED-LINE-0-2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-END-2 )
		( ALLOWED-LINE-0-3 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-END-3 )
		( ALLOWED-LINE-0-4 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-4 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( INS-END-4 )
		( ALLOWED-LINE-0-5 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-5 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( INS-END-5 )
		( ALLOWED-LINE-0-6 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-6 )
		( STACK-LINE-6 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-6 ) )
		( INS-END-6 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-CALL-0-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( CALL-0-0-0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( CALL-0-0-1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( CALL-0-0-2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-3 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( CALL-0-0-3 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-4 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-4 ) )
		( CALL-0-0-4 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-5 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-5 ) )
		( CALL-0-0-5 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION REPEAT-PROCESS-ADJECTIVE-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-PROCESS-ADJECTIVE-0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADJECTIVE ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADJECTIVE-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( INS-PROCESS-ADJECTIVE-1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADJECTIVE ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADJECTIVE-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( INS-PROCESS-ADJECTIVE-2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADJECTIVE ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADJECTIVE-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( INS-PROCESS-ADJECTIVE-3 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADJECTIVE ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADJECTIVE-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
		( INS-PROCESS-ADJECTIVE-4 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADJECTIVE ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADJECTIVE-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADJECTIVE )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
		( INS-PROCESS-ADJECTIVE-5 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADJECTIVE ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-NOUN-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-NOUN-0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-NOUN ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-NOUN-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-NOUN-1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-NOUN ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-NOUN-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-NOUN-2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-NOUN ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-NOUN-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-NOUN-3 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-NOUN ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-NOUN-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-NOUN-4 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-NOUN ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-NOUN-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-NOUN )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-NOUN-5 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-NOUN ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-VERB-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-VERB-0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-VERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-VERB-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-VERB-1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-VERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-VERB-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-VERB-2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-VERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-VERB-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-VERB-3 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-VERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-VERB-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-VERB-4 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-VERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-SINGULAR-VERB-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT SINGULAR-VERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
		( INS-PROCESS-SINGULAR-VERB-5 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT SINGULAR-VERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADVERB-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-PROCESS-ADVERB-0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADVERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADVERB-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
		( INS-PROCESS-ADVERB-1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADVERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADVERB-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
		( INS-PROCESS-ADVERB-2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADVERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADVERB-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
		( INS-PROCESS-ADVERB-3 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADVERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADVERB-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
		( INS-PROCESS-ADVERB-4 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADVERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-PROCESS-ADVERB-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADVERB )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
		( INS-PROCESS-ADVERB-5 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX ?TERMINAL-SYMBOL3 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
					( AT ?INDEX1 )
					( CONTENT ?INDEX2 ?TERMINAL-SYMBOL3 )
				)
				( AND
					( NOT ( AT ?INDEX1 ) )
					( AT ?INDEX2 )
					( NOT ( CURRENT-CONTENT ADVERB ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL3 )
				)
			)
		)
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-1 ROW-0 )
		( INS-END-1 )
		( TEST-0 )
		( AT I2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( AT I0 )
		( CURRENT-CONTENT ADJECTIVE )
		( ADJACENT I0 I1 )
		( ADJACENT I1 I2 )
		( ADJACENT I2 I3 )
		( ADJACENT I3 I4 )
		( ADJACENT I4 I5 )
		( CONTENT I0 ADJECTIVE )
		( CONTENT I1 ADJECTIVE )
		( CONTENT I2 ADJECTIVE )
		( CONTENT I3 ADJECTIVE )
		( CONTENT I4 SINGULAR-NOUN )
		( CONTENT I5 EMPTY )
		( FORALL
			( ?INDEX1 - INDEX )
			( WHEN
				( AND
					( AT ?INDEX1 )
				)
				( NOT ( AT ?INDEX1 ) )
			)
		)
		( FORALL
			( ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CURRENT-CONTENT ?TERMINAL-SYMBOL1 )
				)
				( NOT ( CURRENT-CONTENT ?TERMINAL-SYMBOL1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
				)
				( NOT ( ADJACENT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( NOT ( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-2 ROW-0 )
		( INS-END-2 )
		( TEST-0 )
		( AT I2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( AT I0 )
		( CURRENT-CONTENT ADJECTIVE )
		( ADJACENT I0 I1 )
		( ADJACENT I1 I2 )
		( ADJACENT I2 I3 )
		( ADJACENT I3 I4 )
		( ADJACENT I4 I5 )
		( CONTENT I0 ADJECTIVE )
		( CONTENT I1 ADJECTIVE )
		( CONTENT I2 ADJECTIVE )
		( CONTENT I3 ADJECTIVE )
		( CONTENT I4 SINGULAR-NOUN )
		( CONTENT I5 EMPTY )
		( FORALL
			( ?INDEX1 - INDEX )
			( WHEN
				( AND
					( AT ?INDEX1 )
				)
				( NOT ( AT ?INDEX1 ) )
			)
		)
		( FORALL
			( ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CURRENT-CONTENT ?TERMINAL-SYMBOL1 )
				)
				( NOT ( CURRENT-CONTENT ?TERMINAL-SYMBOL1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
				)
				( NOT ( ADJACENT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( NOT ( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-3 ROW-0 )
		( INS-END-3 )
		( TEST-0 )
		( AT I2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( AT I0 )
		( CURRENT-CONTENT ADJECTIVE )
		( ADJACENT I0 I1 )
		( ADJACENT I1 I2 )
		( ADJACENT I2 I3 )
		( ADJACENT I3 I4 )
		( ADJACENT I4 I5 )
		( CONTENT I0 ADJECTIVE )
		( CONTENT I1 ADJECTIVE )
		( CONTENT I2 ADJECTIVE )
		( CONTENT I3 ADJECTIVE )
		( CONTENT I4 SINGULAR-NOUN )
		( CONTENT I5 EMPTY )
		( FORALL
			( ?INDEX1 - INDEX )
			( WHEN
				( AND
					( AT ?INDEX1 )
				)
				( NOT ( AT ?INDEX1 ) )
			)
		)
		( FORALL
			( ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CURRENT-CONTENT ?TERMINAL-SYMBOL1 )
				)
				( NOT ( CURRENT-CONTENT ?TERMINAL-SYMBOL1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
				)
				( NOT ( ADJACENT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( NOT ( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-4 ROW-0 )
		( INS-END-4 )
		( TEST-0 )
		( AT I2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( AT I0 )
		( CURRENT-CONTENT ADJECTIVE )
		( ADJACENT I0 I1 )
		( ADJACENT I1 I2 )
		( ADJACENT I2 I3 )
		( ADJACENT I3 I4 )
		( ADJACENT I4 I5 )
		( CONTENT I0 ADJECTIVE )
		( CONTENT I1 ADJECTIVE )
		( CONTENT I2 ADJECTIVE )
		( CONTENT I3 ADJECTIVE )
		( CONTENT I4 SINGULAR-NOUN )
		( CONTENT I5 EMPTY )
		( FORALL
			( ?INDEX1 - INDEX )
			( WHEN
				( AND
					( AT ?INDEX1 )
				)
				( NOT ( AT ?INDEX1 ) )
			)
		)
		( FORALL
			( ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CURRENT-CONTENT ?TERMINAL-SYMBOL1 )
				)
				( NOT ( CURRENT-CONTENT ?TERMINAL-SYMBOL1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
				)
				( NOT ( ADJACENT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( NOT ( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-5 ROW-0 )
		( INS-END-5 )
		( TEST-0 )
		( AT I2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( AT I0 )
		( CURRENT-CONTENT ADJECTIVE )
		( ADJACENT I0 I1 )
		( ADJACENT I1 I2 )
		( ADJACENT I2 I3 )
		( ADJACENT I3 I4 )
		( ADJACENT I4 I5 )
		( CONTENT I0 ADJECTIVE )
		( CONTENT I1 ADJECTIVE )
		( CONTENT I2 ADJECTIVE )
		( CONTENT I3 ADJECTIVE )
		( CONTENT I4 SINGULAR-NOUN )
		( CONTENT I5 EMPTY )
		( FORALL
			( ?INDEX1 - INDEX )
			( WHEN
				( AND
					( AT ?INDEX1 )
				)
				( NOT ( AT ?INDEX1 ) )
			)
		)
		( FORALL
			( ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CURRENT-CONTENT ?TERMINAL-SYMBOL1 )
				)
				( NOT ( CURRENT-CONTENT ?TERMINAL-SYMBOL1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
				)
				( NOT ( ADJACENT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( NOT ( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-6 ROW-0 )
		( INS-END-6 )
		( TEST-0 )
		( AT I2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-6 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( AT I0 )
		( CURRENT-CONTENT ADJECTIVE )
		( ADJACENT I0 I1 )
		( ADJACENT I1 I2 )
		( ADJACENT I2 I3 )
		( ADJACENT I3 I4 )
		( ADJACENT I4 I5 )
		( CONTENT I0 ADJECTIVE )
		( CONTENT I1 ADJECTIVE )
		( CONTENT I2 ADJECTIVE )
		( CONTENT I3 ADJECTIVE )
		( CONTENT I4 SINGULAR-NOUN )
		( CONTENT I5 EMPTY )
		( FORALL
			( ?INDEX1 - INDEX )
			( WHEN
				( AND
					( AT ?INDEX1 )
				)
				( NOT ( AT ?INDEX1 ) )
			)
		)
		( FORALL
			( ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CURRENT-CONTENT ?TERMINAL-SYMBOL1 )
				)
				( NOT ( CURRENT-CONTENT ?TERMINAL-SYMBOL1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( ADJACENT ?INDEX1 ?INDEX2 )
				)
				( NOT ( ADJACENT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( NOT ( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-1 ROW-0 )
		( INS-END-1 )
		( TEST-1 )
		( AT I5 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-1-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-2 ROW-0 )
		( INS-END-2 )
		( TEST-1 )
		( AT I5 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-3 ROW-0 )
		( INS-END-3 )
		( TEST-1 )
		( AT I5 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-4 ROW-0 )
		( INS-END-4 )
		( TEST-1 )
		( AT I5 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-1-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-5 ROW-0 )
		( INS-END-5 )
		( TEST-1 )
		( AT I5 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-1-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-6 ROW-0 )
		( INS-END-6 )
		( TEST-1 )
		( AT I5 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-4 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-4 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-5 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-5 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-6
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-6 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-6 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-6 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-4
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-4 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-4 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-4 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-5
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-5 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-5 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-5 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-6
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-6 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-6 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-6 ?STACKROW1 ) )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-3 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-4 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-4 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-4 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CALL-0-0-5 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-5 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-5 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION SELECT-PROGRAM-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-SELECT-PROGRAM-0 )
		( ALLOWED-LINE-0-1 )
	)
  :EFFECT
	( AND
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
	)
)
( :ACTION SELECT-PROGRAM-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-SELECT-PROGRAM-0 )
		( ALLOWED-LINE-0-2 )
	)
  :EFFECT
	( AND
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
	)
)
( :ACTION SELECT-PROGRAM-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-SELECT-PROGRAM-0 )
		( ALLOWED-LINE-0-3 )
	)
  :EFFECT
	( AND
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
	)
)
( :ACTION SELECT-PROGRAM-0-4
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-SELECT-PROGRAM-0 )
		( ALLOWED-LINE-0-4 )
	)
  :EFFECT
	( AND
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-4 ?STACKROW0 )
	)
)
( :ACTION SELECT-PROGRAM-0-5
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-SELECT-PROGRAM-0 )
		( ALLOWED-LINE-0-5 )
	)
  :EFFECT
	( AND
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-5 ?STACKROW0 )
	)
)
( :ACTION SELECT-PROGRAM-0-6
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
		( INS-SELECT-PROGRAM-0 )
		( ALLOWED-LINE-0-6 )
	)
  :EFFECT
	( AND
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-6 ?STACKROW0 )
	)
)
)
