(define (problem p3x4b)
  (:domain visual-marker )
  (:objects  v0 v1 v2 v3 v4 - value 
  )
  (:init
	( consec v0 v1)
	( consec v1 v2)
	( consec v2 v3)
	( consec v3 v4)
	(xpos v0)(ypos v0)(xmax v3)(ymax v4)
	(green v0 v0 )
	(block v0 v0 )
	(block v0 v1 )
	(block v0 v2 )
	(block v0 v3 )
	(block v0 v4 )
	(block v1 v0 )
	(block v1 v1 )
	(block v3 v0 )
	(block v3 v1 )
	(block v3 v2 )
	(block v3 v3 ) )
  (:goal
	( and ( marked )
	)
  )
)