(define (problem p4x3b)
  (:domain visual-marker )
  (:objects  v0 v1 v2 v3 v4 - value 
  )
  (:init
	( consec v0 v1)
	( consec v1 v2)
	( consec v2 v3)
	( consec v3 v4)
	(xpos v0)(ypos v0)(xmax v4)(ymax v3)
	(green v3 v2 )
	(block v0 v0 )
	(block v0 v1 )
	(block v0 v2 )
	(block v2 v0 )
	(block v2 v1 )
	(block v2 v2 )
	(block v2 v3 )
	(block v3 v0 )
	(block v3 v1 )
	(block v3 v2 )
	(block v3 v3 ) )
  (:goal
	( and ( marked )
	)
  )
)