(define (domain blocks)
  (:requirements :typing)
  (:types block)
  (:predicates (on ?x ?y - block)
               (ontable ?x - block)
               (clear ?x - block)
               (hold ?x - block)
               (green ?x - block)
               (have ?x - block)
               (empty)(finished)
               (obs-greenish))

  (:action unstack
    :parameters ()
    :precondition ()
    :effect (forall (?x ?y - block)
        (and (when (and (not (finished)) (clear ?x) (on ?x ?y) (empty))
               (and (hold ?x) (clear ?y) (not (clear ?x))
                    (not (on ?x ?y)) (not (empty)))
             )
             (when (and (not (finished)) (clear ?x) (ontable ?x) (empty))
               (and (hold ?x) (not (clear ?x))
                    (not (ontable ?x)) (not (empty)))
             )
        )
      )
  )

  (:action drop
    :parameters ()
    :precondition ()
    :effect (forall (?x - block)
        (when (and (not (finished)) (hold ?x))
          (and (empty) (not (hold ?x))))
      )
  )
  (:action collect
    :parameters ()
    :precondition ()
    :effect (forall (?x - block)
        (when (and (not (finished)) (hold ?x))
          (and (have ?x) (empty) (finished) (not (hold ?x))))
      )
  )

  (:derived (obs-greenish)
    (exists (?x - block) (and (clear ?x) (green ?x))))

)

