(define (problem fibo1-neg-a)
  (:domain variables)
  (:objects - value)
  (:init (assignment a v0) (assignment b v1) (assignment c v1) (assignment d v0) (sum v0 v0 v0))
  (:goal (and  (assignment a v0) (assignment b v0) (assignment c v1) (assignment d v1))))
