(define (problem fibo3-neg-b)
  (:domain variables)
  (:objects v2 v3 - value)
  (:init (assignment a v2) (assignment b v0) (assignment c v1) (assignment d v2) (sum v0 v0 v0))
  (:goal (and  (assignment a v0) (assignment b v1) (assignment c v3) (assignment d v0))))
