(define (problem fibo4-neg-c)
  (:domain variables)
  (:objects v2 v3 v4 v5 - value)
  (:init (assignment a v5) (assignment b v4) (assignment c v1) (assignment d v1) (sum v0 v0 v0)(sum v0 v1 v1)(sum v1 v0 v1))
  (:goal (and  (assignment a v1) (assignment b v1) (assignment c v1) (assignment d v1))))
