(define (problem fibo1-neg-c)
  (:domain variables)
  (:objects - value)
  (:init (assignment a v0) (assignment b v0) (assignment c v1) (assignment d v1) (sum v0 v0 v0))
  (:goal (and  (assignment a v0) (assignment b v0) (assignment c v0) (assignment d v0))))
