# Training Set
./gen.py 1 False a
./gen.py 1 False b
./gen.py 1 False c
./gen.py 1 False d
./gen.py 2 False a
./gen.py 2 False b
./gen.py 2 False c
./gen.py 2 False d
./gen.py 3 False a
./gen.py 3 False b
./gen.py 3 False c
./gen.py 3 False d
./gen.py 4 False a
./gen.py 4 False b
./gen.py 4 False c
./gen.py 4 False d
./gen.py 5 False a
./gen.py 5 False b
./gen.py 5 False c
./gen.py 5 False d
./gen.py 6 False a
./gen.py 6 False b
./gen.py 6 False c
./gen.py 6 False d
./gen.py 7 False a
./gen.py 7 False b
./gen.py 7 False c
./gen.py 7 False d
./gen.py 8 False a
./gen.py 8 False b
./gen.py 8 False c
./gen.py 8 False d
./gen.py 9 False a
./gen.py 9 False b
./gen.py 9 False c
./gen.py 9 False d
./gen.py 10 False a
./gen.py 10 False b
./gen.py 10 False c
./gen.py 10 False d
./gen.py 11 False a
./gen.py 11 False b
./gen.py 11 False c
./gen.py 11 False d
./gen.py 12 False a
./gen.py 12 False b
./gen.py 12 False c
./gen.py 12 False d
./gen.py 13 False a
./gen.py 13 False b
./gen.py 13 False c
./gen.py 13 False d
./gen.py 1 True a
./gen.py 2 True a
./gen.py 3 True a
./gen.py 4 True a
./gen.py 5 True a
./gen.py 6 True a
./gen.py 7 True a
./gen.py 8 True a
./gen.py 9 True a
./gen.py 10 True a
./gen.py 11 True a
./gen.py 12 True a
./gen.py 13 True a
