(define (problem p3x3b)
  (:domain variables-output )
  (:objects  v0 v1 v2 - value 
  )
  (:init
	( next v0 v1)
	( next v1 v2)
	( not-output-two v0 v0)
	( not-output-two v0 v1)
	( not-output-two v0 v2)
	( not-output-two v1 v0)
	( not-output-two v1 v1)
	( not-output-two v1 v2)
	( not-output-two v2 v0)
	( not-output-two v2 v1)
	( not-output-two v2 v2)
	( assignment a v2)
	( assignment b v0)
	( assignment c v2)
	( assignment d v2) )
  (:goal
	( and
	( output-two v0 v0 )
	( not-output-two v0 v1)
	( output-two v0 v2 )
	( not-output-two v1 v0)
	( not-output-two v1 v1)
	( not-output-two v1 v2)
	( output-two v2 v0 )
	( not-output-two v2 v1)
	( output-two v2 v2 )
	)
  )
)