(define (problem p7x7b)
  (:domain variables-output )
  (:objects  v0 v1 v2 v3 v4 v5 v6 - value 
  )
  (:init
	( next v0 v1)
	( next v1 v2)
	( next v2 v3)
	( next v3 v4)
	( next v4 v5)
	( next v5 v6)
	( not-output-two v0 v0)
	( not-output-two v0 v1)
	( not-output-two v0 v2)
	( not-output-two v0 v3)
	( not-output-two v0 v4)
	( not-output-two v0 v5)
	( not-output-two v0 v6)
	( not-output-two v1 v0)
	( not-output-two v1 v1)
	( not-output-two v1 v2)
	( not-output-two v1 v3)
	( not-output-two v1 v4)
	( not-output-two v1 v5)
	( not-output-two v1 v6)
	( not-output-two v2 v0)
	( not-output-two v2 v1)
	( not-output-two v2 v2)
	( not-output-two v2 v3)
	( not-output-two v2 v4)
	( not-output-two v2 v5)
	( not-output-two v2 v6)
	( not-output-two v3 v0)
	( not-output-two v3 v1)
	( not-output-two v3 v2)
	( not-output-two v3 v3)
	( not-output-two v3 v4)
	( not-output-two v3 v5)
	( not-output-two v3 v6)
	( not-output-two v4 v0)
	( not-output-two v4 v1)
	( not-output-two v4 v2)
	( not-output-two v4 v3)
	( not-output-two v4 v4)
	( not-output-two v4 v5)
	( not-output-two v4 v6)
	( not-output-two v5 v0)
	( not-output-two v5 v1)
	( not-output-two v5 v2)
	( not-output-two v5 v3)
	( not-output-two v5 v4)
	( not-output-two v5 v5)
	( not-output-two v5 v6)
	( not-output-two v6 v0)
	( not-output-two v6 v1)
	( not-output-two v6 v2)
	( not-output-two v6 v3)
	( not-output-two v6 v4)
	( not-output-two v6 v5)
	( not-output-two v6 v6)
	( assignment a v0)
	( assignment b v1)
	( assignment c v6)
	( assignment d v6) )
  (:goal
	( and
	( output-two v0 v0 )
	( not-output-two v0 v1)
	( not-output-two v0 v2)
	( not-output-two v0 v3)
	( not-output-two v0 v4)
	( not-output-two v0 v5)
	( output-two v0 v6 )
	( not-output-two v1 v0)
	( not-output-two v1 v1)
	( not-output-two v1 v2)
	( not-output-two v1 v3)
	( not-output-two v1 v4)
	( not-output-two v1 v5)
	( not-output-two v1 v6)
	( not-output-two v2 v0)
	( not-output-two v2 v1)
	( not-output-two v2 v2)
	( not-output-two v2 v3)
	( not-output-two v2 v4)
	( not-output-two v2 v5)
	( not-output-two v2 v6)
	( not-output-two v3 v0)
	( not-output-two v3 v1)
	( not-output-two v3 v2)
	( not-output-two v3 v3)
	( not-output-two v3 v4)
	( not-output-two v3 v5)
	( not-output-two v3 v6)
	( not-output-two v4 v0)
	( not-output-two v4 v1)
	( not-output-two v4 v2)
	( not-output-two v4 v3)
	( not-output-two v4 v4)
	( not-output-two v4 v5)
	( not-output-two v4 v6)
	( not-output-two v5 v0)
	( not-output-two v5 v1)
	( not-output-two v5 v2)
	( not-output-two v5 v3)
	( not-output-two v5 v4)
	( not-output-two v5 v5)
	( not-output-two v5 v6)
	( output-two v6 v0 )
	( not-output-two v6 v1)
	( not-output-two v6 v2)
	( not-output-two v6 v3)
	( not-output-two v6 v4)
	( not-output-two v6 v5)
	( output-two v6 v6 )
	)
  )
)