(define (problem list5-pos-a)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 - node )
  (:init ( at n3) ( not-visited n5 ) ( tail n5)( adjacent n3 n4)( not-visited n3 )( adjacent n4 n1)( not-visited n4 )( adjacent n1 n2)( not-visited n1 )( adjacent n2 n5)( not-visited n2 ) )
  (:goal (and ( visited n3 )( visited n4 )( visited n1 )( visited n2 )( visited n5 ))))
