(define (problem list10-neg-c)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 - node )
  (:init ( at n3) ( not-visited n4 ) ( tail n4)( adjacent n3 n9)( not-visited n3 )( adjacent n9 n7)( not-visited n9 )( adjacent n7 n5)( not-visited n7 )( adjacent n5 n1)( not-visited n5 )( adjacent n1 n8)( not-visited n1 )( adjacent n8 n6)( not-visited n8 )( adjacent n6 n10)( not-visited n6 )( adjacent n10 n2)( not-visited n10 )( adjacent n2 n4)( not-visited n2 ) )
  (:goal (and ( not-visited n3 )( not-visited n9 )( not-visited n7 )( not-visited n5 )( not-visited n1 )( not-visited n8 )( not-visited n6 )( not-visited n10 )( not-visited n2 )( not-visited n4 ))))
