(define (problem list8-neg-c)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 n6 n7 n8 - node )
  (:init ( at n4) ( not-visited n2 ) ( tail n2)( adjacent n4 n8)( not-visited n4 )( adjacent n8 n7)( not-visited n8 )( adjacent n7 n1)( not-visited n7 )( adjacent n1 n5)( not-visited n1 )( adjacent n5 n6)( not-visited n5 )( adjacent n6 n3)( not-visited n6 )( adjacent n3 n2)( not-visited n3 ) )
  (:goal (and ( visited n4 )( visited n8 )( not-visited n7 )( visited n1 )( not-visited n5 )( visited n6 )( visited n3 )( visited n2 ))))
