(define (problem list10-pos-a)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 - node )
  (:init ( at n6) ( not-visited n2 ) ( tail n2)( adjacent n6 n8)( not-visited n6 )( adjacent n8 n5)( not-visited n8 )( adjacent n5 n3)( not-visited n5 )( adjacent n3 n10)( not-visited n3 )( adjacent n10 n4)( not-visited n10 )( adjacent n4 n1)( not-visited n4 )( adjacent n1 n9)( not-visited n1 )( adjacent n9 n7)( not-visited n9 )( adjacent n7 n2)( not-visited n7 ) )
  (:goal (and ( visited n6 )( visited n8 )( visited n5 )( visited n3 )( visited n10 )( visited n4 )( visited n1 )( visited n9 )( visited n7 )( visited n2 ))))
