(define (problem list6-neg-b)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 n6 - node )
  (:init ( at n2) ( not-visited n5 ) ( tail n5)( adjacent n2 n4)( not-visited n2 )( adjacent n4 n6)( not-visited n4 )( adjacent n6 n1)( not-visited n6 )( adjacent n1 n3)( not-visited n1 )( adjacent n3 n5)( not-visited n3 ) )
  (:goal (and ( visited n2 )( visited n4 )( visited n6 )( not-visited n1 )( not-visited n3 )( not-visited n5 ))))
