(define (problem list3-neg-d)
  (:domain list)
  (:objects  n1 n2 n3 - node )
  (:init ( at n1) ( not-visited n2 ) ( tail n2)( adjacent n1 n3)( not-visited n1 )( adjacent n3 n2)( not-visited n3 ) )
  (:goal (and ( not-visited n1 )( visited n3 )( not-visited n2 ))))
