(define (problem list5-neg-c)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 - node )
  (:init ( at n2) ( not-visited n4 ) ( tail n4)( adjacent n2 n1)( not-visited n2 )( adjacent n1 n3)( not-visited n1 )( adjacent n3 n5)( not-visited n3 )( adjacent n5 n4)( not-visited n5 ) )
  (:goal (and ( not-visited n2 )( not-visited n1 )( visited n3 )( visited n5 )( visited n4 ))))
