(define (problem list4-pos-a)
  (:domain list)
  (:objects  n1 n2 n3 n4 - node )
  (:init ( at n3) ( not-visited n1 ) ( tail n1)( adjacent n3 n2)( not-visited n3 )( adjacent n2 n4)( not-visited n2 )( adjacent n4 n1)( not-visited n4 ) )
  (:goal (and ( visited n3 )( visited n2 )( visited n4 )( visited n1 ))))
