(define (problem list8-pos-a)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 n6 n7 n8 - node )
  (:init ( at n2) ( not-visited n5 ) ( tail n5)( adjacent n2 n7)( not-visited n2 )( adjacent n7 n1)( not-visited n7 )( adjacent n1 n6)( not-visited n1 )( adjacent n6 n8)( not-visited n6 )( adjacent n8 n4)( not-visited n8 )( adjacent n4 n3)( not-visited n4 )( adjacent n3 n5)( not-visited n3 ) )
  (:goal (and ( visited n2 )( visited n7 )( visited n1 )( visited n6 )( visited n8 )( visited n4 )( visited n3 )( visited n5 ))))
