(define (problem list9-neg-c)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 n6 n7 n8 n9 - node )
  (:init ( at n6) ( not-visited n9 ) ( tail n9)( adjacent n6 n2)( not-visited n6 )( adjacent n2 n8)( not-visited n2 )( adjacent n8 n4)( not-visited n8 )( adjacent n4 n5)( not-visited n4 )( adjacent n5 n1)( not-visited n5 )( adjacent n1 n7)( not-visited n1 )( adjacent n7 n3)( not-visited n7 )( adjacent n3 n9)( not-visited n3 ) )
  (:goal (and ( not-visited n6 )( not-visited n2 )( not-visited n8 )( not-visited n4 )( not-visited n5 )( visited n1 )( not-visited n7 )( not-visited n3 )( visited n9 ))))
