(define (problem list3-neg-b)
  (:domain list)
  (:objects  n1 n2 n3 - node )
  (:init ( at n3) ( not-visited n1 ) ( tail n1)( adjacent n3 n2)( not-visited n3 )( adjacent n2 n1)( not-visited n2 ) )
  (:goal (and ( not-visited n3 )( not-visited n2 )( not-visited n1 ))))
