(define (problem list7-pos-a)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 n6 n7 - node )
  (:init ( at n5) ( not-visited n6 ) ( tail n6)( adjacent n5 n4)( not-visited n5 )( adjacent n4 n3)( not-visited n4 )( adjacent n3 n7)( not-visited n3 )( adjacent n7 n2)( not-visited n7 )( adjacent n2 n1)( not-visited n2 )( adjacent n1 n6)( not-visited n1 ) )
  (:goal (and ( visited n5 )( visited n4 )( visited n3 )( visited n7 )( visited n2 )( visited n1 )( visited n6 ))))
