(define (problem list11-neg-d)
  (:domain list)
  (:objects  n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 - node )
  (:init ( at n2) ( not-visited n8 ) ( tail n8)( adjacent n2 n9)( not-visited n2 )( adjacent n9 n6)( not-visited n9 )( adjacent n6 n7)( not-visited n6 )( adjacent n7 n5)( not-visited n7 )( adjacent n5 n10)( not-visited n5 )( adjacent n10 n4)( not-visited n10 )( adjacent n4 n3)( not-visited n4 )( adjacent n3 n1)( not-visited n3 )( adjacent n1 n11)( not-visited n1 )( adjacent n11 n8)( not-visited n11 ) )
  (:goal (and ( visited n2 )( visited n9 )( visited n6 )( visited n7 )( visited n5 )( not-visited n10 )( visited n4 )( not-visited n3 )( visited n1 )( visited n11 )( visited n8 ))))
