(define (problem row3x6)
	(:domain vmarker)
	(:objects
		block empty green - relation
		v0 v1 v2 v3 v4 v5 v6 - value
		x y xm ym - variable
	)
	(:init 
		(assignment x v1)
		(assignment y v0)
		(assignment xm v3)
		(assignment ym v6)
		(next v0 v1)
		(next v1 v2)
		(next v2 v3)
		(next v3 v4)
		(next v4 v5)
		(next v5 v6)
		(includes-2ary block v0 v0)
		(includes-2ary block v0 v1)
		(includes-2ary empty v0 v2)
		(includes-2ary empty v0 v3)
		(includes-2ary empty v0 v4)
		(includes-2ary empty v0 v5)
		(includes-2ary block v1 v0)
		(includes-2ary block v1 v1)
		(includes-2ary block v1 v2)
		(includes-2ary block v1 v3)
		(includes-2ary empty v1 v4)
		(includes-2ary empty v1 v5)
		(includes-2ary block v2 v0)
		(includes-2ary block v2 v1)
		(includes-2ary block v2 v2)
		(includes-2ary green v2 v2)
		(includes-2ary block v2 v3)
		(includes-2ary block v2 v4)
		(includes-2ary empty v2 v5)
	)
	(:goal (and
		(assignment x v1)
		(assignment y v4)
	))
)
