(define (problem p2)
	(:domain SerialBinaryAdder)
	(:objects i0 i1 i2 last - index  )
	(:init 
		(at i0)
		(next i0 i1)
		(next i1 i2)
		(next i2 last)

		(one first i0 )
		(zero first i1 )
		(one first i2 )

		(zero second i0 )
		(one second i1 )
		(one second i2 )
		(zero second i3 )
		(one second i4 )
		(zero second i5 )
		(one second i6 )
		(zero second i7 )
	)
	(:goal (and 
		(one res i0 )
		(one res i1 )
		(zero res i2 )
		(zero res i3 )
		(one res i4 )
		(zero res i5 )
		(one res i6 )
		(one res i7 )
	))
)
