./scripts/neg/aaai20/gb-val/gb-NEG-1-1-a-val.sh experiments/neg/aaai20/gb/1.neg.program > experiments/neg/aaai20/gb/1.neg.val 2> experiments/neg/aaai20/gb/1.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-1-b-val.sh experiments/neg/aaai20/gb/2.neg.program > experiments/neg/aaai20/gb/2.neg.val 2> experiments/neg/aaai20/gb/2.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-1-c-val.sh experiments/neg/aaai20/gb/3.neg.program > experiments/neg/aaai20/gb/3.neg.val 2> experiments/neg/aaai20/gb/3.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-1-d-val.sh experiments/neg/aaai20/gb/4.neg.program > experiments/neg/aaai20/gb/4.neg.val 2> experiments/neg/aaai20/gb/4.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-2-a-val.sh experiments/neg/aaai20/gb/5.neg.program > experiments/neg/aaai20/gb/5.neg.val 2> experiments/neg/aaai20/gb/5.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-2-b-val.sh experiments/neg/aaai20/gb/6.neg.program > experiments/neg/aaai20/gb/6.neg.val 2> experiments/neg/aaai20/gb/6.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-2-c-val.sh experiments/neg/aaai20/gb/7.neg.program > experiments/neg/aaai20/gb/7.neg.val 2> experiments/neg/aaai20/gb/7.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-3-1-a-val.sh experiments/neg/aaai20/gb/8.neg.program > experiments/neg/aaai20/gb/8.neg.val 2> experiments/neg/aaai20/gb/8.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-2-d-val.sh experiments/neg/aaai20/gb/9.neg.program > experiments/neg/aaai20/gb/9.neg.val 2> experiments/neg/aaai20/gb/9.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-3-1-b-val.sh experiments/neg/aaai20/gb/10.neg.program > experiments/neg/aaai20/gb/10.neg.val 2> experiments/neg/aaai20/gb/10.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-3-a-val.sh experiments/neg/aaai20/gb/11.neg.program > experiments/neg/aaai20/gb/11.neg.val 2> experiments/neg/aaai20/gb/11.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-3-1-c-val.sh experiments/neg/aaai20/gb/12.neg.program > experiments/neg/aaai20/gb/12.neg.val 2> experiments/neg/aaai20/gb/12.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-3-b-val.sh experiments/neg/aaai20/gb/13.neg.program > experiments/neg/aaai20/gb/13.neg.val 2> experiments/neg/aaai20/gb/13.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-3-1-d-val.sh experiments/neg/aaai20/gb/14.neg.program > experiments/neg/aaai20/gb/14.neg.val 2> experiments/neg/aaai20/gb/14.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-3-c-val.sh experiments/neg/aaai20/gb/15.neg.program > experiments/neg/aaai20/gb/15.neg.val 2> experiments/neg/aaai20/gb/15.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-3-2-a-val.sh experiments/neg/aaai20/gb/16.neg.program > experiments/neg/aaai20/gb/16.neg.val 2> experiments/neg/aaai20/gb/16.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-3-d-val.sh experiments/neg/aaai20/gb/17.neg.program > experiments/neg/aaai20/gb/17.neg.val 2> experiments/neg/aaai20/gb/17.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-3-2-b-val.sh experiments/neg/aaai20/gb/18.neg.program > experiments/neg/aaai20/gb/18.neg.val 2> experiments/neg/aaai20/gb/18.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-4-a-val.sh experiments/neg/aaai20/gb/19.neg.program > experiments/neg/aaai20/gb/19.neg.val 2> experiments/neg/aaai20/gb/19.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-3-2-c-val.sh experiments/neg/aaai20/gb/20.neg.program > experiments/neg/aaai20/gb/20.neg.val 2> experiments/neg/aaai20/gb/20.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-4-b-val.sh experiments/neg/aaai20/gb/21.neg.program > experiments/neg/aaai20/gb/21.neg.val 2> experiments/neg/aaai20/gb/21.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-3-2-d-val.sh experiments/neg/aaai20/gb/22.neg.program > experiments/neg/aaai20/gb/22.neg.val 2> experiments/neg/aaai20/gb/22.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-4-c-val.sh experiments/neg/aaai20/gb/23.neg.program > experiments/neg/aaai20/gb/23.neg.val 2> experiments/neg/aaai20/gb/23.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-1-4-d-val.sh experiments/neg/aaai20/gb/24.neg.program > experiments/neg/aaai20/gb/24.neg.val 2> experiments/neg/aaai20/gb/24.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-1-a-val.sh experiments/neg/aaai20/gb/25.neg.program > experiments/neg/aaai20/gb/25.neg.val 2> experiments/neg/aaai20/gb/25.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-1-b-val.sh experiments/neg/aaai20/gb/26.neg.program > experiments/neg/aaai20/gb/26.neg.val 2> experiments/neg/aaai20/gb/26.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-1-c-val.sh experiments/neg/aaai20/gb/27.neg.program > experiments/neg/aaai20/gb/27.neg.val 2> experiments/neg/aaai20/gb/27.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-1-d-val.sh experiments/neg/aaai20/gb/28.neg.program > experiments/neg/aaai20/gb/28.neg.val 2> experiments/neg/aaai20/gb/28.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-2-a-val.sh experiments/neg/aaai20/gb/29.neg.program > experiments/neg/aaai20/gb/29.neg.val 2> experiments/neg/aaai20/gb/29.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-2-b-val.sh experiments/neg/aaai20/gb/30.neg.program > experiments/neg/aaai20/gb/30.neg.val 2> experiments/neg/aaai20/gb/30.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-2-c-val.sh experiments/neg/aaai20/gb/31.neg.program > experiments/neg/aaai20/gb/31.neg.val 2> experiments/neg/aaai20/gb/31.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-4-1-a-val.sh experiments/neg/aaai20/gb/32.neg.program > experiments/neg/aaai20/gb/32.neg.val 2> experiments/neg/aaai20/gb/32.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-2-d-val.sh experiments/neg/aaai20/gb/33.neg.program > experiments/neg/aaai20/gb/33.neg.val 2> experiments/neg/aaai20/gb/33.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-4-1-b-val.sh experiments/neg/aaai20/gb/34.neg.program > experiments/neg/aaai20/gb/34.neg.val 2> experiments/neg/aaai20/gb/34.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-3-a-val.sh experiments/neg/aaai20/gb/35.neg.program > experiments/neg/aaai20/gb/35.neg.val 2> experiments/neg/aaai20/gb/35.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-4-1-c-val.sh experiments/neg/aaai20/gb/36.neg.program > experiments/neg/aaai20/gb/36.neg.val 2> experiments/neg/aaai20/gb/36.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-3-b-val.sh experiments/neg/aaai20/gb/37.neg.program > experiments/neg/aaai20/gb/37.neg.val 2> experiments/neg/aaai20/gb/37.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-4-1-d-val.sh experiments/neg/aaai20/gb/38.neg.program > experiments/neg/aaai20/gb/38.neg.val 2> experiments/neg/aaai20/gb/38.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-3-c-val.sh experiments/neg/aaai20/gb/39.neg.program > experiments/neg/aaai20/gb/39.neg.val 2> experiments/neg/aaai20/gb/39.neg.val.err
./scripts/neg/aaai20/gb-val/gb-NEG-2-3-d-val.sh experiments/neg/aaai20/gb/40.neg.program > experiments/neg/aaai20/gb/40.neg.val 2> experiments/neg/aaai20/gb/40.neg.val.err

