./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-1-a-val.sh experiments/neg/aaai20/gb/1.neglite.program > experiments/neg/aaai20/gb/1.neglite.val 2> experiments/neg/aaai20/gb/1.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-1-b-val.sh experiments/neg/aaai20/gb/2.neglite.program > experiments/neg/aaai20/gb/2.neglite.val 2> experiments/neg/aaai20/gb/2.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-1-c-val.sh experiments/neg/aaai20/gb/3.neglite.program > experiments/neg/aaai20/gb/3.neglite.val 2> experiments/neg/aaai20/gb/3.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-1-d-val.sh experiments/neg/aaai20/gb/4.neglite.program > experiments/neg/aaai20/gb/4.neglite.val 2> experiments/neg/aaai20/gb/4.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-2-a-val.sh experiments/neg/aaai20/gb/5.neglite.program > experiments/neg/aaai20/gb/5.neglite.val 2> experiments/neg/aaai20/gb/5.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-2-b-val.sh experiments/neg/aaai20/gb/6.neglite.program > experiments/neg/aaai20/gb/6.neglite.val 2> experiments/neg/aaai20/gb/6.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-2-c-val.sh experiments/neg/aaai20/gb/7.neglite.program > experiments/neg/aaai20/gb/7.neglite.val 2> experiments/neg/aaai20/gb/7.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-3-1-a-val.sh experiments/neg/aaai20/gb/8.neglite.program > experiments/neg/aaai20/gb/8.neglite.val 2> experiments/neg/aaai20/gb/8.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-2-d-val.sh experiments/neg/aaai20/gb/9.neglite.program > experiments/neg/aaai20/gb/9.neglite.val 2> experiments/neg/aaai20/gb/9.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-3-1-b-val.sh experiments/neg/aaai20/gb/10.neglite.program > experiments/neg/aaai20/gb/10.neglite.val 2> experiments/neg/aaai20/gb/10.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-3-a-val.sh experiments/neg/aaai20/gb/11.neglite.program > experiments/neg/aaai20/gb/11.neglite.val 2> experiments/neg/aaai20/gb/11.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-3-1-c-val.sh experiments/neg/aaai20/gb/12.neglite.program > experiments/neg/aaai20/gb/12.neglite.val 2> experiments/neg/aaai20/gb/12.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-3-b-val.sh experiments/neg/aaai20/gb/13.neglite.program > experiments/neg/aaai20/gb/13.neglite.val 2> experiments/neg/aaai20/gb/13.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-3-1-d-val.sh experiments/neg/aaai20/gb/14.neglite.program > experiments/neg/aaai20/gb/14.neglite.val 2> experiments/neg/aaai20/gb/14.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-3-c-val.sh experiments/neg/aaai20/gb/15.neglite.program > experiments/neg/aaai20/gb/15.neglite.val 2> experiments/neg/aaai20/gb/15.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-3-2-a-val.sh experiments/neg/aaai20/gb/16.neglite.program > experiments/neg/aaai20/gb/16.neglite.val 2> experiments/neg/aaai20/gb/16.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-3-d-val.sh experiments/neg/aaai20/gb/17.neglite.program > experiments/neg/aaai20/gb/17.neglite.val 2> experiments/neg/aaai20/gb/17.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-3-2-b-val.sh experiments/neg/aaai20/gb/18.neglite.program > experiments/neg/aaai20/gb/18.neglite.val 2> experiments/neg/aaai20/gb/18.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-4-a-val.sh experiments/neg/aaai20/gb/19.neglite.program > experiments/neg/aaai20/gb/19.neglite.val 2> experiments/neg/aaai20/gb/19.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-3-2-c-val.sh experiments/neg/aaai20/gb/20.neglite.program > experiments/neg/aaai20/gb/20.neglite.val 2> experiments/neg/aaai20/gb/20.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-4-b-val.sh experiments/neg/aaai20/gb/21.neglite.program > experiments/neg/aaai20/gb/21.neglite.val 2> experiments/neg/aaai20/gb/21.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-3-2-d-val.sh experiments/neg/aaai20/gb/22.neglite.program > experiments/neg/aaai20/gb/22.neglite.val 2> experiments/neg/aaai20/gb/22.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-4-c-val.sh experiments/neg/aaai20/gb/23.neglite.program > experiments/neg/aaai20/gb/23.neglite.val 2> experiments/neg/aaai20/gb/23.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-1-4-d-val.sh experiments/neg/aaai20/gb/24.neglite.program > experiments/neg/aaai20/gb/24.neglite.val 2> experiments/neg/aaai20/gb/24.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-1-a-val.sh experiments/neg/aaai20/gb/25.neglite.program > experiments/neg/aaai20/gb/25.neglite.val 2> experiments/neg/aaai20/gb/25.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-1-b-val.sh experiments/neg/aaai20/gb/26.neglite.program > experiments/neg/aaai20/gb/26.neglite.val 2> experiments/neg/aaai20/gb/26.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-1-c-val.sh experiments/neg/aaai20/gb/27.neglite.program > experiments/neg/aaai20/gb/27.neglite.val 2> experiments/neg/aaai20/gb/27.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-1-d-val.sh experiments/neg/aaai20/gb/28.neglite.program > experiments/neg/aaai20/gb/28.neglite.val 2> experiments/neg/aaai20/gb/28.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-2-a-val.sh experiments/neg/aaai20/gb/29.neglite.program > experiments/neg/aaai20/gb/29.neglite.val 2> experiments/neg/aaai20/gb/29.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-2-b-val.sh experiments/neg/aaai20/gb/30.neglite.program > experiments/neg/aaai20/gb/30.neglite.val 2> experiments/neg/aaai20/gb/30.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-2-c-val.sh experiments/neg/aaai20/gb/31.neglite.program > experiments/neg/aaai20/gb/31.neglite.val 2> experiments/neg/aaai20/gb/31.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-4-1-a-val.sh experiments/neg/aaai20/gb/32.neglite.program > experiments/neg/aaai20/gb/32.neglite.val 2> experiments/neg/aaai20/gb/32.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-2-d-val.sh experiments/neg/aaai20/gb/33.neglite.program > experiments/neg/aaai20/gb/33.neglite.val 2> experiments/neg/aaai20/gb/33.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-4-1-b-val.sh experiments/neg/aaai20/gb/34.neglite.program > experiments/neg/aaai20/gb/34.neglite.val 2> experiments/neg/aaai20/gb/34.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-3-a-val.sh experiments/neg/aaai20/gb/35.neglite.program > experiments/neg/aaai20/gb/35.neglite.val 2> experiments/neg/aaai20/gb/35.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-4-1-c-val.sh experiments/neg/aaai20/gb/36.neglite.program > experiments/neg/aaai20/gb/36.neglite.val 2> experiments/neg/aaai20/gb/36.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-3-b-val.sh experiments/neg/aaai20/gb/37.neglite.program > experiments/neg/aaai20/gb/37.neglite.val 2> experiments/neg/aaai20/gb/37.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-4-1-d-val.sh experiments/neg/aaai20/gb/38.neglite.program > experiments/neg/aaai20/gb/38.neglite.val 2> experiments/neg/aaai20/gb/38.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-3-c-val.sh experiments/neg/aaai20/gb/39.neglite.program > experiments/neg/aaai20/gb/39.neglite.val 2> experiments/neg/aaai20/gb/39.neglite.val.err
./scripts/neg/aaai20/gb-val/gb-NEGLITE-2-3-d-val.sh experiments/neg/aaai20/gb/40.neglite.program > experiments/neg/aaai20/gb/40.neglite.val 2> experiments/neg/aaai20/gb/40.neglite.val.err

