( DEFINE ( DOMAIN ELEVATORS-SEQUENCEDSTRIPS )
( :REQUIREMENTS :ACTION-COSTS :TYPING )
( :TYPES
	ELEVATOR - OBJECT
	SLOW-ELEVATOR - ELEVATOR
	FAST-ELEVATOR - ELEVATOR
	PASSENGER - OBJECT
	COUNT - OBJECT
)
( :PREDICATES
	( PASSENGER-AT ?PASSENGER0 - PASSENGER ?COUNT1 - COUNT )
	( BOARDED ?PASSENGER0 - PASSENGER ?ELEVATOR1 - ELEVATOR )
	( LIFT-AT ?ELEVATOR0 - ELEVATOR ?COUNT1 - COUNT )
	( REACHABLE-FLOOR ?ELEVATOR0 - ELEVATOR ?COUNT1 - COUNT )
	( ABOVE ?COUNT0 - COUNT ?COUNT1 - COUNT )
	( PASSENGERS ?ELEVATOR0 - ELEVATOR ?COUNT1 - COUNT )
	( CAN-HOLD ?ELEVATOR0 - ELEVATOR ?COUNT1 - COUNT )
	( NEXT ?COUNT0 - COUNT ?COUNT1 - COUNT )
)
( :FUNCTIONS
	( TOTAL-COST )
	( TRAVEL-SLOW ?COUNT0 - COUNT ?COUNT1 - COUNT )
	( TRAVEL-FAST ?COUNT0 - COUNT ?COUNT1 - COUNT )
)
( :ACTION MOVE-UP-SLOW
  :PARAMETERS ( ?SLOW-ELEVATOR0 - SLOW-ELEVATOR ?COUNT1 - COUNT ?COUNT2 - COUNT )
  :PRECONDITION
	( AND
		( LIFT-AT ?SLOW-ELEVATOR0 ?COUNT1 )
		( ABOVE ?COUNT1 ?COUNT2 )
		( REACHABLE-FLOOR ?SLOW-ELEVATOR0 ?COUNT2 )
	)
  :EFFECT
	( AND
		( LIFT-AT ?SLOW-ELEVATOR0 ?COUNT2 )
		( NOT ( LIFT-AT ?SLOW-ELEVATOR0 ?COUNT1 ) )
		( INCREASE ( TOTAL-COST ) ( TRAVEL-SLOW ?COUNT1 ?COUNT2 ) )
	)
)
( :ACTION MOVE-DOWN-SLOW
  :PARAMETERS ( ?SLOW-ELEVATOR0 - SLOW-ELEVATOR ?COUNT1 - COUNT ?COUNT2 - COUNT )
  :PRECONDITION
	( AND
		( LIFT-AT ?SLOW-ELEVATOR0 ?COUNT1 )
		( ABOVE ?COUNT2 ?COUNT1 )
		( REACHABLE-FLOOR ?SLOW-ELEVATOR0 ?COUNT2 )
	)
  :EFFECT
	( AND
		( LIFT-AT ?SLOW-ELEVATOR0 ?COUNT2 )
		( NOT ( LIFT-AT ?SLOW-ELEVATOR0 ?COUNT1 ) )
		( INCREASE ( TOTAL-COST ) ( TRAVEL-SLOW ?COUNT2 ?COUNT1 ) )
	)
)
( :ACTION MOVE-UP-FAST
  :PARAMETERS ( ?FAST-ELEVATOR0 - FAST-ELEVATOR ?COUNT1 - COUNT ?COUNT2 - COUNT )
  :PRECONDITION
	( AND
		( LIFT-AT ?FAST-ELEVATOR0 ?COUNT1 )
		( ABOVE ?COUNT1 ?COUNT2 )
		( REACHABLE-FLOOR ?FAST-ELEVATOR0 ?COUNT2 )
	)
  :EFFECT
	( AND
		( LIFT-AT ?FAST-ELEVATOR0 ?COUNT2 )
		( NOT ( LIFT-AT ?FAST-ELEVATOR0 ?COUNT1 ) )
		( INCREASE ( TOTAL-COST ) ( TRAVEL-FAST ?COUNT1 ?COUNT2 ) )
	)
)
( :ACTION MOVE-DOWN-FAST
  :PARAMETERS ( ?FAST-ELEVATOR0 - FAST-ELEVATOR ?COUNT1 - COUNT ?COUNT2 - COUNT )
  :PRECONDITION
	( AND
		( LIFT-AT ?FAST-ELEVATOR0 ?COUNT1 )
		( ABOVE ?COUNT2 ?COUNT1 )
		( REACHABLE-FLOOR ?FAST-ELEVATOR0 ?COUNT2 )
	)
  :EFFECT
	( AND
		( LIFT-AT ?FAST-ELEVATOR0 ?COUNT2 )
		( NOT ( LIFT-AT ?FAST-ELEVATOR0 ?COUNT1 ) )
		( INCREASE ( TOTAL-COST ) ( TRAVEL-FAST ?COUNT2 ?COUNT1 ) )
	)
)
( :ACTION BOARD
  :PARAMETERS ( ?PASSENGER0 - PASSENGER ?ELEVATOR1 - ELEVATOR ?COUNT2 - COUNT ?COUNT3 - COUNT ?COUNT4 - COUNT )
  :PRECONDITION
	( AND
		( LIFT-AT ?ELEVATOR1 ?COUNT2 )
		( PASSENGER-AT ?PASSENGER0 ?COUNT2 )
		( PASSENGERS ?ELEVATOR1 ?COUNT3 )
		( NEXT ?COUNT3 ?COUNT4 )
		( CAN-HOLD ?ELEVATOR1 ?COUNT4 )
	)
  :EFFECT
	( AND
		( NOT ( PASSENGER-AT ?PASSENGER0 ?COUNT2 ) )
		( BOARDED ?PASSENGER0 ?ELEVATOR1 )
		( NOT ( PASSENGERS ?ELEVATOR1 ?COUNT3 ) )
		( PASSENGERS ?ELEVATOR1 ?COUNT4 )
	)
)
( :ACTION LEAVE
  :PARAMETERS ( ?PASSENGER0 - PASSENGER ?ELEVATOR1 - ELEVATOR ?COUNT2 - COUNT ?COUNT3 - COUNT ?COUNT4 - COUNT )
  :PRECONDITION
	( AND
		( LIFT-AT ?ELEVATOR1 ?COUNT2 )
		( BOARDED ?PASSENGER0 ?ELEVATOR1 )
		( PASSENGERS ?ELEVATOR1 ?COUNT3 )
		( NEXT ?COUNT4 ?COUNT3 )
	)
  :EFFECT
	( AND
		( PASSENGER-AT ?PASSENGER0 ?COUNT2 )
		( NOT ( BOARDED ?PASSENGER0 ?ELEVATOR1 ) )
		( NOT ( PASSENGERS ?ELEVATOR1 ?COUNT3 ) )
		( PASSENGERS ?ELEVATOR1 ?COUNT4 )
	)
)
)
