(define (problem p3c)
  (:domain pointers )
  (:objects  v0 v1 v2 - value 
  )
  (:init
	( next v0 v1)
	( next v1 v2)
	( less v0 v1)
	( less v0 v2)
	( less v1 v2)
	( vector-assignment v0 v2)
	( vector-assignment v1 v0)
	( vector-assignment v2 v1)
	( assignment a v0 )
	( content a v2 )
	( assignment b v2 )
	( content b v1 ) )
  (:goal
	( and
	( vector-assignment v0 v1)
	( vector-assignment v1 v0)
	( vector-assignment v2 v2)
	)
  )
)