(define (problem p10d)
  (:domain blocksworld)
  (:objects 
	 c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 - columns  b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block )
	
  (:init
	( adjacent-columns c1 c2 )
	( adjacent-columns c2 c3 )
	( adjacent-columns c3 c4 )
	( adjacent-columns c4 c5 )
	( adjacent-columns c5 c6 )
	( adjacent-columns c6 c7 )
	( adjacent-columns c7 c8 )
	( adjacent-columns c8 c9 )
	( adjacent-columns c9 c10 )
	( handempty )
	( current-columns c2 )
	( goal-columns c9 )
	( ontable b8 )
	( on b5 b8 )
	( on b10 b5 )
	( on b1 b10 )
	( on b9 b1 )
	( on b2 b9 )
	( on b7 b2 )
	( clear b7 )
	( ontable b4 )
	( on b3 b4 )
	( on b6 b3 )
	( clear b6 ) )
  (:goal
	( and 
	( ontable b7 )
	( clear b7 )
	( ontable b6 )
	( clear b6 )
	( ontable b4 )
	( on b1 b4 )
	( clear b1 )
	( ontable b5 )
	( clear b5 )
	( ontable b8 )
	( clear b8 )
	( ontable b3 )
	( clear b3 )
	( ontable b2 )
	( clear b2 )
	( ontable b9 )
	( clear b9 )
	( ontable b10 )
	( clear b10 )
	)
  )
)