(define (problem p6a)
  (:domain blocksworld)
  (:objects 
	 c1 c2 c3 c4 c5 c6 - columns  b1 b2 b3 b4 b5 b6 - block )
	
  (:init
	( adjacent-columns c1 c2 )
	( adjacent-columns c2 c3 )
	( adjacent-columns c3 c4 )
	( adjacent-columns c4 c5 )
	( adjacent-columns c5 c6 )
	( handempty )
	( current-columns c6 )
	( goal-columns c4 )
	( ontable b5 )
	( clear b5 )
	( ontable b3 )
	( clear b3 )
	( ontable b1 )
	( clear b1 )
	( ontable b6 )
	( clear b6 )
	( ontable b2 )
	( clear b2 )
	( ontable b4 )
	( clear b4 ) )
  (:goal
	( and 
	( ontable b6 )
	( on b4 b6 )
	( on b3 b4 )
	( clear b3 )
	( ontable b2 )
	( clear b2 )
	( ontable b1 )
	( clear b1 )
	( ontable b5 )
	( clear b5 )
	)
  )
)