(define (problem p10d)
  (:domain pointers )
  (:objects  v0 v1 v2 v3 v4 v5 v6 v7 v8 v9 - value 
  )
  (:init
	( next v0 v1)
	( next v1 v2)
	( next v2 v3)
	( next v3 v4)
	( next v4 v5)
	( next v5 v6)
	( next v6 v7)
	( next v7 v8)
	( next v8 v9)
	( vector-assignment v0 v1)
	( vector-assignment v1 v0)
	( vector-assignment v2 v1)
	( vector-assignment v3 v3)
	( vector-assignment v4 v7)
	( vector-assignment v5 v3)
	( vector-assignment v6 v7)
	( vector-assignment v7 v2)
	( vector-assignment v8 v1)
	( vector-assignment v9 v6)
	( assignment a v0 )
	( content a v1 )
	( assignment c v0 )
	( assignment target v1)
	( assignment tail v9) )
  (:goal
	( and
	( assignment a v9 )
	( assignment c v3 )
	)
  )
)