(define (problem p7)
  (:domain pointers )
  (:objects  v0 v1 v2 v3 v4 v5 v6 - value 
  )
  (:init
	( next v0 v1)
	( next v1 v2)
	( next v2 v3)
	( next v3 v4)
	( next v4 v5)
	( next v5 v6)
	( vector-assignment v0 v1)
	( vector-assignment v1 v1)
	( vector-assignment v2 v6)
	( vector-assignment v3 v5)
	( vector-assignment v4 v4)
	( vector-assignment v5 v2)
	( vector-assignment v6 v6)
	( assignment a v0 )
	( content a v1 )
	( assignment c v0 )
	( assignment target v0)
	( assignment tail v6) )
  (:goal
	( and
	( assignment a v6 )
	( assignment c v0 )
	)
  )
)