(define (problem p9a)
  (:domain pointers )
  (:objects  v0 v1 v2 v3 v4 v5 v6 v7 v8 - value 
  )
  (:init
	( next v0 v1)
	( next v1 v2)
	( next v2 v3)
	( next v3 v4)
	( next v4 v5)
	( next v5 v6)
	( next v6 v7)
	( next v7 v8)
	( vector-assignment v0 v4)
	( vector-assignment v1 v4)
	( vector-assignment v2 v0)
	( vector-assignment v3 v4)
	( vector-assignment v4 v1)
	( vector-assignment v5 v6)
	( vector-assignment v6 v5)
	( vector-assignment v7 v0)
	( vector-assignment v8 v6)
	( assignment a v0 )
	( content a v4 )
	( assignment c v0 )
	( assignment target v3)
	( assignment tail v8) )
  (:goal
	( and
	( assignment a v8 )
	( assignment c v0 )
	)
  )
)