( DEFINE ( DOMAIN SCHEDULE )
( :REQUIREMENTS :STRIPS )
( :CONSTANTS
	COLD HOT CYLINDRICAL POLISHER ROLLER LATHE GRINDER PUNCH DRILL-PRESS SPRAY-PAINTER IMMERSION-PAINTER POLISHED ROUGH SMOOTH NOWIDTH NOORIENT UNDEFINED NOPAINT UNWANTEDARGS 
)
( :PREDICATES
	( PART ?OBJECT0 )
	( TEMPERATURE ?OBJECT0 ?OBJECT1 )
	( BUSY ?OBJECT0 )
	( IDLE ?OBJECT0 )
	( SCHEDULED ?OBJECT0 ?OBJECT1 )
	( UNSCHEDULED ?OBJECT0 )
	( SURFACE-CONDITION ?OBJECT0 ?OBJECT1 )
	( SHAPE ?OBJECT0 ?OBJECT1 )
	( PAINTED ?OBJECT0 ?OBJECT1 )
	( HAS-HOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 )
	( HAS-BIT ?OBJECT0 ?OBJECT1 )
	( CAN-ORIENT ?OBJECT0 ?OBJECT1 )
	( HAS-PAINT ?OBJECT0 ?OBJECT1 )
	( LASTHOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 )
	( LINKED ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 ?OBJECT4 )
	( RU ?OBJECT0 )
)
( :ACTION DO-POLISH
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 )
  :PRECONDITION
	( AND
		( RU ?OBJECT1 )
		( PART ?OBJECT0 )
		( IDLE POLISHER )
		( UNSCHEDULED ?OBJECT0 )
		( TEMPERATURE ?OBJECT0 COLD )
		( SURFACE-CONDITION ?OBJECT0 ?OBJECT2 )
	)
  :EFFECT
	( AND
		( BUSY POLISHER )
		( NOT ( IDLE POLISHER ) )
		( SCHEDULED ?OBJECT0 POLISHER )
		( NOT ( UNSCHEDULED ?OBJECT0 ) )
		( SURFACE-CONDITION ?OBJECT0 POLISHED )
		( NOT ( SURFACE-CONDITION ?OBJECT0 ?OBJECT2 ) )
	)
)
( :ACTION DO-ROLL
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 ?OBJECT4 ?OBJECT5 )
  :PRECONDITION
	( AND
		( RU ?OBJECT1 )
		( PART ?OBJECT0 )
		( IDLE ROLLER )
		( UNSCHEDULED ?OBJECT0 )
		( SURFACE-CONDITION ?OBJECT0 ?OBJECT2 )
		( TEMPERATURE ?OBJECT0 ?OBJECT3 )
		( SHAPE ?OBJECT0 ?OBJECT4 )
		( PAINTED ?OBJECT0 ?OBJECT5 )
		( LASTHOLE ?OBJECT0 NOWIDTH NOORIENT )
	)
  :EFFECT
	( AND
		( BUSY ROLLER )
		( NOT ( IDLE ROLLER ) )
		( SCHEDULED ?OBJECT0 ROLLER )
		( NOT ( UNSCHEDULED ?OBJECT0 ) )
		( TEMPERATURE ?OBJECT0 HOT )
		( NOT ( TEMPERATURE ?OBJECT0 ?OBJECT3 ) )
		( SHAPE ?OBJECT0 CYLINDRICAL )
		( NOT ( SHAPE ?OBJECT0 ?OBJECT4 ) )
		( NOT ( PAINTED ?OBJECT0 ?OBJECT5 ) )
		( PAINTED ?OBJECT0 NOPAINT )
		( SURFACE-CONDITION ?OBJECT0 ROUGH )
		( NOT ( SURFACE-CONDITION ?OBJECT0 ?OBJECT2 ) )
	)
)
( :ACTION DO-LATHE
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 ?OBJECT4 )
  :PRECONDITION
	( AND
		( RU ?OBJECT1 )
		( PART ?OBJECT0 )
		( IDLE LATHE )
		( UNSCHEDULED ?OBJECT0 )
		( PAINTED ?OBJECT0 ?OBJECT3 )
		( SHAPE ?OBJECT0 ?OBJECT2 )
		( SURFACE-CONDITION ?OBJECT0 ?OBJECT4 )
	)
  :EFFECT
	( AND
		( BUSY LATHE )
		( NOT ( IDLE LATHE ) )
		( SCHEDULED ?OBJECT0 LATHE )
		( NOT ( UNSCHEDULED ?OBJECT0 ) )
		( SURFACE-CONDITION ?OBJECT0 ROUGH )
		( SHAPE ?OBJECT0 CYLINDRICAL )
		( NOT ( SHAPE ?OBJECT0 ?OBJECT2 ) )
		( NOT ( SURFACE-CONDITION ?OBJECT0 ?OBJECT4 ) )
		( PAINTED ?OBJECT0 NOPAINT )
		( NOT ( PAINTED ?OBJECT0 ?OBJECT3 ) )
	)
)
( :ACTION DO-GRIND
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 )
  :PRECONDITION
	( AND
		( RU ?OBJECT1 )
		( PART ?OBJECT0 )
		( IDLE GRINDER )
		( UNSCHEDULED ?OBJECT0 )
		( SURFACE-CONDITION ?OBJECT0 ?OBJECT3 )
		( PAINTED ?OBJECT0 ?OBJECT2 )
	)
  :EFFECT
	( AND
		( BUSY GRINDER )
		( NOT ( IDLE GRINDER ) )
		( SCHEDULED ?OBJECT0 GRINDER )
		( NOT ( UNSCHEDULED ?OBJECT0 ) )
		( SURFACE-CONDITION ?OBJECT0 SMOOTH )
		( NOT ( SURFACE-CONDITION ?OBJECT0 ?OBJECT3 ) )
		( PAINTED ?OBJECT0 NOPAINT )
		( NOT ( PAINTED ?OBJECT0 ?OBJECT2 ) )
	)
)
( :ACTION DO-PUNCH
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 ?OBJECT4 ?OBJECT5 ?OBJECT6 )
  :PRECONDITION
	( AND
		( RU ?OBJECT3 )
		( PART ?OBJECT0 )
		( HAS-BIT PUNCH ?OBJECT1 )
		( CAN-ORIENT PUNCH ?OBJECT2 )
		( TEMPERATURE ?OBJECT0 COLD )
		( IDLE PUNCH )
		( UNSCHEDULED ?OBJECT0 )
		( SURFACE-CONDITION ?OBJECT0 ?OBJECT4 )
		( LASTHOLE ?OBJECT0 ?OBJECT5 ?OBJECT6 )
	)
  :EFFECT
	( AND
		( BUSY PUNCH )
		( NOT ( IDLE PUNCH ) )
		( SCHEDULED ?OBJECT0 PUNCH )
		( NOT ( UNSCHEDULED ?OBJECT0 ) )
		( HAS-HOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 )
		( LASTHOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 )
		( LINKED ?OBJECT0 ?OBJECT5 ?OBJECT6 ?OBJECT1 ?OBJECT2 )
		( NOT ( LASTHOLE ?OBJECT0 ?OBJECT5 ?OBJECT6 ) )
		( SURFACE-CONDITION ?OBJECT0 ROUGH )
		( NOT ( SURFACE-CONDITION ?OBJECT0 ?OBJECT4 ) )
	)
)
( :ACTION DO-DRILL-PRESS
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 ?OBJECT4 ?OBJECT5 )
  :PRECONDITION
	( AND
		( RU ?OBJECT3 )
		( PART ?OBJECT0 )
		( HAS-BIT DRILL-PRESS ?OBJECT1 )
		( CAN-ORIENT DRILL-PRESS ?OBJECT2 )
		( TEMPERATURE ?OBJECT0 COLD )
		( IDLE DRILL-PRESS )
		( UNSCHEDULED ?OBJECT0 )
		( LASTHOLE ?OBJECT0 ?OBJECT4 ?OBJECT5 )
	)
  :EFFECT
	( AND
		( BUSY DRILL-PRESS )
		( NOT ( IDLE DRILL-PRESS ) )
		( SCHEDULED ?OBJECT0 DRILL-PRESS )
		( NOT ( UNSCHEDULED ?OBJECT0 ) )
		( LASTHOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 )
		( LINKED ?OBJECT0 ?OBJECT4 ?OBJECT5 ?OBJECT1 ?OBJECT2 )
		( NOT ( LASTHOLE ?OBJECT0 ?OBJECT4 ?OBJECT5 ) )
		( HAS-HOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 )
	)
)
( :ACTION DO-SPRAY-PAINT
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 ?OBJECT4 )
  :PRECONDITION
	( AND
		( PART ?OBJECT0 )
		( RU ?OBJECT2 )
		( HAS-PAINT SPRAY-PAINTER ?OBJECT1 )
		( IDLE SPRAY-PAINTER )
		( UNSCHEDULED ?OBJECT0 )
		( TEMPERATURE ?OBJECT0 COLD )
		( PAINTED ?OBJECT0 ?OBJECT3 )
		( SURFACE-CONDITION ?OBJECT0 ?OBJECT4 )
	)
  :EFFECT
	( AND
		( BUSY SPRAY-PAINTER )
		( NOT ( IDLE SPRAY-PAINTER ) )
		( SCHEDULED ?OBJECT0 SPRAY-PAINTER )
		( NOT ( UNSCHEDULED ?OBJECT0 ) )
		( PAINTED ?OBJECT0 ?OBJECT1 )
		( NOT ( PAINTED ?OBJECT0 ?OBJECT3 ) )
		( SURFACE-CONDITION ?OBJECT0 UNDEFINED )
		( NOT ( SURFACE-CONDITION ?OBJECT0 ?OBJECT4 ) )
	)
)
( :ACTION DO-IMMERSION-PAINT
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 )
  :PRECONDITION
	( AND
		( PART ?OBJECT0 )
		( RU ?OBJECT2 )
		( HAS-PAINT IMMERSION-PAINTER ?OBJECT1 )
		( IDLE IMMERSION-PAINTER )
		( UNSCHEDULED ?OBJECT0 )
		( PAINTED ?OBJECT0 ?OBJECT3 )
	)
  :EFFECT
	( AND
		( BUSY IMMERSION-PAINTER )
		( NOT ( IDLE IMMERSION-PAINTER ) )
		( SCHEDULED ?OBJECT0 IMMERSION-PAINTER )
		( NOT ( UNSCHEDULED ?OBJECT0 ) )
		( PAINTED ?OBJECT0 ?OBJECT1 )
		( NOT ( PAINTED ?OBJECT0 ?OBJECT3 ) )
	)
)
( :ACTION DO-TIME-STEP
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 )
  :PRECONDITION
	( AND
		( RU ?OBJECT0 )
		( BUSY ?OBJECT2 )
		( SCHEDULED ?OBJECT1 ?OBJECT2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY ?OBJECT2 ) )
		( IDLE ?OBJECT2 )
		( NOT ( SCHEDULED ?OBJECT1 ?OBJECT2 ) )
		( UNSCHEDULED ?OBJECT1 )
	)
)
( :ACTION DELETE-STRIP-HOLES
  :PARAMETERS ( ?OBJECT0 ?OBJECT1 ?OBJECT2 ?OBJECT3 ?OBJECT4 )
  :PRECONDITION
	( AND
		( LINKED ?OBJECT0 ?OBJECT3 ?OBJECT4 ?OBJECT1 ?OBJECT2 )
		( LASTHOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 )
		( HAS-HOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 )
	)
  :EFFECT
	( AND
		( NOT ( LINKED ?OBJECT0 ?OBJECT3 ?OBJECT4 ?OBJECT1 ?OBJECT2 ) )
		( NOT ( LASTHOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 ) )
		( NOT ( HAS-HOLE ?OBJECT0 ?OBJECT1 ?OBJECT2 ) )
		( LASTHOLE ?OBJECT0 ?OBJECT3 ?OBJECT4 )
	)
)
)
