( DEFINE ( PROBLEM BINARY-NUMBER-V1S )
( :DOMAIN BINARY-ARITHMETICS )
( :OBJECTS
	I0 I1 I2 I3 - INDEX
)
( :INIT
	( AT I0 )
	( CURRENT-CONTENT V1 )
	( ADJACENT I0 I1 )
	( ADJACENT I1 I2 )
	( ADJACENT I2 I3 )
	( CONTENT I0 V1 )
	( CONTENT I1 V1 )
	( CONTENT I2 V1 )
	( CONTENT I3 EMPTY )
)
( :GOAL
	( AND
		( AT I3 )
	)
)
)
