( DEFINE ( DOMAIN BINARY-ARITHMETICS )
( :REQUIREMENTS :TYPING )
( :TYPES
	DIGIT - TERMINAL-SYMBOL
	TERMINAL-SYMBOL - OBJECT
	OPERATOR - TERMINAL-SYMBOL
	INDEX - OBJECT
)
( :CONSTANTS
	V0 V1 - DIGIT
	EMPTY - TERMINAL-SYMBOL
	ADD BORROW - OPERATOR
)
( :PREDICATES
	( AT ?INDEX0 - INDEX )
	( ADJACENT ?INDEX0 - INDEX ?INDEX1 - INDEX )
	( CONTENT ?INDEX0 - INDEX ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
	( CURRENT-CONTENT ?TERMINAL-SYMBOL0 - TERMINAL-SYMBOL )
)
( :ACTION PROCESS-V0
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V0 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V1
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V1 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-ADD
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADD )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT ADD ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-BORROW
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT BORROW )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT BORROW ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
)
