( DEFINE ( DOMAIN ARITHMETICS )
( :REQUIREMENTS :TYPING )
( :TYPES
	DIGIT - TERMINAL-SYMBOL
	TERMINAL-SYMBOL - OBJECT
	OPERATOR - TERMINAL-SYMBOL
	INDEX - OBJECT
)
( :CONSTANTS
	V0 V1 V2 V3 V4 V5 V6 V7 V8 V9 - DIGIT
	EMPTY - TERMINAL-SYMBOL
	ADD BORROW MULTIPLY DIVISION - OPERATOR
)
( :PREDICATES
	( AT ?INDEX0 - INDEX )
	( ADJACENT ?INDEX0 - INDEX ?INDEX1 - INDEX )
	( CONTENT ?INDEX0 - INDEX ?TERMINAL-SYMBOL1 - TERMINAL-SYMBOL )
	( CURRENT-CONTENT ?TERMINAL-SYMBOL0 - TERMINAL-SYMBOL )
)
( :ACTION PROCESS-V0
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V0 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V1
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V1 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V2
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V2 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V3
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V3 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V3 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V4
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V4 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V4 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V5
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V5 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V5 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V6
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V6 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V6 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V7
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V7 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V7 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V8
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V8 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V8 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-V9
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT V9 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT V9 ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-ADD
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT ADD )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT ADD ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-BORROW
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT BORROW )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT BORROW ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-MULTIPLY
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT MULTIPLY )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT MULTIPLY ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
( :ACTION PROCESS-DIVISION
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT DIVISION )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX0 - INDEX ?INDEX1 - INDEX ?TERMINAL-SYMBOL2 - TERMINAL-SYMBOL )
			( WHEN
				( AND
					( ADJACENT ?INDEX0 ?INDEX1 )
					( AT ?INDEX0 )
					( CONTENT ?INDEX1 ?TERMINAL-SYMBOL2 )
				)
				( AND
					( NOT ( AT ?INDEX0 ) )
					( AT ?INDEX1 )
					( NOT ( CURRENT-CONTENT DIVISION ) )
					( CURRENT-CONTENT ?TERMINAL-SYMBOL2 )
				)
			)
		)
	)
)
)
