( DEFINE ( PROBLEM MULTIPLY )
( :DOMAIN ARITHMETICS )
( :OBJECTS
	I0 I1 I2 I3 I4 I5 - INDEX
)
( :INIT
	( AT I0 )
	( CURRENT-CONTENT V1 )
	( ADJACENT I0 I1 )
	( ADJACENT I1 I2 )
	( ADJACENT I2 I3 )
	( ADJACENT I3 I4 )
	( ADJACENT I4 I5 )
	( CONTENT I0 V1 )
	( CONTENT I1 V1 )
	( CONTENT I2 MULTIPLY )
	( CONTENT I3 V0 )
	( CONTENT I4 V0 )
	( CONTENT I5 EMPTY )
)
( :GOAL
	( AND
		( AT I5 )
	)
)
)
