( DEFINE ( DOMAIN BLOCKS )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	BLOCK - OBJECT
	STACKROW - OBJECT
	STACKSTATE - OBJECT
)
( :CONSTANTS
	B1 B2 B3 - BLOCK
	ROW-0 - STACKROW
	STATE-0 STATE-1 STATE-2 STATE-3 - STACKSTATE
)
( :PREDICATES
	( ON ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
	( ONTABLE ?BLOCK0 - BLOCK )
	( CLEAR ?BLOCK0 - BLOCK )
	( HOLD ?BLOCK0 - BLOCK )
	( GREEN ?BLOCK0 - BLOCK )
	( HAVE ?BLOCK0 - BLOCK )
	( EMPTY )
	( FINISHED )
	( OBS-GREENISH )
	( EMPTY-COND-STACK ?STACKSTATE0 - STACKSTATE )
	( EMPTY-TRUE-GOTO-STACK ?STACKSTATE0 - STACKSTATE )
	( EMPTY-FALSE-GOTO-STACK ?STACKSTATE0 - STACKSTATE )
	( EMPTY-TACT-STACK ?STACKSTATE0 - STACKSTATE )
	( EMPTY-FACT-STACK ?STACKSTATE0 - STACKSTATE )
	( TRUE-NO-ACT-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-NO-ACT-0 ?STACKSTATE0 - STACKSTATE )
	( STATE-STACK ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
	( NEXT-STACK-ROW ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
	( TOP-STACK ?STACKROW0 - STACKROW )
	( STACK-PROCEDURE-0 ?STACKROW0 - STACKROW )
	( TEST-0 )
	( TEST-1 )
	( TEST-2 )
	( TEST-3 )
	( TEST-4 )
	( TRUE-CALL-0-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-CALL-0-0 ?STACKSTATE0 - STACKSTATE )
	( ACCUMULATOR-0 ?STACKROW0 - STACKROW )
	( DONE-EVALUATING-0 ?STACKROW0 - STACKROW )
	( DONE-APPLYING-0 ?STACKROW0 - STACKROW )
	( DONE-PROGRAMMING )
	( AVAILABLE-STATE ?STACKSTATE0 - STACKSTATE )
	( NEXT-STATE ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE )
	( NCOND-0 ?STACKSTATE0 - STACKSTATE )
	( TRUE-GOTO-0 ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE )
	( FALSE-GOTO-0 ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE )
	( COND-ON-0 ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK ?STACKSTATE2 - STACKSTATE )
	( COND-ONTABLE-0 ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE )
	( COND-CLEAR-0 ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE )
	( COND-HOLD-0 ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE )
	( COND-HAVE-0 ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE )
	( COND-EMPTY-0 ?STACKSTATE0 - STACKSTATE )
	( COND-FINISHED-0 ?STACKSTATE0 - STACKSTATE )
	( COND-OBS-GREENISH-0 ?STACKSTATE0 - STACKSTATE )
	( TRUE-UNSTACK-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-UNSTACK-0 ?STACKSTATE0 - STACKSTATE )
	( TRUE-DROP-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-DROP-0 ?STACKSTATE0 - STACKSTATE )
	( TRUE-COLLECT-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-COLLECT-0 ?STACKSTATE0 - STACKSTATE )
	( END-COND-0-0 )
	( END-COND-0-1 )
	( END-COND-0-2 )
	( END-COND-0-3 )
)
( :FUNCTIONS
	( TOTAL-COST )
)
( :ACTION PROGRAM-TRUE-NO-ACT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-NO-ACT-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-NO-ACT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-NO-ACT-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-TRUE-UNSTACK-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-UNSTACK-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-UNSTACK-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-UNSTACK-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-TRUE-DROP-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-DROP-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-DROP-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-DROP-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-TRUE-COLLECT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-COLLECT-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-COLLECT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-COLLECT-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-END-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-PROCEDURE-0 ?STACKROW0 )
		( STATE-STACK STATE-3 ?STACKROW0 )
		( EMPTY-COND-STACK STATE-3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK STATE-3 ) )
		( END-COND-0-3 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-NOCOND-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-COND-STACK ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE0 ) )
		( NCOND-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-COND-ON-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK ?STACKSTATE2 - STACKSTATE ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-PROCEDURE-0 ?STACKROW3 )
		( STATE-STACK ?STACKSTATE2 ?STACKROW3 )
		( EMPTY-COND-STACK ?STACKSTATE2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE2 ) )
		( COND-ON-0 ?BLOCK0 ?BLOCK1 ?STACKSTATE2 )
	)
)
( :ACTION PROGRAM-COND-ONTABLE-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( EMPTY-COND-STACK ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE1 ) )
		( COND-ONTABLE-0 ?BLOCK0 ?STACKSTATE1 )
	)
)
( :ACTION PROGRAM-COND-CLEAR-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( EMPTY-COND-STACK ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE1 ) )
		( COND-CLEAR-0 ?BLOCK0 ?STACKSTATE1 )
	)
)
( :ACTION PROGRAM-COND-HOLD-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( EMPTY-COND-STACK ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE1 ) )
		( COND-HOLD-0 ?BLOCK0 ?STACKSTATE1 )
	)
)
( :ACTION PROGRAM-COND-HAVE-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( EMPTY-COND-STACK ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE1 ) )
		( COND-HAVE-0 ?BLOCK0 ?STACKSTATE1 )
	)
)
( :ACTION PROGRAM-COND-EMPTY-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-COND-STACK ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE0 ) )
		( COND-EMPTY-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-COND-FINISHED-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-COND-STACK ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE0 ) )
		( COND-FINISHED-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-COND-OBS-GREENISH-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-COND-STACK ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE0 ) )
		( COND-OBS-GREENISH-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-TRUE-GOTO-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( ACCUMULATOR-0 ?STACKROW2 )
		( DONE-APPLYING-0 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW2 )
		( EMPTY-TRUE-GOTO-STACK ?STACKSTATE0 )
		( AVAILABLE-STATE ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TRUE-GOTO-STACK ?STACKSTATE0 ) )
		( TRUE-GOTO-0 ?STACKSTATE0 ?STACKSTATE1 )
		( FORALL
			( ?STACKSTATE3 - STACKSTATE )
			( WHEN
				( NEXT-STATE ?STACKSTATE1 ?STACKSTATE3 )
				( AVAILABLE-STATE ?STACKSTATE3 )
			)
		)
	)
)
( :ACTION PROGRAM-FALSE-GOTO-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( NOT ( ACCUMULATOR-0 ?STACKROW2 ) )
		( DONE-APPLYING-0 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW2 )
		( EMPTY-FALSE-GOTO-STACK ?STACKSTATE0 )
		( AVAILABLE-STATE ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FALSE-GOTO-STACK ?STACKSTATE0 ) )
		( FALSE-GOTO-0 ?STACKSTATE0 ?STACKSTATE1 )
		( FORALL
			( ?STACKSTATE3 - STACKSTATE )
			( WHEN
				( NEXT-STATE ?STACKSTATE1 ?STACKSTATE3 )
				( AVAILABLE-STATE ?STACKSTATE3 )
			)
		)
	)
)
( :ACTION PROGRAM-TRUE-CALL-0-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-CALL-0-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-CALL-0-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-CALL-0-0 ?STACKSTATE0 )
	)
)
( :ACTION REPEAT-TRUE-NO-ACT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-NO-ACT-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-NO-ACT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-NO-ACT-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-TRUE-UNSTACK-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-UNSTACK-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?BLOCK2 - BLOCK ?BLOCK3 - BLOCK )
			( AND
				( WHEN
					( AND
						( NOT ( FINISHED ) )
						( CLEAR ?BLOCK2 )
						( ON ?BLOCK2 ?BLOCK3 )
						( EMPTY )
					)
					( AND
						( HOLD ?BLOCK2 )
						( CLEAR ?BLOCK3 )
						( NOT ( CLEAR ?BLOCK2 ) )
						( NOT ( ON ?BLOCK2 ?BLOCK3 ) )
						( NOT ( EMPTY ) )
					)
				)
				( WHEN
					( AND
						( NOT ( FINISHED ) )
						( CLEAR ?BLOCK2 )
						( ONTABLE ?BLOCK2 )
						( EMPTY )
					)
					( AND
						( HOLD ?BLOCK2 )
						( NOT ( CLEAR ?BLOCK2 ) )
						( NOT ( ONTABLE ?BLOCK2 ) )
						( NOT ( EMPTY ) )
					)
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-UNSTACK-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-UNSTACK-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?BLOCK2 - BLOCK ?BLOCK3 - BLOCK )
			( AND
				( WHEN
					( AND
						( NOT ( FINISHED ) )
						( CLEAR ?BLOCK2 )
						( ON ?BLOCK2 ?BLOCK3 )
						( EMPTY )
					)
					( AND
						( HOLD ?BLOCK2 )
						( CLEAR ?BLOCK3 )
						( NOT ( CLEAR ?BLOCK2 ) )
						( NOT ( ON ?BLOCK2 ?BLOCK3 ) )
						( NOT ( EMPTY ) )
					)
				)
				( WHEN
					( AND
						( NOT ( FINISHED ) )
						( CLEAR ?BLOCK2 )
						( ONTABLE ?BLOCK2 )
						( EMPTY )
					)
					( AND
						( HOLD ?BLOCK2 )
						( NOT ( CLEAR ?BLOCK2 ) )
						( NOT ( ONTABLE ?BLOCK2 ) )
						( NOT ( EMPTY ) )
					)
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-TRUE-DROP-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-DROP-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?BLOCK2 - BLOCK )
			( WHEN
				( AND
					( NOT ( FINISHED ) )
					( HOLD ?BLOCK2 )
				)
				( AND
					( EMPTY )
					( NOT ( HOLD ?BLOCK2 ) )
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-DROP-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-DROP-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?BLOCK2 - BLOCK )
			( WHEN
				( AND
					( NOT ( FINISHED ) )
					( HOLD ?BLOCK2 )
				)
				( AND
					( EMPTY )
					( NOT ( HOLD ?BLOCK2 ) )
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-TRUE-COLLECT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-COLLECT-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?BLOCK2 - BLOCK )
			( WHEN
				( AND
					( NOT ( FINISHED ) )
					( HOLD ?BLOCK2 )
				)
				( AND
					( HAVE ?BLOCK2 )
					( EMPTY )
					( FINISHED )
					( NOT ( HOLD ?BLOCK2 ) )
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-COLLECT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-COLLECT-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?BLOCK2 - BLOCK )
			( WHEN
				( AND
					( NOT ( FINISHED ) )
					( HOLD ?BLOCK2 )
				)
				( AND
					( HAVE ?BLOCK2 )
					( EMPTY )
					( FINISHED )
					( NOT ( HOLD ?BLOCK2 ) )
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-TRUE-GOTO-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( TRUE-GOTO-0 ?STACKSTATE0 ?STACKSTATE1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW2 )
		( DONE-EVALUATING-0 ?STACKROW2 )
		( ACCUMULATOR-0 ?STACKROW2 )
		( DONE-APPLYING-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
		( NOT ( DONE-APPLYING-0 ?STACKROW2 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW2 ) )
		( NOT ( STATE-STACK ?STACKSTATE0 ?STACKROW2 ) )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
	)
)
( :ACTION REPEAT-FALSE-GOTO-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( FALSE-GOTO-0 ?STACKSTATE0 ?STACKSTATE1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW2 )
		( DONE-EVALUATING-0 ?STACKROW2 )
		( NOT ( ACCUMULATOR-0 ?STACKROW2 ) )
		( DONE-APPLYING-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
		( NOT ( DONE-APPLYING-0 ?STACKROW2 ) )
		( NOT ( STATE-STACK ?STACKSTATE0 ?STACKROW2 ) )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
	)
)
( :ACTION EVAL-NOCOND-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( NCOND-0 ?STACKSTATE0 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
)
( :ACTION EVAL-COND-ON-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK ?STACKSTATE2 - STACKSTATE ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-PROCEDURE-0 ?STACKROW3 )
		( STATE-STACK ?STACKSTATE2 ?STACKROW3 )
		( COND-ON-0 ?BLOCK0 ?BLOCK1 ?STACKSTATE2 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW3 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW3 )
		( WHEN
			( ON ?BLOCK0 ?BLOCK1 )
			( AND
				( ACCUMULATOR-0 ?STACKROW3 )
			)
		)
	)
)
( :ACTION EVAL-COND-ONTABLE-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( COND-ONTABLE-0 ?BLOCK0 ?STACKSTATE1 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( WHEN
			( ONTABLE ?BLOCK0 )
			( AND
				( ACCUMULATOR-0 ?STACKROW2 )
			)
		)
	)
)
( :ACTION EVAL-COND-CLEAR-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( COND-CLEAR-0 ?BLOCK0 ?STACKSTATE1 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( WHEN
			( CLEAR ?BLOCK0 )
			( AND
				( ACCUMULATOR-0 ?STACKROW2 )
			)
		)
	)
)
( :ACTION EVAL-COND-HOLD-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( COND-HOLD-0 ?BLOCK0 ?STACKSTATE1 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( WHEN
			( HOLD ?BLOCK0 )
			( AND
				( ACCUMULATOR-0 ?STACKROW2 )
			)
		)
	)
)
( :ACTION EVAL-COND-HAVE-0
  :PARAMETERS ( ?BLOCK0 - BLOCK ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( COND-HAVE-0 ?BLOCK0 ?STACKSTATE1 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( WHEN
			( HAVE ?BLOCK0 )
			( AND
				( ACCUMULATOR-0 ?STACKROW2 )
			)
		)
	)
)
( :ACTION EVAL-COND-EMPTY-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( COND-EMPTY-0 ?STACKSTATE0 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW1 )
		( WHEN
			( EMPTY )
			( AND
				( ACCUMULATOR-0 ?STACKROW1 )
			)
		)
	)
)
( :ACTION EVAL-COND-FINISHED-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( COND-FINISHED-0 ?STACKSTATE0 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW1 )
		( WHEN
			( FINISHED )
			( AND
				( ACCUMULATOR-0 ?STACKROW1 )
			)
		)
	)
)
( :ACTION EVAL-COND-OBS-GREENISH-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( COND-OBS-GREENISH-0 ?STACKSTATE0 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW1 )
		( FORALL
			( ?BLOCK2 - BLOCK )
			( WHEN
				( AND
					( CLEAR ?BLOCK2 )
					( GREEN ?BLOCK2 )
				)
				( AND
					( ACCUMULATOR-0 ?STACKROW1 )
				)
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-0-1
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-0 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-1 ROW-0 )
		( END-COND-0-1 )
		( HAVE B2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STATE-STACK STATE-1 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B1 )
		( ONTABLE B2 )
		( ON B1 B2 )
		( EMPTY )
		( GREEN B1 )
	)
)
( :ACTION REPEAT-END-MAIN-0-0-2
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-0 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-2 ROW-0 )
		( END-COND-0-2 )
		( HAVE B2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STATE-STACK STATE-2 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B1 )
		( ONTABLE B2 )
		( ON B1 B2 )
		( EMPTY )
		( GREEN B1 )
	)
)
( :ACTION REPEAT-END-MAIN-0-0-3
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-0 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-3 ROW-0 )
		( END-COND-0-3 )
		( HAVE B2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STATE-STACK STATE-3 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B1 )
		( ONTABLE B2 )
		( ON B1 B2 )
		( EMPTY )
		( GREEN B1 )
	)
)
( :ACTION REPEAT-END-MAIN-1-0-1
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-1 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-1 ROW-0 )
		( END-COND-0-1 )
		( HAVE B1 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-1 ) )
		( TEST-2 )
		( NOT ( STATE-STACK STATE-1 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B2 )
		( ONTABLE B1 )
		( ON B2 B1 )
		( EMPTY )
		( GREEN B2 )
	)
)
( :ACTION REPEAT-END-MAIN-1-0-2
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-1 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-2 ROW-0 )
		( END-COND-0-2 )
		( HAVE B1 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-1 ) )
		( TEST-2 )
		( NOT ( STATE-STACK STATE-2 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B2 )
		( ONTABLE B1 )
		( ON B2 B1 )
		( EMPTY )
		( GREEN B2 )
	)
)
( :ACTION REPEAT-END-MAIN-1-0-3
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-1 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-3 ROW-0 )
		( END-COND-0-3 )
		( HAVE B1 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-1 ) )
		( TEST-2 )
		( NOT ( STATE-STACK STATE-3 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B2 )
		( ONTABLE B1 )
		( ON B2 B1 )
		( EMPTY )
		( GREEN B2 )
	)
)
( :ACTION REPEAT-END-MAIN-2-0-1
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-2 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-1 ROW-0 )
		( END-COND-0-1 )
		( HAVE B2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-2 ) )
		( TEST-3 )
		( NOT ( STATE-STACK STATE-1 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B1 )
		( ONTABLE B3 )
		( ON B1 B2 )
		( ON B2 B3 )
		( EMPTY )
		( GREEN B3 )
	)
)
( :ACTION REPEAT-END-MAIN-2-0-2
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-2 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-2 ROW-0 )
		( END-COND-0-2 )
		( HAVE B2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-2 ) )
		( TEST-3 )
		( NOT ( STATE-STACK STATE-2 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B1 )
		( ONTABLE B3 )
		( ON B1 B2 )
		( ON B2 B3 )
		( EMPTY )
		( GREEN B3 )
	)
)
( :ACTION REPEAT-END-MAIN-2-0-3
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-2 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-3 ROW-0 )
		( END-COND-0-3 )
		( HAVE B2 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-2 ) )
		( TEST-3 )
		( NOT ( STATE-STACK STATE-3 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B1 )
		( ONTABLE B3 )
		( ON B1 B2 )
		( ON B2 B3 )
		( EMPTY )
		( GREEN B3 )
	)
)
( :ACTION REPEAT-END-MAIN-3-0-1
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-3 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-1 ROW-0 )
		( END-COND-0-1 )
		( HAVE B3 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-3 ) )
		( TEST-4 )
		( NOT ( STATE-STACK STATE-1 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B3 )
		( ONTABLE B1 )
		( ON B3 B2 )
		( ON B2 B1 )
		( EMPTY )
		( GREEN B3 )
	)
)
( :ACTION REPEAT-END-MAIN-3-0-2
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-3 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-2 ROW-0 )
		( END-COND-0-2 )
		( HAVE B3 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-3 ) )
		( TEST-4 )
		( NOT ( STATE-STACK STATE-2 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B3 )
		( ONTABLE B1 )
		( ON B3 B2 )
		( ON B2 B1 )
		( EMPTY )
		( GREEN B3 )
	)
)
( :ACTION REPEAT-END-MAIN-3-0-3
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-3 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-3 ROW-0 )
		( END-COND-0-3 )
		( HAVE B3 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-3 ) )
		( TEST-4 )
		( NOT ( STATE-STACK STATE-3 ROW-0 ) )
		( STATE-STACK STATE-0 ROW-0 )
		( FORALL
			( ?BLOCK0 - BLOCK ?BLOCK1 - BLOCK )
			( NOT ( ON ?BLOCK0 ?BLOCK1 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( ONTABLE ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( CLEAR ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HOLD ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( GREEN ?BLOCK0 ) )
		)
		( FORALL
			( ?BLOCK0 - BLOCK )
			( NOT ( HAVE ?BLOCK0 ) )
		)
		( NOT ( EMPTY ) )
		( NOT ( FINISHED ) )
		( CLEAR B3 )
		( ONTABLE B1 )
		( ON B3 B2 )
		( ON B2 B1 )
		( EMPTY )
		( GREEN B3 )
	)
)
( :ACTION REPEAT-END-MAIN-4-0-1
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-4 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-1 ROW-0 )
		( END-COND-0-1 )
		( HAVE B3 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-4-0-2
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-4 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-2 ROW-0 )
		( END-COND-0-2 )
		( HAVE B3 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-4-0-3
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-4 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-3 ROW-0 )
		( END-COND-0-3 )
		( HAVE B3 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-1 ?STACKROW1 )
		( END-COND-0-1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-1 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-2 ?STACKROW1 )
		( END-COND-0-2 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-2 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-3 ?STACKROW1 )
		( END-COND-0-3 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-3 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-1-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-1 ?STACKROW1 )
		( END-COND-0-1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-1 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-1-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-2 ?STACKROW1 )
		( END-COND-0-2 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-2 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-1-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-3 ?STACKROW1 )
		( END-COND-0-3 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-3 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-2-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-1 ?STACKROW1 )
		( END-COND-0-1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-1 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-2-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-2 ?STACKROW1 )
		( END-COND-0-2 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-2 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-2-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-3 ?STACKROW1 )
		( END-COND-0-3 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-3 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-3-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-1 ?STACKROW1 )
		( END-COND-0-1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-1 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-3-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-2 ?STACKROW1 )
		( END-COND-0-2 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-2 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-3-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-3 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-3 ?STACKROW1 )
		( END-COND-0-3 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-3 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-4-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-4 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-1 ?STACKROW1 )
		( END-COND-0-1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-1 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-4-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-4 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-2 ?STACKROW1 )
		( END-COND-0-2 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-2 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-4-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-4 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-3 ?STACKROW1 )
		( END-COND-0-3 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-3 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-TRUE-CALL-0-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-CALL-0-0 ?STACKSTATE0 )
		( NEXT-STACK-ROW ?STACKROW1 ?STACKROW2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK STATE-0 ?STACKROW2 )
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-CALL-0-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-CALL-0-0 ?STACKSTATE0 )
		( NEXT-STACK-ROW ?STACKROW1 ?STACKROW2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK STATE-0 ?STACKROW2 )
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
)
