# POSITIVES
./gen.py NEGLITE 1 0 a
./gen.py NEGLITE 2 0 a
./gen.py NEGLITE 3 0 a
./gen.py NEGLITE 4 0 a
./gen.py NEGLITE 1 0 b
./gen.py NEGLITE 2 0 b
./gen.py NEGLITE 3 0 b
./gen.py NEGLITE 4 0 b
./gen.py NEGLITE 1 0 c
./gen.py NEGLITE 2 0 c
./gen.py NEGLITE 3 0 c
./gen.py NEGLITE 4 0 c
./gen.py NEGLITE 1 0 d
./gen.py NEGLITE 2 0 d
./gen.py NEGLITE 3 0 d
./gen.py NEGLITE 4 0 d

# NEGLITES
./gen.py NEGLITE 1 1 a
./gen.py NEGLITE 2 1 a
./gen.py NEGLITE 3 1 a
./gen.py NEGLITE 4 1 a
./gen.py NEGLITE 1 1 b
./gen.py NEGLITE 2 1 b
./gen.py NEGLITE 3 1 b
./gen.py NEGLITE 4 1 b
./gen.py NEGLITE 1 1 c
./gen.py NEGLITE 2 1 c
./gen.py NEGLITE 3 1 c
./gen.py NEGLITE 4 1 c
./gen.py NEGLITE 1 1 d
./gen.py NEGLITE 2 1 d
./gen.py NEGLITE 3 1 d
./gen.py NEGLITE 4 1 d
./gen.py NEGLITE 1 2 a
./gen.py NEGLITE 2 2 a
./gen.py NEGLITE 3 2 a
./gen.py NEGLITE 1 2 b
./gen.py NEGLITE 2 2 b
./gen.py NEGLITE 3 2 b
./gen.py NEGLITE 1 2 c
./gen.py NEGLITE 2 2 c
./gen.py NEGLITE 3 2 c
./gen.py NEGLITE 1 2 d
./gen.py NEGLITE 2 2 d
./gen.py NEGLITE 3 2 d
./gen.py NEGLITE 1 3 a
./gen.py NEGLITE 2 3 a
./gen.py NEGLITE 1 3 b
./gen.py NEGLITE 2 3 b
./gen.py NEGLITE 1 3 c
./gen.py NEGLITE 2 3 c
./gen.py NEGLITE 1 3 d
./gen.py NEGLITE 2 3 d
./gen.py NEGLITE 1 4 a
./gen.py NEGLITE 1 4 b
./gen.py NEGLITE 1 4 c
./gen.py NEGLITE 1 4 d


# NEG
./gen.py NEG 1 1 a
./gen.py NEG 2 1 a
./gen.py NEG 3 1 a
./gen.py NEG 4 1 a
./gen.py NEG 1 1 b
./gen.py NEG 2 1 b
./gen.py NEG 3 1 b
./gen.py NEG 4 1 b
./gen.py NEG 1 1 c
./gen.py NEG 2 1 c
./gen.py NEG 3 1 c
./gen.py NEG 4 1 c
./gen.py NEG 1 1 d
./gen.py NEG 2 1 d
./gen.py NEG 3 1 d
./gen.py NEG 4 1 d
./gen.py NEG 1 2 a
./gen.py NEG 2 2 a
./gen.py NEG 3 2 a
./gen.py NEG 1 2 b
./gen.py NEG 2 2 b
./gen.py NEG 3 2 b
./gen.py NEG 1 2 c
./gen.py NEG 2 2 c
./gen.py NEG 3 2 c
./gen.py NEG 1 2 d
./gen.py NEG 2 2 d
./gen.py NEG 3 2 d
./gen.py NEG 1 3 a
./gen.py NEG 2 3 a
./gen.py NEG 1 3 b
./gen.py NEG 2 3 b
./gen.py NEG 1 3 c
./gen.py NEG 2 3 c
./gen.py NEG 1 3 d
./gen.py NEG 2 3 d
./gen.py NEG 1 4 a
./gen.py NEG 1 4 b
./gen.py NEG 1 4 c
./gen.py NEG 1 4 d

