(define (problem pneg-10)
  (:domain list )
  (:objects  n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 - node 
  )
  (:init
	( at n9) ( goal n2)
	( adjacent n9 n6)
	( adjacent n6 n4)
	( adjacent n4 n7)
	( adjacent n7 n5)
	( adjacent n5 n10)
	( adjacent n10 n8)
	( adjacent n8 n3)
	( adjacent n3 n1)
	( adjacent n1 n2) )
  (:goal
	( and
	( at n2) ( visited n2)
	( visited n9 )
	( visited n6 )
	( visited n4 )
	( visited n7 )
	( visited n5 )
	( not ( visited n10 ) )
	( visited n8 )
	( visited n3 )
	( visited n1 )
	( checked n9 )
	( checked n6 )
	( checked n4 )
	( not ( checked n7 ) )
	( checked n5 )
	( checked n10 )
	( not ( checked n8 ) )
	( checked n3 )
	( checked n1 )
	)
  )
)