( DEFINE ( DOMAIN ANBN )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	INDEX - OBJECT
	LETTER - OBJECT
	STACKROW - OBJECT
	STACKSTATE - OBJECT
)
( :CONSTANTS
	I0 I1 I2 I3 I4 I5 I6 I7 I8 - INDEX
	A B EMPTY - LETTER
	ROW-0 ROW-1 ROW-2 ROW-3 ROW-4 - STACKROW
	STATE-0 STATE-1 STATE-2 - STACKSTATE
)
( :PREDICATES
	( AT ?INDEX0 - INDEX )
	( ADJACENT ?INDEX0 - INDEX ?INDEX1 - INDEX )
	( CONTENT ?INDEX0 - INDEX ?LETTER1 - LETTER )
	( CURRENT-CONTENT ?LETTER0 - LETTER )
	( EMPTY-COND-STACK ?STACKSTATE0 - STACKSTATE )
	( EMPTY-TRUE-GOTO-STACK ?STACKSTATE0 - STACKSTATE )
	( EMPTY-FALSE-GOTO-STACK ?STACKSTATE0 - STACKSTATE )
	( EMPTY-TACT-STACK ?STACKSTATE0 - STACKSTATE )
	( EMPTY-FACT-STACK ?STACKSTATE0 - STACKSTATE )
	( TRUE-NO-ACT-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-NO-ACT-0 ?STACKSTATE0 - STACKSTATE )
	( STATE-STACK ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
	( NEXT-STACK-ROW ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
	( TOP-STACK ?STACKROW0 - STACKROW )
	( STACK-PROCEDURE-0 ?STACKROW0 - STACKROW )
	( TEST-0 )
	( TRUE-CALL-0-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-CALL-0-0 ?STACKSTATE0 - STACKSTATE )
	( ACCUMULATOR-0 ?STACKROW0 - STACKROW )
	( DONE-EVALUATING-0 ?STACKROW0 - STACKROW )
	( DONE-APPLYING-0 ?STACKROW0 - STACKROW )
	( DONE-PROGRAMMING )
	( AVAILABLE-STATE ?STACKSTATE0 - STACKSTATE )
	( NEXT-STATE ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE )
	( NCOND-0 ?STACKSTATE0 - STACKSTATE )
	( TRUE-GOTO-0 ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE )
	( FALSE-GOTO-0 ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE )
	( COND-AT-0 ?INDEX0 - INDEX ?STACKSTATE1 - STACKSTATE )
	( COND-CURRENT-CONTENT-0 ?LETTER0 - LETTER ?STACKSTATE1 - STACKSTATE )
	( TRUE-PROCESS-A-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-PROCESS-A-0 ?STACKSTATE0 - STACKSTATE )
	( TRUE-PROCESS-B-0 ?STACKSTATE0 - STACKSTATE )
	( FALSE-PROCESS-B-0 ?STACKSTATE0 - STACKSTATE )
	( END-COND-0-0 )
	( END-COND-0-1 )
	( END-COND-0-2 )
)
( :FUNCTIONS
	( TOTAL-COST )
)
( :ACTION PROGRAM-TRUE-NO-ACT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-NO-ACT-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-NO-ACT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-NO-ACT-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-TRUE-PROCESS-A-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT A )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-PROCESS-A-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-PROCESS-A-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT A )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-PROCESS-A-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-TRUE-PROCESS-B-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT B )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-PROCESS-B-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-PROCESS-B-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT B )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-PROCESS-B-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-END-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-PROCEDURE-0 ?STACKROW0 )
		( STATE-STACK STATE-2 ?STACKROW0 )
		( EMPTY-COND-STACK STATE-2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK STATE-2 ) )
		( END-COND-0-2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-NOCOND-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-COND-STACK ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE0 ) )
		( NCOND-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-COND-AT-0
  :PARAMETERS ( ?INDEX0 - INDEX ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( EMPTY-COND-STACK ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE1 ) )
		( COND-AT-0 ?INDEX0 ?STACKSTATE1 )
	)
)
( :ACTION PROGRAM-COND-CURRENT-CONTENT-0
  :PARAMETERS ( ?LETTER0 - LETTER ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( EMPTY-COND-STACK ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-COND-STACK ?STACKSTATE1 ) )
		( COND-CURRENT-CONTENT-0 ?LETTER0 ?STACKSTATE1 )
	)
)
( :ACTION PROGRAM-TRUE-GOTO-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( ACCUMULATOR-0 ?STACKROW2 )
		( DONE-APPLYING-0 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW2 )
		( EMPTY-TRUE-GOTO-STACK ?STACKSTATE0 )
		( AVAILABLE-STATE ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TRUE-GOTO-STACK ?STACKSTATE0 ) )
		( TRUE-GOTO-0 ?STACKSTATE0 ?STACKSTATE1 )
		( FORALL
			( ?STACKSTATE3 - STACKSTATE )
			( WHEN
				( NEXT-STATE ?STACKSTATE1 ?STACKSTATE3 )
				( AVAILABLE-STATE ?STACKSTATE3 )
			)
		)
	)
)
( :ACTION PROGRAM-FALSE-GOTO-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( NOT ( ACCUMULATOR-0 ?STACKROW2 ) )
		( DONE-APPLYING-0 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW2 )
		( EMPTY-FALSE-GOTO-STACK ?STACKSTATE0 )
		( AVAILABLE-STATE ?STACKSTATE1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FALSE-GOTO-STACK ?STACKSTATE0 ) )
		( FALSE-GOTO-0 ?STACKSTATE0 ?STACKSTATE1 )
		( FORALL
			( ?STACKSTATE3 - STACKSTATE )
			( WHEN
				( NEXT-STATE ?STACKSTATE1 ?STACKSTATE3 )
				( AVAILABLE-STATE ?STACKSTATE3 )
			)
		)
	)
)
( :ACTION PROGRAM-TRUE-CALL-0-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-TACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-TACT-STACK ?STACKSTATE0 ) )
		( TRUE-CALL-0-0 ?STACKSTATE0 )
	)
)
( :ACTION PROGRAM-FALSE-CALL-0-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( EMPTY-FACT-STACK ?STACKSTATE0 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-FACT-STACK ?STACKSTATE0 ) )
		( FALSE-CALL-0-0 ?STACKSTATE0 )
	)
)
( :ACTION REPEAT-TRUE-NO-ACT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-NO-ACT-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-NO-ACT-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-NO-ACT-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-TRUE-PROCESS-A-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT A )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-PROCESS-A-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX2 - INDEX ?INDEX3 - INDEX ?LETTER4 - LETTER )
			( WHEN
				( AND
					( ADJACENT ?INDEX2 ?INDEX3 )
					( AT ?INDEX2 )
					( CONTENT ?INDEX3 ?LETTER4 )
				)
				( AND
					( NOT ( AT ?INDEX2 ) )
					( AT ?INDEX3 )
					( NOT ( CURRENT-CONTENT A ) )
					( CURRENT-CONTENT ?LETTER4 )
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-PROCESS-A-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT A )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-PROCESS-A-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX2 - INDEX ?INDEX3 - INDEX ?LETTER4 - LETTER )
			( WHEN
				( AND
					( ADJACENT ?INDEX2 ?INDEX3 )
					( AT ?INDEX2 )
					( CONTENT ?INDEX3 ?LETTER4 )
				)
				( AND
					( NOT ( AT ?INDEX2 ) )
					( AT ?INDEX3 )
					( NOT ( CURRENT-CONTENT A ) )
					( CURRENT-CONTENT ?LETTER4 )
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-TRUE-PROCESS-B-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT B )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-PROCESS-B-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX2 - INDEX ?INDEX3 - INDEX ?LETTER4 - LETTER )
			( WHEN
				( AND
					( ADJACENT ?INDEX2 ?INDEX3 )
					( AT ?INDEX2 )
					( CONTENT ?INDEX3 ?LETTER4 )
				)
				( AND
					( NOT ( AT ?INDEX2 ) )
					( AT ?INDEX3 )
					( NOT ( CURRENT-CONTENT B ) )
					( CURRENT-CONTENT ?LETTER4 )
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-PROCESS-B-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( CURRENT-CONTENT B )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-PROCESS-B-0 ?STACKSTATE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX2 - INDEX ?INDEX3 - INDEX ?LETTER4 - LETTER )
			( WHEN
				( AND
					( ADJACENT ?INDEX2 ?INDEX3 )
					( AT ?INDEX2 )
					( CONTENT ?INDEX3 ?LETTER4 )
				)
				( AND
					( NOT ( AT ?INDEX2 ) )
					( AT ?INDEX3 )
					( NOT ( CURRENT-CONTENT B ) )
					( CURRENT-CONTENT ?LETTER4 )
				)
			)
		)
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-TRUE-GOTO-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( TRUE-GOTO-0 ?STACKSTATE0 ?STACKSTATE1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW2 )
		( DONE-EVALUATING-0 ?STACKROW2 )
		( ACCUMULATOR-0 ?STACKROW2 )
		( DONE-APPLYING-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
		( NOT ( DONE-APPLYING-0 ?STACKROW2 ) )
		( NOT ( ACCUMULATOR-0 ?STACKROW2 ) )
		( NOT ( STATE-STACK ?STACKSTATE0 ?STACKROW2 ) )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
	)
)
( :ACTION REPEAT-FALSE-GOTO-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( FALSE-GOTO-0 ?STACKSTATE0 ?STACKSTATE1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW2 )
		( DONE-EVALUATING-0 ?STACKROW2 )
		( NOT ( ACCUMULATOR-0 ?STACKROW2 ) )
		( DONE-APPLYING-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
		( NOT ( DONE-APPLYING-0 ?STACKROW2 ) )
		( NOT ( STATE-STACK ?STACKSTATE0 ?STACKROW2 ) )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
	)
)
( :ACTION EVAL-NOCOND-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( NCOND-0 ?STACKSTATE0 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW1 )
		( ACCUMULATOR-0 ?STACKROW1 )
	)
)
( :ACTION EVAL-COND-AT-0
  :PARAMETERS ( ?INDEX0 - INDEX ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( COND-AT-0 ?INDEX0 ?STACKSTATE1 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( WHEN
			( AT ?INDEX0 )
			( AND
				( ACCUMULATOR-0 ?STACKROW2 )
			)
		)
	)
)
( :ACTION EVAL-COND-CURRENT-CONTENT-0
  :PARAMETERS ( ?LETTER0 - LETTER ?STACKSTATE1 - STACKSTATE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK ?STACKSTATE1 ?STACKROW2 )
		( COND-CURRENT-CONTENT-0 ?LETTER0 ?STACKSTATE1 )
		( NOT ( DONE-EVALUATING-0 ?STACKROW2 ) )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING-0 ?STACKROW2 )
		( WHEN
			( CURRENT-CONTENT ?LETTER0 )
			( AND
				( ACCUMULATOR-0 ?STACKROW2 )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-0-1
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-0 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-1 ROW-0 )
		( END-COND-0-1 )
		( AT I8 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-0-0-2
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( TEST-0 )
		( TOP-STACK ROW-0 )
		( STATE-STACK STATE-2 ROW-0 )
		( END-COND-0-2 )
		( AT I8 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-1 ?STACKROW1 )
		( END-COND-0-1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-1 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-END-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK STATE-2 ?STACKROW1 )
		( END-COND-0-2 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STATE-STACK STATE-2 ?STACKROW1 ) )
		( NOT ( STACK-PROCEDURE-0 ?STACKROW1 ) )
	)
)
( :ACTION REPEAT-TRUE-CALL-0-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( ACCUMULATOR-0 ?STACKROW1 )
		( TRUE-CALL-0-0 ?STACKSTATE0 )
		( NEXT-STACK-ROW ?STACKROW1 ?STACKROW2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK STATE-0 ?STACKROW2 )
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
( :ACTION REPEAT-FALSE-CALL-0-0
  :PARAMETERS ( ?STACKSTATE0 - STACKSTATE ?STACKROW1 - STACKROW ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( NOT ( ACCUMULATOR-0 ?STACKROW1 ) )
		( FALSE-CALL-0-0 ?STACKSTATE0 )
		( NEXT-STACK-ROW ?STACKROW1 ?STACKROW2 )
		( TOP-STACK ?STACKROW1 )
		( STACK-PROCEDURE-0 ?STACKROW1 )
		( STATE-STACK ?STACKSTATE0 ?STACKROW1 )
		( DONE-EVALUATING-0 ?STACKROW1 )
		( NOT ( DONE-APPLYING-0 ?STACKROW1 ) )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW2 )
		( STACK-PROCEDURE-0 ?STACKROW2 )
		( STATE-STACK STATE-0 ?STACKROW2 )
		( DONE-APPLYING-0 ?STACKROW1 )
	)
)
)
