(define (problem trees5e)
	(:domain programming)
	(:objects
		left-child right-child internal visited - relation
		n1 n2 n3 n4 n5 - value
		current child - variable
	)
	(:init
		(assignment current n3)
		(copyable-2ary left-child)
		(copyable-2ary right-child)
		;(conditional-1ary internal)
		(achievable-1ary visited child)
		(achievable-1ary visited current)
		(includes-2ary left-child n3 n4)
		(includes-2ary right-child n4 n5)
		(includes-2ary left-child n5 n2)
		(includes-2ary right-child n2 n1)
		;(includes-1ary internal n2)
		;(includes-1ary internal n5)
		;(includes-1ary internal n4)
		(conditional-1ary visited)
		(includes-2ary left-child n2 null)
		(includes-2ary right-child n5 null)
		(includes-2ary left-child n4 null)
		(includes-2ary right-child n3 null)
	)
	(:goal (and
		(includes-1ary visited n1)
		(includes-1ary visited n2)
		(includes-1ary visited n3)
		(includes-1ary visited n4)
		(includes-1ary visited n5)
	))
)
