echo 'Fibonacci...'
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p1.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p2.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p3.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p4.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p5.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p6.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p7.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p8.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p9.pddl 300
./planner.sh domains/variables/domain.pddl domains/variables/fibonacci/p10.pddl 300

echo 'GreenBlock...'
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p10-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p10-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p20-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p20-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p30-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p30-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p40-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p40-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p50-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p50-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p60-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p60-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p70-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p70-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p80-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p80-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p90-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p90-b.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p100-a.pddl 60
./planner.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p100-b.pddl 60

echo 'Grid...'
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid5x5aa-2.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid5x5ab-2.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid5x5ba-2.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid5x5bb-2.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6aa.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6ab.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6ba.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6bb.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6aa-2.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6ab-2.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6ba-2.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6bb-2.pddl 300

echo 'Gripper...'
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p10.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p20.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p30.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p40.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p50.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p60.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p70.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p80.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p90.pddl 100
./planner.sh domains/other/gripper/domain.pddl domains/other/gripper/p100.pddl 100

echo 'Hall-A...'
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p2x2a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p2x2b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p2x2c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p2x2d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p3x3a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p3x3b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p3x3c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p3x3d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p4x4a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p4x4b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p4x4c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p4x4d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p5x5a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p5x5b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p5x5c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p5x5d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p6x6a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p6x6b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p6x6c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p6x6d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p7x7a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p7x7b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p7x7c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p7x7d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p8x8a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p8x8b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p8x8c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p8x8d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p9x9a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p9x9b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p9x9c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p9x9d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p10x10a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p10x10b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p10x10c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p10x10d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p20x20a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p20x20b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p20x20c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p20x20d.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p50x50a.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p50x50b.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p50x50c.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p50x50d.pddl 300


echo 'List...'
./planner.sh domains/old/list/domain.pddl domains/old/list/p10.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p20.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p30.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p40.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p50.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p60.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p70.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p80.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p90.pddl 300
./planner.sh domains/old/list/domain.pddl domains/old/list/p100.pddl 300

echo 'Reverse...'
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p2a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p2b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p2c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p2d.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p3a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p3b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p3c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p3d.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p4a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p4b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p4c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p4d.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p5a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p5b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p5c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p5d.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p6a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p6b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p6c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p6d.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p7a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p7b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p7c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p7d.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p8a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p8b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p8c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p8d.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p9a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p9b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p9c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p9d.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p10a.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p10b.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p10c.pddl 300
./planner.sh domains/pointers/domain.pddl domains/pointers/reverse/p10d.pddl 300

echo 'Sorting...'
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p3-3a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p3-3b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p3-3c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p3-3d.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p4-4a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p4-4b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p4-4c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p4-4d.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p5-5a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p5-5b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p5-5c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p5-5d.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p6-5a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p6-5b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p6-5c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p6-5d.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p7-5a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p7-5b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p7-5c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p7-5d.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p8-5a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p8-5b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p8-5c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p8-5d.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p9-5a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p9-5b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p9-5c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p9-5d.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-5a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-5b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-5c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-5d.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-10a.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-10b.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-10c.pddl 100
./planner.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-10d.pddl 100

echo 'Triangular Sum...'
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory2.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory6.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory10.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory15.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory21.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory28.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory36.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory45.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory55.pddl 100
./planner.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory120.pddl 100

echo 'Trees...'
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10a.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10b.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10c.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10d.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10e.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10f.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10g.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10h.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10i.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20a.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20b.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20c.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20d.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20e.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20f.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20g.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20h.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20i.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p40a.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p40b.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p40c.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p40d.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p100a.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p100b.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p100c.pddl 60
./planner.sh domains/other/trees/domain_alt.pddl domains/other/trees/p100d.pddl 60

echo 'Visitall...'
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p5.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p10.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p15.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p20.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p25.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p30.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p35.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p40.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p45.pddl 300
./planner.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p50.pddl 300

echo 'Visualm...'
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x2a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x2b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x2c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x2d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x3a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x3b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x3c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x3d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x2a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x2b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x2c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x2d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x3a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x3b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x3c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x3d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x3a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x3b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x3c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x3d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x4a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x4b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x4c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x4d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x4a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x4b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x4c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x4d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x4a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x4b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x4c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x4d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x5a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x5b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x5c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x5d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x5a.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x5b.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x5c.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x5d.pddl 300 
./planner.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p10x10.pddl 300 



