echo 'Fibonacci...'
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p1.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p2.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p3.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p4.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p5.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p6.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p7.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p8.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p9.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/fibonacci/p10.pddl

echo 'GreenBlock...'
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p10-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p10-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p20-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p20-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p30-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p30-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p40-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p40-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p50-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p50-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p60-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p60-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p70-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p70-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p80-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p80-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p90-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p90-b.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p100-a.pddl
./bfws.sh domains/other/blocks/domain_cl.pddl domains/other/blocks/p100-b.pddl

echo 'Grid...'
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid5x5aa-2.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid5x5ab-2.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid5x5ba-2.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid5x5bb-2.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6aa.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6ab.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6ba.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6bb.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6aa-2.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6ab-2.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6ba-2.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/grid/grid6x6bb-2.pddl

echo 'Gripper...'
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p10.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p20.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p30.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p40.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p50.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p60.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p70.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p80.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p90.pddl
./bfws.sh domains/other/gripper/domain.pddl domains/other/gripper/p100.pddl

echo 'Hall-A...'
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p2x2a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p2x2b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p2x2c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p2x2d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p3x3a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p3x3b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p3x3c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p3x3d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p4x4a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p4x4b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p4x4c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p4x4d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p5x5a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p5x5b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p5x5c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p5x5d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p6x6a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p6x6b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p6x6c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p6x6d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p7x7a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p7x7b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p7x7c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p7x7d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p8x8a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p8x8b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p8x8c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p8x8d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p9x9a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p9x9b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p9x9c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p9x9d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p10x10a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p10x10b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p10x10c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p10x10d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p20x20a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p20x20b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p20x20c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p20x20d.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p50x50a.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p50x50b.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p50x50c.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/hallA/p50x50d.pddl


echo 'List...'
./bfws.sh domains/old/list/domain.pddl domains/old/list/p10.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p20.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p30.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p40.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p50.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p60.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p70.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p80.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p90.pddl
./bfws.sh domains/old/list/domain.pddl domains/old/list/p100.pddl

echo 'Reverse...'
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p2a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p2b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p2c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p2d.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p3a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p3b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p3c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p3d.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p4a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p4b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p4c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p4d.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p5a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p5b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p5c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p5d.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p6a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p6b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p6c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p6d.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p7a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p7b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p7c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p7d.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p8a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p8b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p8c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p8d.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p9a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p9b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p9c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p9d.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p10a.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p10b.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p10c.pddl
./bfws.sh domains/pointers/domain.pddl domains/pointers/reverse/p10d.pddl

echo 'Sorting...'
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p3-3a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p3-3b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p3-3c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p3-3d.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p4-4a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p4-4b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p4-4c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p4-4d.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p5-5a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p5-5b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p5-5c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p5-5d.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p6-5a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p6-5b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p6-5c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p6-5d.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p7-5a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p7-5b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p7-5c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p7-5d.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p8-5a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p8-5b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p8-5c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p8-5d.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p9-5a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p9-5b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p9-5c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p9-5d.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-5a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-5b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-5c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-5d.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-10a.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-10b.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-10c.pddl
./bfws.sh domains/other/sorting/domain_cl.pddl domains/other/sorting/p10-10d.pddl

echo 'Triangular Sum...'
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory2.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory6.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory10.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory15.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory21.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory28.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory36.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory45.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory55.pddl
./bfws.sh domains/variables/domain.pddl domains/variables/sumatory/sumatory120.pddl

echo 'Trees...'
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10a.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10b.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10c.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10d.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10e.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10f.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10g.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10h.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p10i.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20a.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20b.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20c.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20d.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20e.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20f.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20g.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20h.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p20i.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p40a.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p40b.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p40c.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p40d.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p100a.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p100b.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p100c.pddl
./bfws.sh domains/other/trees/domain_alt.pddl domains/other/trees/p100d.pddl

echo 'Visitall...'
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p5.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p10.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p15.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p20.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p25.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p30.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p35.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p40.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p45.pddl
./bfws.sh domains/variables-output/domain.pddl domains/variables-output/visitall/p50.pddl

echo 'Visualm...'
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x2a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x2b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x2c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x2d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x3a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x3b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x3c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p2x3d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x2a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x2b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x2c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x2d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x3a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x3b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x3c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x3d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x3a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x3b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x3c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x3d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x4a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x4b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x4c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p3x4d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x4a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x4b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x4c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x4d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x4a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x4b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x4c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x4d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x5a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x5b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x5c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p4x5d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x5a.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x5b.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x5c.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p5x5d.pddl 
./bfws.sh domains/other/visualm/domain-2steps.pddl domains/other/visualm/p10x10.pddl 



